
```{r setup}
#| include: false
library(rvest)
library(xml2)
library(dplyr)
library(purrr)
library(stringr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(knitr)
options(knitr.kable.NA = '')
library(kableExtra)
library(readxl)
theme_set(theme_bw())
library(patchwork)
library(forcats)
```

# Executive Summary

The Statistics department at UNL is an integral part of the university infrastructure, and like other essential infrastructure (roads, plumbing, electricity), it can be easy to overlook our contributions to the university ecosystem. 

Statistics courses are used across campus to instill quantitative literacy (Stat 218, 380), teach undergraduate and graduate students the basic skills they need for domain research and job training(Stat 462, 463, 801, 802, 850, 870), and to provide advanced statistical education (Stat 821, 822, 823, 882, 883, 950) for a variety of different disciplines including agronomy, statistical genetics, and finance. 

Statistics also serves two different research functions: we conduct our own research, which leads to methods which are more efficient both in terms of data collection (e.g. better analyses, software packages, etc.) and in how data are written up for publication (knitr, rmarkdown, ggplot2). In addition to our research, however, we also serve as collaborators on domain research problems.
These problems can inspire new statistical research questions, but even when that does not occur, collaborative activity emphasizes the relational aspects of statistics. While collaborations can take a long time to produce measurable fruit, these relationships are the foundation of statistical practice.

In addition to collaboration, statistical consulting provides an essential service across the university, helping graduate students and professors get research out the door quickly and with maximal power. 

Ultimately, eliminating the statistics department would cripple the university's research and teaching infrastructure and threaten its ability to maintain its membership in the Big Ten or rejoin the AAU. Instead, the department recommends a bold plan that is aligned with Dr. Gold's Odyssey to the Extraordinary objectives:  create a centralized structure that will facilitate collaboration, consulting, and teaching across many departments on both East and City campuses, as well as eventually UNMC. Strategically invest in a department that can supercharge the research metrics across the university.


Important links:

- [Detailed statistical analysis of variables used in the budget proposal analysis](app-metrics-analysis.qmd)

- [Analysis of problems with the data used in the budget proposal analysis](app-analysis-issues.qmd)

If you are viewing a PDF copy of this report or viewing a printout of the report, all of the supporting documentation (APR reports, letters, etc) can be found at https://srvanderplas.github.io/2025-stat-apc-report/ (HTML version with links) or at https://github.com/srvanderplas/2025-stat-apc-report/. 
Statisticians care very much about scientific reproducibility, and so we have done our best to provide the sources, data, and code to support this analysis. 
