
# Introduction

```{r}
#| include: false
library(rvest)
library(xml2)
library(dplyr)
library(purrr)
library(stringr)
library(tidyr)
library(tibble)
library(readr)
library(ggplot2)
library(knitr)
options(knitr.kable.NA = '')
library(kableExtra)
library(readxl)
theme_set(theme_bw())
library(patchwork)
library(forcats)
```

On September 11, 2025, the Statistics Department was informed that it had been proposed for elimination under the Chancellor's [budget reduction proposal](https://budgetprocess.unl.edu/proposed-budget-reductions/). 

> When the process is invoked, the Chancellor will provide a framework document that describes the issue(s), including a rationale for the proposed reduction(s), the scope of the reduction/reallocation, and a desired timeline for completing the review process and implementing the changes. The document will be made available to the Chancellor's Executive Leadership Team and the following shared governance partners: the Academic Planning Committee (APC), the deans, the Executive Committee of the UNL Faculty Senate, appropriate representatives of the Staff Senate, and appropriate representatives of the Association of Students of the University of Nebraska (ASUN).

The rationale for the proposed reductions provided in the budget reduction plan is as follows:

> The proposed plan would eliminate a standalone Department of Statistics offering BS, MS, and PhD degrees and moves the university toward a distributed model that leverages expertise embedded across IANR, UNL and the NU system. The plan proposes to strategically deploy a portion of the state-appropriated funds to continue to offer selected undergraduate and graduate courses and provide coordinated statistical consulting.  Budget reductions would be achieved through the elimination of positions (12 FTE).

That is, the only rationale offered is that the Chancellor proposes to move towards a distributed model that "leverages expertise embedded across IANR, UNL, and the NU system". 
The distributed model has been tried before at UNL, within both IANR and the College of Arts and Sciences, and the end result was the creation of a stand-alone statistics department (though only after nearly every other possible model was proposed and attempted). 



## Outline

@sec-dept-analysis discusses statistics within the University of Nebraska System, with a focus on the University of Nebraska -- Lincoln. 
@sec-history-dept provides a brief history of the Statistics Department at UNL and its associated graduate and undergraduate programs, along with the rationale used to motivate past changes to the department structure. 
This historical data is used to assess the plan to move toward a distributed model of embedding statisticians within other departments on campus.  
@sec-role-dept examines the role of the Statistics Department on campus, outlining its integration with the teaching, research, and extension missions within the university. @sec-nu-stats examines other clusters of statistical expertise within the University of Nebraska system, including related departments at UNL, Biostatistics at UNMC and Mathematics departments at UNO and UNK. 
These additional clusters of statistical knowledge are critically assessed to determine whether any other unit or the combination of all other units have the capacity to replace the functions of the Statistics department without hiring additional FTEs and reducing the savings from the proposed elimination of the department. 


@sec-metrics examines the metrics used to evaluate the performance of the department and makes the case that the reliance on these metrics demonstrates the importance of accounting for random variation and contextual information when interpreting data -- that is, that the Statistics department is a necessary component of decision making across the university.

@sec-peer-analysis discusses the presence of statistics departments within the AAU, Big Ten, R1, and land-grant classifications, examining the viability of a distributed model based on data from peer institutions.

@sec-program-analysis examines the programs housed within the Statistics department as well as important contributions made by the department to other programs, and evaluates the impact of closing the department on the university and the state. 

@sec-future provides an alternative plan to situate the Statistics department within the university in a way that will best position UNL to rejoin the AAU and serve the state of Nebraska by strengthening research, teaching, and extension missions of the university. 

Throughout this report, additional resources and references are directly linked (rather than providing a bibliography and formal citations) to ensure that APC has the necessary information immediately available. 
