---
# title: "Regents Statement 2025-10-03"
format: pdf
---

Hi, my name is Susan Vanderplas. I'm an associate professor in the Statistics Department, and have been at UNL since 2020. I also serve on the UNL Faculty Senate Executive Committee. 

I have had concerns with the speed of the budget process occurring at UNL since the timeline was announced in Faculty Senate Exec meetings in early August. 
Of course, when the Statistics department was proposed for elimination, I began trying to understand why the data-driven method used resulted in my department being poorly ranked.

What I found in the data analysis process would have earned any of my students an F and an invitation to visit office hours for some pointed re-teaching of key statistics principles. 
My colleagues have highlighted some of these problems - inaccurate data, faulty statistical methodology, and above all, a failure to consider the real-world context of the data. 
Ultimately, it is not reasonable to compare the Physics department to the English department on the amount of grant funding received, just as it would be unreasonable to compare Physics to English on the number of books written. 
These variables are useful for comparing similar departments, but they are not helpful when the departments have different funding opportunities and different expectations for the form in which research is presented. 

Chancellor Bennett will insist that he is following the process outlined by APC procedures. 
While I will agree with him that APC is ensuring that the process is followed now that the ball is in their court, the fact remains that the metrics used to identify departments are neither transparent nor fair, which is a necessary component of the process. 
Departments have not been provided with sufficient information to allow them to correct the faulty data, and the administration has prevented faculty from acquiring their own data from the registrar and graduate college.  

In this week's hearings, Josh Davis, the Vice Chancellor, claims to have used industry best practices to evaluate departments. 
This is categorically false. 

I urge the Regents, President Gold, and Chancellor Bennett to stop the current process and consult with certified professional statisticians or Ph.D.s in Statistics before coming up with a new plan to cut UNL's budget. 
Using the faulty data and sloppy methods from the initial attempt will only cost UNL money in wrongful termination suits, hurt UNL's national and international reputation, limit the options for students to get in-demand degrees at state institutions, and further accelerate the brain drain as students leave the state for educational opportunities elsewhere and return only to visit family on holidays.
My department provides programs unique in this state at the undergraduate and graduate levels, training students for in-demand jobs in digital agriculture, data science, finance and actuarial science, and artificial intelligence. 
As a state, we cannot afford to eliminate Statistics programs because the state university misused statistics.  
