<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2025-10-02">

<title>Statistics: An Essential Department for a Modern R1 University</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="2025-Stat-APC-report_files/libs/clipboard/clipboard.min.js"></script>
<script src="2025-Stat-APC-report_files/libs/quarto-html/quarto.js"></script>
<script src="2025-Stat-APC-report_files/libs/quarto-html/popper.min.js"></script>
<script src="2025-Stat-APC-report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="2025-Stat-APC-report_files/libs/quarto-html/anchor.min.js"></script>
<link href="2025-Stat-APC-report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="2025-Stat-APC-report_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="2025-Stat-APC-report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="2025-Stat-APC-report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="2025-Stat-APC-report_files/libs/bootstrap/bootstrap-032e220be364433605a2bb7b2b296306.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="2025-Stat-APC-report_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="2025-Stat-APC-report_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#sec-dept-analysis" id="toc-sec-dept-analysis" class="nav-link" data-scroll-target="#sec-dept-analysis"><span class="header-section-number">2</span> The UNL Statistics Department</a>
  <ul class="collapse">
  <li><a href="#sec-history-dept" id="toc-sec-history-dept" class="nav-link" data-scroll-target="#sec-history-dept"><span class="header-section-number">2.1</span> History of the Department</a></li>
  <li><a href="#sec-role-dept" id="toc-sec-role-dept" class="nav-link" data-scroll-target="#sec-role-dept"><span class="header-section-number">2.2</span> The Role of a Statistics Department</a></li>
  <li><a href="#sec-nu-stats" id="toc-sec-nu-stats" class="nav-link" data-scroll-target="#sec-nu-stats"><span class="header-section-number">2.3</span> NU System Statistics Expertise</a></li>
  </ul></li>
  <li><a href="#sec-metrics" id="toc-sec-metrics" class="nav-link" data-scroll-target="#sec-metrics"><span class="header-section-number">3</span> Metrics</a>
  <ul class="collapse">
  <li><a href="#research" id="toc-research" class="nav-link" data-scroll-target="#research"><span class="header-section-number">3.1</span> Research</a></li>
  <li><a href="#teaching" id="toc-teaching" class="nav-link" data-scroll-target="#teaching"><span class="header-section-number">3.2</span> Teaching</a></li>
  <li><a href="#consulting" id="toc-consulting" class="nav-link" data-scroll-target="#consulting"><span class="header-section-number">3.3</span> Consulting</a></li>
  <li><a href="#collaboration" id="toc-collaboration" class="nav-link" data-scroll-target="#collaboration"><span class="header-section-number">3.4</span> Collaboration</a></li>
  </ul></li>
  <li><a href="#sec-peer-analysis" id="toc-sec-peer-analysis" class="nav-link" data-scroll-target="#sec-peer-analysis"><span class="header-section-number">4</span> Peer Analysis</a>
  <ul class="collapse">
  <li><a href="#r1-universities" id="toc-r1-universities" class="nav-link" data-scroll-target="#r1-universities"><span class="header-section-number">4.1</span> R1 Universities</a></li>
  <li><a href="#land-grant-universities" id="toc-land-grant-universities" class="nav-link" data-scroll-target="#land-grant-universities"><span class="header-section-number">4.2</span> Land Grant Universities</a></li>
  <li><a href="#aau-universities" id="toc-aau-universities" class="nav-link" data-scroll-target="#aau-universities"><span class="header-section-number">4.3</span> AAU Universities</a></li>
  </ul></li>
  <li><a href="#sec-program-analysis" id="toc-sec-program-analysis" class="nav-link" data-scroll-target="#sec-program-analysis"><span class="header-section-number">5</span> Program Analysis</a>
  <ul class="collapse">
  <li><a href="#apc-criteria" id="toc-apc-criteria" class="nav-link" data-scroll-target="#apc-criteria"><span class="header-section-number">5.1</span> APC Criteria</a>
  <ul class="collapse">
  <li><a href="#addressing-the-criteria-in-support-of-reduction" id="toc-addressing-the-criteria-in-support-of-reduction" class="nav-link" data-scroll-target="#addressing-the-criteria-in-support-of-reduction"><span class="header-section-number">5.1.1</span> Addressing the Criteria in Support of Reduction</a></li>
  <li><a href="#addressing-the-criteria-indicating-that-elimination-is-inadvisable" id="toc-addressing-the-criteria-indicating-that-elimination-is-inadvisable" class="nav-link" data-scroll-target="#addressing-the-criteria-indicating-that-elimination-is-inadvisable"><span class="header-section-number">5.1.2</span> Addressing the Criteria Indicating that Elimination is Inadvisable</a></li>
  <li><a href="#addressing-criteria-indicating-that-reduction-is-inadvisable" id="toc-addressing-criteria-indicating-that-reduction-is-inadvisable" class="nav-link" data-scroll-target="#addressing-criteria-indicating-that-reduction-is-inadvisable"><span class="header-section-number">5.1.3</span> Addressing Criteria Indicating that Reduction is Inadvisable</a></li>
  </ul></li>
  <li><a href="#effects-of-proposed-cuts-on-outside-programs" id="toc-effects-of-proposed-cuts-on-outside-programs" class="nav-link" data-scroll-target="#effects-of-proposed-cuts-on-outside-programs"><span class="header-section-number">5.2</span> Effects of Proposed Cuts on Outside Programs</a>
  <ul class="collapse">
  <li><a href="#mathematics" id="toc-mathematics" class="nav-link" data-scroll-target="#mathematics"><span class="header-section-number">5.2.1</span> Mathematics</a></li>
  <li><a href="#university-wide-impact" id="toc-university-wide-impact" class="nav-link" data-scroll-target="#university-wide-impact"><span class="header-section-number">5.2.2</span> University-Wide Impact</a></li>
  </ul></li>
  <li><a href="#undergraduate-program" id="toc-undergraduate-program" class="nav-link" data-scroll-target="#undergraduate-program"><span class="header-section-number">5.3</span> Undergraduate Program</a></li>
  <li><a href="#ms-program" id="toc-ms-program" class="nav-link" data-scroll-target="#ms-program"><span class="header-section-number">5.4</span> MS Program</a></li>
  <li><a href="#ph.d.-program" id="toc-ph.d.-program" class="nav-link" data-scroll-target="#ph.d.-program"><span class="header-section-number">5.5</span> Ph.D.&nbsp;Program</a></li>
  </ul></li>
  <li><a href="#concentrated-vs.-distributed-statistics-model" id="toc-concentrated-vs.-distributed-statistics-model" class="nav-link" data-scroll-target="#concentrated-vs.-distributed-statistics-model"><span class="header-section-number">6</span> Concentrated vs.&nbsp;Distributed Statistics Model</a></li>
  <li><a href="#sec-future" id="toc-sec-future" class="nav-link" data-scroll-target="#sec-future"><span class="header-section-number">7</span> Planning for the Future</a></li>
  <li><a href="#appendix" id="toc-appendix" class="nav-link" data-scroll-target="#appendix"><span class="header-section-number">8</span> Appendix</a>
  <ul class="collapse">
  <li><a href="#statistics-faculty-in-the-un-system" id="toc-statistics-faculty-in-the-un-system" class="nav-link" data-scroll-target="#statistics-faculty-in-the-un-system"><span class="header-section-number">8.1</span> Statistics Faculty in the UN System</a></li>
  <li><a href="#sec-metric-problems" id="toc-sec-metric-problems" class="nav-link" data-scroll-target="#sec-metric-problems"><span class="header-section-number">8.2</span> Problems with the Metrics</a>
  <ul class="collapse">
  <li><a href="#provision-of-data-and-interactive-consultation-process" id="toc-provision-of-data-and-interactive-consultation-process" class="nav-link" data-scroll-target="#provision-of-data-and-interactive-consultation-process"><span class="header-section-number">8.2.1</span> Provision of Data and Interactive Consultation Process</a></li>
  <li><a href="#data-quality" id="toc-data-quality" class="nav-link" data-scroll-target="#data-quality"><span class="header-section-number">8.2.2</span> Data Quality</a></li>
  <li><a href="#sec-metric-sri-problems" id="toc-sec-metric-sri-problems" class="nav-link" data-scroll-target="#sec-metric-sri-problems"><span class="header-section-number">8.2.3</span> Use of Scholarly Research Index</a></li>
  <li><a href="#problems-with-overall-z-scores" id="toc-problems-with-overall-z-scores" class="nav-link" data-scroll-target="#problems-with-overall-z-scores"><span class="header-section-number">8.2.4</span> Problems with Overall Z-scores</a></li>
  <li><a href="#custom-unl-research-metrics" id="toc-custom-unl-research-metrics" class="nav-link" data-scroll-target="#custom-unl-research-metrics"><span class="header-section-number">8.2.5</span> Custom UNL Research Metrics</a></li>
  </ul></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="2025-Stat-APC-report.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Statistics: An Essential Department for a Modern R1 University</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 2, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Summary
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>The Chancellor’s proposal to move to a distributed model with statistics expertise located within relevant departments around the university will require hiring additional faculty in various departments, significantly reducing the 12 FTE savings from the elimination of the Statistics department.</li>
<li>There is not sufficient capacity on any other UN system campus to sufficiently meet the research, teaching, and extension missions of the university with regard to statistics demand at UNL.</li>
<li>The distributed model promotes duplication of classes and expertise across departments, at a time when we should be increasing efficiency.</li>
<li>Statistics at UNL has tried many different models. The reasons for creating a separate statistics department are still relevant today: visibility, efficiency, and the importance of offering statistics programs.</li>
</ul>
<p>The more efficient path forward is to keep the Statistics department but to locate it in a place where it can best serve the entire university, rather than solely IANR. The 1968 plan to locate Statistics and Computer Science within a School of Computing might be the right model. Joint and courtesy appointments from outside of Statistics could be used to build stronger ties with other Statistics-adjacent departments, including those located on City campus. IANR should continue to contribute support to the SC3L (consulting group) to ensure that collaboration and consulting demand from IANR continues to be met.</p>
</div>
</div>
<p>On September 11, 2025, the Statistics Department was informed that it had been proposed for elimination under the Chancellor’s <a href="https://budgetprocess.unl.edu/proposed-budget-reductions/">budget reduction proposal</a>.</p>
<blockquote class="blockquote">
<p>When the process is invoked, the Chancellor will provide a framework document that describes the issue(s), including a rationale for the proposed reduction(s), the scope of the reduction/reallocation, and a desired timeline for completing the review process and implementing the changes. The document will be made available to the Chancellor’s Executive Leadership Team and the following shared governance partners: the Academic Planning Committee (APC), the deans, the Executive Committee of the UNL Faculty Senate, appropriate representatives of the Staff Senate, and appropriate representatives of the Association of Students of the University of Nebraska (ASUN).</p>
</blockquote>
<p>The rationale for the proposed reductions provided in the budget reduction plan is as follows:</p>
<blockquote class="blockquote">
<p>The proposed plan would eliminate a standalone Department of Statistics offering BS, MS, and PhD degrees and moves the university toward a distributed model that leverages expertise embedded across IANR, UNL and the NU system. The plan proposes to strategically deploy a portion of the state-appropriated funds to continue to offer selected undergraduate and graduate courses and provide coordinated statistical consulting. Budget reductions would be achieved through the elimination of positions (12 FTE).</p>
</blockquote>
<p>That is, the only rationale offered is that the Chancellor proposes to move towards a distributed model that “leverages expertise embedded across IANR, UNL, and the NU system”. The distributed model has been tried before at UNL, within both IANR and the College of Arts and Sciences, and the end result was the creation of a stand-alone statistics department (though only after nearly every other possible model was proposed and attempted).</p>
<p><a href="#sec-dept-analysis" class="quarto-xref">Section&nbsp;2</a> discusses statistics within the University of Nebraska System, with a focus on the University of Nebraska – Lincoln. <a href="#sec-history-dept" class="quarto-xref">Section&nbsp;2.1</a> provides a brief history of the Statistics Department at UNL and its associated graduate and undergraduate programs, along with the rationale used to motivate past changes to the department structure. This historical data is used to assess the plan to move toward a distributed model of embedding statisticians within other departments on campus.<br>
<a href="#sec-role-dept" class="quarto-xref">Section&nbsp;2.2</a> examines the role of the Statistics Department on campus, outlining its interactions with the teaching, research, and extension missions within the university. <a href="#sec-nu-stats" class="quarto-xref">Section&nbsp;2.3</a> examines other clusters of statistical expertise within the University of Nebraska system, including related departments at UNL, Biostatistics at UNMC and Mathematics departments at UNO and UNK. These additional clusters of statistical knowledge are critically assessed to determine whether any other unit or the combination of all other units have the capacity to replace the functions of the Statistics department without hiring additional FTEs and reducing the savings from the proposed elimination of the department.</p>
<p>Section <a href="#sec-metrics" class="quarto-xref">Section&nbsp;3</a> examines the metrics used to evaluate the performance of the department and makes the case that the reliance on these metrics demonstrates the importance of accounting for random variation and contextual information when interpreting data – that is, that the Statistics department is a necessary component of decision making across the university.</p>
<p>Section <a href="#sec-peer-analysis" class="quarto-xref">Section&nbsp;4</a> discusses the presence of statistics departments within the AAU, Big Ten, R1, and land-grant classifications, examining the viability of a distributed model based on data from peer institutions.</p>
<p>Section <a href="#sec-program-analysis" class="quarto-xref">Section&nbsp;5</a> examines the programs housed within the Statistics department as well as important contributions made by the department to other programs, and evaluates the impact of closing the department on the university and the state.</p>
<p>Section <strong>?@sec-planning</strong> provides an alternative plan to situate the Statistics department within the university in a way that will best position UNL to rejoin the AAU and serve the state of Nebraska by strengthening research, teaching, and extension missions of the university.</p>
<p>Throughout this report, additional resources and references are directly linked (rather than providing a bibliography and formal citations) to ensure that APC has the necessary information immediately available.</p>
</section>
<section id="sec-dept-analysis" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> The UNL Statistics Department</h1>
<section id="sec-history-dept" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="sec-history-dept"><span class="header-section-number">2.1</span> History of the Department</h2>
<!-- https://digitalcommons.unl.edu/cgi/viewcontent.cgi?article=1000&context=statisticsdeptdocs -->
<ul>
<li>1957 - Statistics Laboratory founded at UNL under Dr.&nbsp;Charles Gardner, funded by the Agricultural Experiment Station to provide design, analysis, and data processing services to researchers.</li>
</ul>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-2-contents" aria-controls="callout-2" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Consulting Headcount Comparison
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-2" class="callout-2-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<p>Under the current proposal, only one FTE would be responsible for statistical consulting, across the UNL campus. This reduction would take UNL back to 1957 in the amount of statistical consulting assistance available across campus. Without graduate students at the SC3L, who currently provide over 100 hours per week of dedicated consulting time, the preservation of a single FTE for statistical consulting represents a dramatic reduction in capacity during a period of greatly increased demand across IANR as well as the wider university.</p>
</div>
</div>
</div>
<ul>
<li><p>1968 - <a href="https://math.unl.edu/statistics-history-unl/">UNL attempts to create a School of Computational Sciences with two departments: Computer Science and Statistics, but it fails. Instead, the Mathematics Department is renamed the Department of Mathematics and Statistics to account for the growing relevance of Statistics across the university.</a>.</p></li>
<li><p>1968 - Dr.&nbsp;Wilfred Schutz becomes head of the UNL Statistics Laboratory. At this point, the Statistics laboratory consists of Dr.&nbsp;Schutz, one additional faculty member, a data processing programmer, a computer operator, data entry personnel, and a secretary. Faculty members hold academic appointments in Agronomy.</p></li>
<li><p>1972 - Statistics courses are transferred to the Statistics laboratory from Agronomy. Several new faculty are hired due to growing demand for consulting services and additional courses.</p></li>
<li><p>Early 1970s - A Ph.D.&nbsp;program in statistics is discussed involving faculty from Math, Biometrics, Educational Psychology, and other departments (<a href="documentation/1993-Biometry-APR-SelfStudy.pdf">1993 Biometry Department Self-Study</a>, page 30).</p></li>
<li><p>1978 - The Statistics Laboratory is renamed the Biometrics and Information Systems Center.</p></li>
<li><p>1985 - A committee is formed to study the feasibility of combining the Statistics portion of the Mathematics Department and the Biometrics Department into a Department of Statistics (<a href="documentation/1993-Biometry-APR-SelfStudy.pdf">1993 Biometry Department Self-Study</a>, page 31).</p></li>
<li><p>1987 - The Biometrics and Information Systems Center is divided into the Biometrics Center and IANR Computing, as recommended in 1985 self-study (<a href="documentation/1993-Biometry-APR-SelfStudy.pdf">1993 Biometry Department Self-Study</a>, page 31).</p></li>
<li><p>1988 - The Division of Statistics is established as a subgroup within the Department of Mathematics and Statistics (<a href="documentation/2001-MathStats-Apr-SelfStudy.pdf">2001 Mathematics &amp; Statistics Department Self-Study</a>)</p></li>
<li><p>1989 - The Department of Biometry is established from the Biometrics Center. Faculty from the Biometrics Center hold academic appointments in the Biometry department. (<a href="documentation/1993-Biometry-APR-SelfStudy.pdf">1993 Biometry Self-Study</a>, page 9)</p></li>
<li><p>1990 - The Board of Regents approves an MS program in Biometry (<a href="documentation/1993-Biometry-APR-SelfStudy.pdf">1993 Biometry Self-Study</a>, page 20).</p></li>
<li><p>1993 - The Mathematics APR Report recommends creation of a separate department of statistics (<a href="documentation/2001-MathStats-Apr-SelfStudy.pdf">2001 Mathematics &amp; Statistics APR Self-Study</a>, pg 147)</p></li>
</ul>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-3-contents" aria-controls="callout-3" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Motivation for Stand-alone Statistics Department
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-3" class="callout-3-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Retention: faculty left after only a few years because of lack of recognition of statistics as a discipline by the university.</li>
<li>A separate department will strengthen the research and teaching in statistics</li>
<li>A separate department will enrich the research of statisticians who are currently in the departments of Mathematics and Biometry</li>
</ul>
</div>
</div>
</div>
<ul>
<li><p>2000 - A largely-autonomous Division of Statistics is created within the Department of Mathematics and Statistics with a focus area in survey sampling to support the Gallup Research Center. Some faculty transfer tenure homes into the department from Biometry and Sociology (<a href="documentation/2001-MathStats-Apr-SelfStudy.pdf">2001 Mathematics &amp; Statistics APR Self-Study</a>, pg 14).</p></li>
<li><p>2003 - The Statistics Department is founded from the Department of Biometry (IANR) and the Statistics faculty from the Department of Mathematics and Statistics (<a href="documentation/2005-STAT-APR-Report.pdf">2005 Statistics APR</a>, pg 3)</p></li>
<li><p>2003 - A Statistics PhD program is created within the newly-formed Statistics Department.</p></li>
</ul>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-4-contents" aria-controls="callout-4" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Reasons motivating the PhD Program’s initiation:
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-4" class="callout-4-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Recruit better graduate students</li>
<li>Enhance ability to do research using PhD graduate students</li>
<li>Enhance consulting via both research and satisfying increasing consulting demand using well-trained and supervised graduate students.</li>
<li>PhD students can lead graduate course labs for MS students, reducing the instructional burden on faculty</li>
<li>PhD students enhance professional development for faculty by facilitating research and consulting collaborations</li>
</ul>
</div>
</div>
</div>
<ul>
<li><p>2005 - <a href="documentation/2005-STAT-APR-Report.pdf">APR Team recommends</a> better integration and outreach to city campus and assessment of service teaching needs in other departments.</p></li>
<li><p>2013 - <a href="documentation/2013-STAT-APR-Report.pdf">APR Team recommends</a> reducing graduate program enrollment and creation of an undergraduate and 3+2 BS+MS program.</p></li>
</ul>
<div class="callout callout-style-simple callout-none no-icon callout-titled">
<div class="callout-header d-flex align-content-center" data-bs-toggle="collapse" data-bs-target=".callout-5-contents" aria-controls="callout-5" aria-expanded="false" aria-label="Toggle callout">
<div class="callout-icon-container">
<i class="callout-icon no-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Specific Recommendations
</div>
<div class="callout-btn-toggle d-inline-block border-0 py-1 ps-1 pe-0 float-end"><i class="callout-toggle"></i></div>
</div>
<div id="callout-5" class="callout-5-contents callout-collapse collapse">
<div class="callout-body-container callout-body">
<ul>
<li>Graduate program enrollment reductions (no more than 5/1 student/faculty ratio)</li>
<li>More collaborative and cross-listed courses with Departments of Mathematics and Computer Science.</li>
<li>Creation of an undergraduate program and a 2+3 BS+MS statistics program.</li>
<li>Use of Online/blended delivery and flipped classroom approaches to improve learning and reduce instructional costs.</li>
<li>Hiring a Professor of Practice position to cover program administration, advising, and instructional needs.</li>
</ul>
</div>
</div>
</div>
<ul>
<li><p>July 1, 2018 - The Statistics department fully separates from the College of Arts and Sciences and is 100% supported by the Institute of Agriculture and Natural Resources.</p></li>
<li><p>Fall 2019 - The Statistics department begins to design an undergraduate major in Statistics and Data Analytics at the request of CASNR Dean Tiffany Heng-Moss and in response to the recommendations from the 2013 APR.</p></li>
<li><p>2021 - <a href="documentation/2021-STAT-APR-Report.pdf">APR team recommends</a> increasing the number of tenure-track faculty to 20, hiring several teaching faculty to increase instructional efficiency and capacity, and adding departmental administrators to ensure program success.</p></li>
<li><p>Fall 2021 - <a href="https://ccpe.nebraska.gov/sites/default/files/UNL%20Creation%20BS%20in%20Stats%20%20Data%20Analytics_08162021.pdf">Statistics and Data Analytics major approved by the Board of Regents</a></p></li>
<li><p>June 2022 - <a href="https://ccpe.nebraska.gov/sites/default/files/AP_UNL%20Data%20Sciences%20BA%20BS%20Proposal.pdf">Data Science Major approved by Board of Regents with programs in CASNR, CAS, and Engineering</a></p></li>
<li><p>Fall 2022 - First Statistics and Data Analytics freshman cohort begins classes</p></li>
<li><p>Spring 2026 - First Statistics and Data Analytics cohort expected to graduate</p></li>
</ul>
</section>
<section id="sec-role-dept" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="sec-role-dept"><span class="header-section-number">2.2</span> The Role of a Statistics Department</h2>
<p>A statistics department provides a number of services within the campus ecosystem apart from its own programs (which often exist to provide these services efficiently, as demonstrated in the 1993 Biometry Self-Study report). Statistics is an essential component of undergraduate quantitative literacy; over 20% of UNL undergraduates take Stat 218 to fulfill their Ace 3 requirements. In addition, Statistics supports additional quantitative coursework for other departments: Stat 318 and 380, as well as Stat 462 and Stat 463, which are an essential component of the Actuarial Sciences program. At the graduate level, the department provides additional critical training in statistical methods (Stat 801, 802) and in computing and the use of software packages for data analysis and visualization (Stat 850). These courses facilitate research across the university, in a way that is difficult to explicitly measure: by training graduate researchers in other disciplines, we facilitate high quality research in those disciplines. <!-- However, we could do this at a larger scale by growing enrollment in Stat 850: it already consists of approximately 50% statistics students and 50% outside students, and it is helpful for students in agronomy, biological sciences, engineering, psychology, and sociology.  --> In addition to introductory courses, however, graduate students in other departments often need additional course work in experimental design and specific areas of statistical methodology, such as Bayesian statistics or statistical genetics. Without a centralized statistics department and the expertise of statistics faculty, each department must solve the problem of providing this coursework separately.</p>
<p>It is more efficient to offer courses in linear mixed models under a statistics prefix than to teach separate courses for Agronomy, Animal Science, Engineering, Psychology, and Sociology across five departments with five instructors. While it may be necessary to offer two courses (one which accommodates the lack of linear algebra or calculus prerequisite work), this is still a substantial savings over offering five separate courses. <!-- The examples which are used in the courses can be varied fairly easily to accommodate multiple disciplines simultaneously.  --> One failing of a distributed model where statisticians are embedded within each department is that it results in duplication of effort across departments, and if departments cannot hire someone with statistical expertise AND domain expertise, then it becomes difficult for that department to meet the needs of both students and faculty.</p>
<blockquote class="blockquote">
<p>The training my own students receive from Statistics – from coursework, from collaborators, and from Statistics faculty on their thesis and dissertation committees – is essential to our ability to win and execute upon large federal research awards. Our institute’s capacity to train students whose expertise bridges quantitative techniques and in the field understanding of crop systems is why I receive e-mails from Corteva, Syngenta, and Bayer asking when my next lab’s next PhDs will be graduating.<br>
– <a href="letters/James%20Schnable.pdf">James Schnable, Letter to APC</a></p>
</blockquote>
<p>On the research side, a statistics department should have collaborations with many scientific departments across campus, assisting with the development of new methodology as well as consulting on the appropriate established methodology to use. This dual collaboration and consulting function of a statistics department is critical for ensuring that the scientific results published by researchers are valid and for accelerating progress within other fields. A major research university without a statistics department is as difficult to imagine as a university known for its engineering programs that doesn’t have a mathematics department to assist with teaching calculus and differential equations or a physics department to teach statics and mechanics.</p>
<blockquote class="blockquote">
<p>Statistics is the midwife to all other departments. UNL has a strong agricultural mission and a proud track record in agronomy. So does statistics. My field was started by Sir Ronald Fisher, who worked to analyze agricultural data at the Rothamsted Experimental Station before moving on to University College London and eventually the University of Cambridge. The work that Fisher did laid the mathematical foundation for continual improvement of yields. His co-founding of statistical genetics has been the basis for nearly all improvement in agriculture over the last 100 years (aside from the Haber-Bosch process, which gave us plentiful fertilizer). But statistics doesn’t just feed agronomy. It provided the necessary confirmation of the Higgs boson in physics. It undergirds the risk analyses that drive medical therapies, business decisions, insurance, and the amelioration of climate change. English professors use latent Dirichlet allocation to identify themes in literature. Philosophy faculty study the implications of Bayes’ Rule for rationality and coherence. Chemists, entomologists and historians all employ statistics on a regular basis, either on their own or through collaboration with research statisticians. – <a href="letters/David%20Banks.pdf">David Banks, Duke University Statistics Department, ASA Fellow, IMS Fellow, AAAS Fellow</a></p>
</blockquote>
<p>While biostatistics departments are generally composed of individuals who assist medical schools with clinical trials, survival analyses, and causal inference, statistics departments typically have experts in experimental design relevant to important programs across campus: at UNL, that would include agricultural field experiments, population genetics for plants and animals, engineering factorial experiments and quality control, survey sampling to support social science, statistical computing and simulation, Bayesian methodology, and operations research. A centralized statistics department that is set up to collaborate with quantitative disciplines on campus is more efficient than a distributed set of statisticians scattered across many different departments, because it is easier to find the statistician with the right expertise when they are collocated. Under a distributed model, someone might have to search directory information within 12-15 departments<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, and it is likely that they may not find the right person in any case.</p>
<p>Decentralized statisticians also exist in a service role, publishing research papers that may develop their disciplines but which often do not make contributions to the discipline of statistics. As an example, the charts and graphs used to show the metrics of each UNL department were created with <code>ggplot2</code> and <code>plotly</code>, both tools developed at Iowa State under the supervision of Dr.&nbsp;Heike Hofmann, who is now in the UNL Statistics department. It is hard to imagine such tools being developed under a distributed model: they are the product of statistics research, and they are now used across quantitative disciplines. Similarly, tools like <code>rmarkdown</code>, <code>knitr</code>, and <code>quarto</code> (which were used to assemble the charts into a document that was shared across the university) were research products of the Iowa State Statistics department in the same era, and they are now gold-standard tools for reproducible research across the sciences, in addition to making reporting easier within e.g.&nbsp;business and administrative units. Within UNL, these tools are used in agronomy, agricultural economics, biosystems engineering, the School of Natural Resources, journalism, and psychology<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Collaboration between statisticians produces research that makes science better and more efficient for everyone, but this is difficult or impossible to prioritize under a distributed or service model where embedded statisticians are evaluated based on discipline-specific contributions.</p>
<blockquote class="blockquote">
<p>A centralized Statistics Department provides essential consulting, collaboration, and training for research across all colleges. Dispersing faculty into a “distributed model” weakens this role and undermines interdisciplinary strength. – <a href="letters/LetterVidakovic_TAMU.pdf">Brani Vidakovic, H.O. Hartley Chair and Department Head, Department of Statistics, Texas A&amp;M University</a></p>
</blockquote>
<p>However, we can also evaluate the purported efficiency of a distributed model by examining the resources currently available across the NU system in Statistics. If there is excess capacity of faculty with statistical expertise outside the Statistics department, then perhaps the inefficiencies of workin in the distributed model would be countered by the savings from eliminating the department. However, this is not the case, as demonstrated in the next section.</p>
</section>
<section id="sec-nu-stats" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="sec-nu-stats"><span class="header-section-number">2.3</span> NU System Statistics Expertise</h2>
<p>There are several units within UNL that maintain some statistical expertise in-house, in addition to programs in Biostatistics at UNMC and Statistics and Data Science at UNO.</p>
<p>At UNL, in addition to the Statistics department, some departments have overlap with Statistics in coursework and/or research:</p>
<ul>
<li>the Quantitative, Qualitative, and Psychometrics (QQPM) department, which focuses on educational statistics and measurement. None of the faculty have Ph.D.s in Statistics; they are distributed between QQPM, Educational Psychology, and Psychology programs. However, they clearly have expertise in some aspects of statistics and measurement.</li>
<li>the Sociology department has two faculty (Kristen Olson, Jolene Smyth) who specialize in survey research methods. Their Ph.D.s are in Survey Methodology and Sociology, but they do survey research and have expertise that isn’t currently available within the Statistics department.</li>
<li>the Economics department. Econometrics has some overlap with Statistics. There are three faculty (Yifan Gong, Christopher Mann, Federico Zincenko) who mention Econometrics as a research area within this department.</li>
<li>the Agricultural Economics department. There is some overlap with statistics in discipline, but it is difficult to identify any specific faculty who might have the expertise and interest to do Statistics work. None of the faculty appear to have Ph.D.s in Statistics.</li>
<li>the Actuarial Science program. Three tenured or tenure-track faculty (Colin Ramsay, Mostafa Mashayekhi, Graham Liu) affiliated with Actuarial Science have Ph.D.s in Statistics or Actuarial Science.</li>
<li>the Supply Chain Management &amp; Analytics program. None of the faculty have Ph.D.s in Statistics, but seven tenured or tenure-track faculty have degrees in business analytics, operations management, or supply chain management. These degrees are not comparable to statistics in terms of theoretical training that would support development of new statistical methodology but might suffice to cover some of the coursework currently offered in the Statistics department. <!-- Yunxia (Peter) Zhu, Yingchao Lan, Erkut Sonmez, Scott Swenseth, Esma Gel, Wesley Boyce, Shengchao Zhuang --></li>
</ul>
<p><a href="#sec-metrics" class="quarto-xref">Section&nbsp;3</a> discusses the ways that the Statistics department interacts with other portions of campus. Faculty within the College of Business (Econometrics, Actuarial Science, Supply Chain Management &amp; Analytics) represent perhaps the closest group outside of the Statistics department within UNL, but none have degrees in Statistics, and while some of the courses taught in the College of Business may touch on topics such as forecasting, simulation, and modeling, the faculty within the college have specialized to apply these techniques to business and finance, and it seems unlikely that they have extra capacity.</p>
<p>Ultimately, however, there are clearly insufficient FTEs available at UNL in statistics-adjacent fields that could reasonably take over the teaching, collaboration, consulting, and research functions which are fulfilled by the Department of Statistics, particularly when the existing demands on those FTEs are considered.</p>
<p>The Biostatistics department at UNMC has sixteen faculty members, and of these, fourteen have Ph.D.s in Statistics rather than Biostatistics; the remaining individuals received their Ph.D.s from UNMC in Biostatistics and Biomedical Informatics. Moreover, five of the sixteen tenured or tenure-track faculty received their Ph.D.&nbsp;from the Statistics department at UNL (see <a href="#tbl-unmc-biostats" class="quarto-xref">Table&nbsp;4</a> for a full list), an indication that the Statistics department at UNL actually serves to enrich Biostats at UNMC, rather than being a redundancy within the UN system. While Biostatisticians at UNMC do valuable work that contributes to research methodology in statistics, many of the papers listed in different research areas were published before the faculty member joined UNMC - that is, the broader methodological papers were written as part of their doctoral work in Statistics.</p>
<p>Biostatisticians apply statistical methods to medicine, and must cultivate a specific set of skills for collaborating with doctors that are distinct from collaboration skills required for working with other academic disciplines. A Biostatistics department is not sufficient to serve as the center of a statistical practice that supports the many non-medical disciplines that are important to the state of Nebraska: agriculture, animal science, population genetics (animal and plant), engineering, social sciences, education, business, physics, chemistry, and biology. <a href="#sec-peer-analysis" class="quarto-xref">Section&nbsp;4</a> includes a discussion of peer R1 and AAU institutions, many of whom maintain both statistics and biostatistics departments.</p>
<p>There is also a Mathematics department at UNO which offers statistics coursework and a data science program. Of the 18 tenured and tenure-track faculty in this department, there are three with statistics Ph.D.s (see <a href="#tbl-uno-math" class="quarto-xref">Table&nbsp;5</a> for a full list). UNO is not an R1 university, and faculty there have a much heavier teaching load than faculty at UNL; consequently, it stands to reason that the UNO Mathematics department would not be able to significantly alleviate the statistics need across the university that would be created through the proposed elimination of the Statistics department in favor of a distributed model.</p>
<p>The University of Nebraska - Kearney has a mathematics and statistics department which does not appear to contain any statisticians, according to the research interests listed on the faculty web pages. Moreover, as UNK does not have a statistics program at any level, it stands to reason that UNK Mathematics &amp; Statistics faculty will not be able to help UNL with its proposal to use a distributed model for the university’s statistics instruction, collaboration, consulting, and research needs.</p>
</section>
</section>
<section id="sec-metrics" class="level1 page-columns page-full" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Metrics</h1>
<p>We begin this section by acknowledging that it is <em>hard</em> to assemble fully correct data that best represents our department, and that the task to assemble all of the (correct) data for all departments on campus is indeed a difficult one. We teach several courses in our department which describe how to build a data pipeline, from collection to cleaning to visualization, and we believe having a resource on campus which can consult on these tasks is fundamentally important to both the research and administration of the university. Our students are taught to consider the impact of the decisions which are made during assembly of a data pipeline when conducting the resulting statistical analysis; it is this step that is most obviously missing from the metrics provided to APC to justify the budget reduction plan. The department would be more than happy to assist with future projects evaluating the efficiency of units across campus, and integrating this data into a course as a service learning opportunity would have very real benefits. This data is both extremely interesting and provides an excellent demonstration of the importance of a variety of concepts from data documentation to reproducibility and the different varieties of messy data which often appear in real-world analyses.</p>
<p>However, we would be remiss if we did not note that administration has access to resources which have not been made available to departments seeking to understand how the relevant metrics were assembled. Ultimately, these issues are not particularly relevant to the importance of the Statistics department within the University of Nebraska ecosystem, and so we will defer discussion of the most egregious issues to <a href="#sec-metric-problems" class="quarto-xref">Section&nbsp;8.2</a><a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>.</p>
<section id="research" class="level2 page-columns page-full" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="research"><span class="header-section-number">3.1</span> Research</h2>
<p>The Scholarly Research Index (SRI) is a measure developed by Academic Analytics to evaluate the research performance of individuals and entities with respect to (1) scholarly products, such as conference proceedings, research articles, books, and book chapters, (2) recognition from the community in form of citations and awards, and (3) federal sponsoring of research projects measured by the number of grants and their amounts.</p>
<p>Different disciplines operate differently. The weighting of each of these measures is discipline specific (based on a factor analysis by Academic Analytics); the weights for statistics are shown in <a href="#tbl-metrics-aa-stat-weights" class="quarto-xref">Table&nbsp;1</a>.</p>

<div class="no-row-height column-margin column-container"><div class="">
<div id="tbl-metrics-aa-stat-weights" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-metrics-aa-stat-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Academic Analytics weights used to evaluate statistics department research performance and impact.
</figcaption>
<div aria-describedby="tbl-metrics-aa-stat-weights-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>Category</th>
<th style="text-align: right;">Weight</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Articles</td>
<td style="text-align: right;">18</td>
</tr>
<tr class="even">
<td>Awards</td>
<td style="text-align: right;">19</td>
</tr>
<tr class="odd">
<td>Books</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="even">
<td>Chapters</td>
<td style="text-align: right;">5</td>
</tr>
<tr class="odd">
<td>Citations</td>
<td style="text-align: right;">20</td>
</tr>
<tr class="even">
<td>Conf Procs</td>
<td style="text-align: right;">11</td>
</tr>
<tr class="odd">
<td>Grant $</td>
<td style="text-align: right;">22</td>
</tr>
<tr class="even">
<td>Patents</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="odd">
<td>Trials</td>
<td style="text-align: right;">0</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td style="text-align: right;"><strong>100</strong></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</div></div><p>UNL Statistics has (based on data through December 2023) an SRI of 0.4 based on all R1 and R2 institutions tracked by Academic Analytics. Academic Analytics also offers the ability to compute an SRI based on a custom comparison group; using only AAU universities, the department’s custom SRI is -0.1.</p>
<p>Importantly, however, because SRI is the result of discipline-specific weights, it <strong>cannot</strong> be effectively compared across departments. Each discipline has a different distribution of SRI values, and comparing across disciplines without accounting for these distributional differences is not only incorrect but extremely misleading. <a href="#fig-sri-percentile-all-depts" class="quarto-xref">Figure&nbsp;1</a> shows the SRI percentile for each department on campus when compared to other R1 and R2 departments. While several departments which have been proposed to be eliminated are indeed performing below the median, many departments are also above-average in their respective fields. We teach statistics students to carefully consider the appropriate comparison population and the real-world meaning of the numbers they use in analyses; it is important that UNL’s administration does the same. After all, it is less important that Statistics publishes the same amount of papers or generates the same amount of grant funding as Physics, because grants in those fields cover different things (statisticians don’t need particle accelerators very frequently) and publication norms are also different. What matters is whether departments are doing good work as measured by comparisons to the appropriate peers, both actual and aspirational.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sri-percentile-all-depts" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sri-percentile-all-depts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2025-Stat-APC-report_files/figure-html/fig-sri-percentile-all-depts-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sri-percentile-all-depts-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: UNL Units ranked by SRI percentile compared to peer departments in Academic Analytics. Points are colored by the budget proposal status. Some of the departments proposed to be eliminated are extremely well ranked.
</figcaption>
</figure>
</div>
</div>
</div>
<p>UNL’s ranking indicates that the Statistics department’s research productivity and recognition is better than 75% of other R1 and R2 institutions.</p>
<p>Comparing the Statistics department’s SRI to other Statistics departments (<a href="#fig-sri-by-class" class="quarto-xref">Figure&nbsp;2</a>), it is clear that the UNL Statistics department performs better than several well-respected AAU and Big Ten institutions. That is, if the Statistics department is eliminated, it is likely to hurt UNL’s case to be readmitted to the AAU, even though our SRI is below the mean for AAU institutions. Instead, what is clear is that the Statistics department is performing within the range expected of statistics departments at AAU institutions.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sri-by-class" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sri-by-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2025-Stat-APC-report_files/figure-html/fig-sri-by-class-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sri-by-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Research performance (SRI percentile) of units by classification. UNL is performing extremely well compared to its peers and has better performance than many AAU institutions.
</figcaption>
</figure>
</div>
</div>
</div>
<p>What is remarkable is that UNL does all of this with a department that is very small relative to its peers, as shown in <a href="#fig-size-by-class" class="quarto-xref">Figure&nbsp;3</a>. It should be noted that UNL offers a full complement of statistics degrees and supports the data science program with this small faculty (13 tenure-track professors and a 30% FTE teaching professor of practice) while keeping research productivity high.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-size-by-class" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-size-by-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2025-Stat-APC-report_files/figure-html/fig-size-by-class-1.png" class="img-fluid figure-img" width="960">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-size-by-class-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Size of Statistics-related Units at each institution. UNL is managing to handle all of its BS, MS, and PhD programs within a department that is extremely small relative to peer institutions at both R1 and AAU institutions.
</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="teaching" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="teaching"><span class="header-section-number">3.2</span> Teaching</h2>
<p>The Statistics department has high-SCH service courses, which the budget proposal recognizes and plans to continue. However, it is not clear how these courses will be taught - currently, they are taught by a combination of graduate students with training in statistics pedagogy and tenure-track faculty. The <a href="documentation/1993-Biometry-APR-SelfStudy.pdf">1993 Biometry APR Self Study</a> (pg 29) documented the challenges of appropriately staffing e.g.&nbsp;801 and 802 labs when motivating their desire to start a Ph.D.&nbsp;program:</p>
<blockquote class="blockquote">
<p>Enhanced teaching. Biometry has a number of classes with labs. We are constantly struggling to place graduate students with an appropriate background as lab instructors. For example, our M.S. students are required to take BIOM 802 (Experimental Design), which has a lab. They cannot teach the lab until they have had the course themselves… In general, Ph.D.&nbsp;level graduate students can make a variety of contributions to the teaching program that faculty do not have the time to make and M.S. students lack the background to make.</p>
</blockquote>
<p>Currently, the Statistics department offers approximately 15 sections of Stat 218 (8 in fall, 7 in spring), in addition to 6 sections of Stat 380, and two sections of 801 (with 2 sections of lab each) and 802. Stat 870 is offered less frequently, so we will exclude it from this analysis. The courses identified to be kept require 25 sections across 4 preps; we estimate that this would require at least 3 professors of practice to teach (assuming a 4-4 load) which are not accounted for by the current budget reduction plan. These FTEs would need to be subtracted from the savings listed, yielding only 9 FTE savings for cutting four programs (BS in Statistics, BS in Data Science from CASNR, MS in Statistics, and Ph.D.&nbsp;in Statistics). In addition, Stat 218, 380, 801, and 802 regularly benefit from statistical research (for instance, an experiential learning activity in Stat 218 is used to introduce data visualization topics to students), and these benefits would disappear if all statistics coursework was offered by teaching-only professors of practice. We use professors of practice for this comparison rather than adjuncts both because it seems unlikely that 25 courses could be assigned to adjuncts with statistical training, given that most people with graduate degrees in Statistics can make more freelancing as data scientists than they would be compensated for teaching courses.</p>
<p>The calculations for how many PoPs would be required to teach current Statistics courses that drive revenue generation for the department does not include courses not identified by IANR, such as Stat 462 and Stat 463, which are required for the Actuarial Science degree in Business and the Actuarial Science Mathematics concentration. Two additional Stat 300/400 level courses are required for the Mathematics, Statistics, and Data Science focus area within the Math department beyond Stat 380. The Digital Agriculture minor also requires Stat 151 and 251, computing courses developed for the Statistics undergraduate major. The Agricultural Economics Ph.D.&nbsp;requires Stat 882, and the Finance Ph.D.&nbsp;requires 9 hours of graduate Statistics coursework (it is quite possible that Stat 882 and 883 would be preferable to 801 and 802 for Finance majors). This analysis does not consider the fate of the Data Science programs in CAS and COE, which would lose the Statistics focus area that is primarily made up of courses designed for the Statistics and Data Analytics major and the Statistics minor. In order to support these additional courses, an additional professor of practice would likely be required, reducing the FTE savings from eliminating the department to 8.</p>
<p>The department’s teaching metrics are also not representative of recent changes we have made in order to be more efficient. We have recently increased class sizes for Stat 218, but have not been able to increase section sizes beyond approximately 80 students per section due to a lack of availability for large lecture halls. In past years, Stat 218 sections were more often 30 or 45 students each – we have made these changes to increase instructional efficiency as a result of the initial metrics, but of course none of these changes have been reflected in the numbers because data after 2024 is not included. Similarly, we began offering Stat 801 and 802 online in order to better support outstate students in various IANR programs, but this new modality has not been available for long enough to change the enrollment metrics. The department has been consistently working to increase instructional efficiency, even as we roll out a new undergraduate curriculum without additional FTE to support that program, however, it takes time to move our courses to larger city campus classrooms because of the relative lack of large classrooms on East campus, and ultimately there is a limit to the capacity of these classrooms that provides an upper limit on efficiency increases.</p>
</section>
<section id="consulting" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="consulting"><span class="header-section-number">3.3</span> Consulting</h2>
<p>In 1957, the seeds of the Statistics Department were planted with the founding of the Statistical Laboratory, which would provide statistical computing and consulting services to IANR. The consulting mission of the laboratory motivated the creation of the MS program in Biometry and the Ph.D.&nbsp;program in Statistics so that the department could meet more of the demand for statistical consultation and assistance with experimental design and statistical computing tasks.</p>
<blockquote class="blockquote">
<p>…advanced graduate students can do routine statistical consulting on their own. This improves everybody’s access to statistical consulting and frees the faculty to concentrate on more difficult consulting problems. In Spring semester, 1993, Biometry instituted a “Help Desk” staffed by a graduate student. The response has been very good; she has been very busy with a variety of problems. - <a href="documentation/1993-Biometry-APR-SelfStudy.pdf">1993 Biometry APR Self-Study, pg 29</a></p>
</blockquote>
<p>It is important to note that even in 1993, it was clear that the 8 tenured or tenure-track faculty in Biometry could not meet the demand within IANR for statistical consulting. The current proposal maintains 1 FTE of the current 13 FTE in the Statistics department, which is well below even 1957 levels of funding and support.</p>
<div class="cell">
<div id="tbl-sc3l-clients" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sc3l-clients-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: SC3L clients, 2020-2025. The SC3L is essential for research in departments across campus, but also has worked with clients from UNO, UNMC, and UNK. Ultimately, the entire university system would be hurt by the proposal to eliminate the Statistics department, because the SC3L is staffed by statistics graduate students. One supervisor cannot reasonably perform the consulting tasks currently handled by 5 students working 20+ hours a week.
</figcaption>
<div aria-describedby="tbl-sc3l-clients-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 63%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Department</th>
<th style="text-align: right;">2020</th>
<th style="text-align: right;">2021</th>
<th style="text-align: right;">2022</th>
<th style="text-align: right;">2023</th>
<th style="text-align: right;">2024</th>
<th style="text-align: right;">2025</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Agricultural Economics</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Agricultural Leadership, Education and Communication</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Agronomy and Horticulture</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">33</td>
<td style="text-align: right;">31</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">13</td>
</tr>
<tr class="even">
<td style="text-align: left;">Animal Science</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Athletics</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Biochemistry</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biological Systems Engineering</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">13</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Biology</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Biotechnology</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Birth Outcomes and Water Research</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">CAS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">CEHS</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">CYAF</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Chemistry</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Civil and Environmental Engineering</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Communication Studies</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Computer Science and Engineering</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Criminology and Criminal Justice</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Dental Hygiene</td>
<td style="text-align: right;">24</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">15</td>
<td style="text-align: right;">14</td>
</tr>
<tr class="even">
<td style="text-align: left;">EDPS</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Earth &amp; Atmospheric Sciences</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Education</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">English</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Entomology</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">27</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">8</td>
<td style="text-align: right;">6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Environmental and Sustainability Studies</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Food Science and Technology</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">16</td>
<td style="text-align: right;">9</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Glenn Korff School of Music</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Growth &amp; Development</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Marketing</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Mathematics</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mechanical</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Music - Vocal Pedagogy</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">National Drought Mitigation Center</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">NeDNR - Water Planning Division</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nebraska Forest Service</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Neurocarrus</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nutrition and Health Sciences</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Office of Academic and Student Affairs</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Office of Research</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Oral Radiology</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Other</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Panhandle Research and Extension Center</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Philosophy</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Physics</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Plant Pathology</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">Political Science</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Psychology</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Public Policy Center</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">SGIS-Anthropology</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">SVBMS</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="odd">
<td style="text-align: left;">School of Biological Sciences</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
</tr>
<tr class="even">
<td style="text-align: left;">School of Natural Resources</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">6</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">8</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sociology</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">2</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="even">
<td style="text-align: left;">Southwest Fire and Rescue</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">TLTE</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">Testing Center</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">4</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">Textile Science</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
</tr>
<tr class="even">
<td style="text-align: left;">UNK Communication</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: left;">UNMC</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">4</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">3</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">University Libraries</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;"></td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">2</td>
<td style="text-align: right;">1</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>As <a href="#tbl-sc3l-clients" class="quarto-xref">Table&nbsp;2</a> shows, the SC3L handles a large number of projects over the course of a single year. Many of these projects are graduate research in other departments, and result in publications which only sometimes include the SC3L consultant and very rarely include any Statistics faculty. Thus, these contributions to the research activity across the university and system are simply not counted in the metrics, as graduate student papers are not counted in the department’s metrics.</p>
<p>Moreover, Kathy Hanford, the head of the SC3L until her retirement in 2023, had a Professor of Practice position, which means her research outputs are not counted in the department’s contributions, both because she was not in a tenure-track position, and because she retired in December 2023 and was thus not in the department when the data were assembled.</p>
<p>Currently, the SC3L employs five graduate students for 20 hours a week each, though they generally work on SC3L projects more than the 20 hours required by their assistantships. There is no way that the single FTE dedicated to the SC3L under the current budget can manage this workload. In addition, under the new rules imposed by IANR, this 100 hours per week (plus the SC3L director’s time) is devoted only to IANR projects. The demand for consulting services in other colleges and units is surely much higher.</p>
<p>Without the graduate students supported by the SC3L, UNL risks publishing studies which are the product of faulty statistical analysis, or which employ sub-optimal experimental designs. This will slowly erode the reputation of other departments on campus, and will make UNL less competitive for federal funding. Ultimately, reducing the consulting resources on campus threatens the ability of UNL to maintain its status as a Big Ten, land-grant, AAU-aspiring R1 university.</p>
</section>
<section id="collaboration" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="collaboration"><span class="header-section-number">3.4</span> Collaboration</h2>
</section>
</section>
<section id="sec-peer-analysis" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Peer Analysis</h1>
<p>There is an incredible diversity of both names and structures for housing statisticians within units across R1 and AAU universities. For the purposes of this analysis, there are two characteristics which seem to be particularly important:</p>
<ul>
<li>A group of statisticians located in the same department (whether that is called Statistics, Data Science, or Mathematics &amp; Statistics), where</li>
<li>The department offers programs in Statistics at the undergraduate or graduate level</li>
</ul>
<p>We exclude from this “big tent” biostatistics departments, not because they don’t serve a similar role, but because many universities have both Statistics and Biostatistics departments<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>, and so we track Biostatistics as a separate (but closely related) discipline. Note that our approach differs from the Academic Analytics tracking of Statistics as a discipline, but the conclusions of this analysis are largely the same using either approach.</p>
<section id="r1-universities" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="r1-universities"><span class="header-section-number">4.1</span> R1 Universities</h2>
<p>Of the 186 R1 universities, only 1 does not have a stand-alone statistics, biostatistics, or data science department. If we exclude biostatistics, only 16 do not have a stand-alone statistics or data science department, and of these, 8 are medical schools which do not grant undergraduate degrees outside of the health sciences<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>.</p>
<blockquote class="blockquote">
<p>Agencies such as NIH, NSF, USDA, and DOE expect a strong institutional presence in statistics when awarding large research grants. Eliminating the department will send a negative signal to funders, and the resulting shortfall in research funding will, over time, exceed the current budget savings.<br>
– <a href="letters/LetterVidakovic_TAMU.pdf">Brani Vidakovic, Chair, Texas A&amp;M and former Program Director, National Science Foundation</a></p>
</blockquote>
</section>
<section id="land-grant-universities" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="land-grant-universities"><span class="header-section-number">4.2</span> Land Grant Universities</h2>
<p>If we instead consider our 48 land-grant peers, all 48 have a stand-alone statistics or data science department, and 27 also have a biostatistics department. That is, UNL would be alone among land-grant institutions if the proposed elimination of the Statistics department goes through.</p>
<blockquote class="blockquote">
<p>Disbanding Statistics would immediately weaken UNL’s standing as a comprehensive, research‐intensive institution. It would jeopardize collaborations across colleges, with federal agencies, industry, and other universities, and risk signaling a retreat from UNL’s land-grant mission. – <a href="letters/UNL_Statistics_Support_Letter_ThomasLee.pdf">Thomas Lee, Distinguished Professor of Statistics, UC Davis</a></p>
</blockquote>
</section>
<section id="aau-universities" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="aau-universities"><span class="header-section-number">4.3</span> AAU Universities</h2>
<p>If instead we compare to the 69 AAU universities, all 69 have a stand-alone statistics, biostatistics, or data science department and only 3 do not have a statistics or data science department<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>.</p>
<p>Faculty outside the department of Statistics recognize the essential function we serve and the threat to the University’s standing among its peers if the Statistics department is eliminated:</p>
<blockquote class="blockquote">
<p>Every AAU member university and every Big Ten university maintains a Department of Statistics (or an equivalent stand-alone unit) as a core component of their research infrastructure. Eliminating ours would immediately place UNL at a disadvantage relative to our peers and signal a retreat from the standards of excellence required for AAU membership.<br>
– <a href="letters/Letter%20of%20support%20for%20Stats%20department_Hyten.pdf">David Hyten, Letter to APC</a></p>
</blockquote>
<p>And this assessment is shared by the chairs of other Big Ten statistics departments:</p>
<blockquote class="blockquote">
<p>Moreover, dissolving the Statistics Department will make it difficult, if not impossible, for UNL to achieve its goal of rejoining the Association of American Universities (AAU). – <a href="letters/Big10_UNL_Letter.pdf">Big Ten Statistics Department Chairs</a></p>
</blockquote>
<p>While it is often desireable to be unique in a field, eliminating the statistics department would be more akin to notoriety. Statistics expertise is <strong>essential</strong> to the function of a modern R1 land-grant institution, particularly in a state where there is not another competing R1 institution which might serve researchers at both schools. We fear that if the Statistics department is cut, UNL will soon lose not only any hope of rejoining the AAU, but may also find its R1 status threatened. The proposed elimination of the department has threatened UNL’s international reputation, but going through with that elimination would have dire consequences for the institution’s standing among its peers.</p>
<blockquote class="blockquote">
<p>Statistics is the backbone of modern research across all fields, from agriculture and medicine to engineering and social sciences. The expertise provided by statisticians is essential for designing experiments, analyzing data, and interpreting results. Without a dedicated Statistics Department, UNL will lose its competitive edge in research and innovation, and a fall in research quality and rankings is inevitable. – Rob Hyndman, Monash University, Australia.</p>
</blockquote>
<p>The Statistics department has assembled letters from a truly international array of scientists and statisticians, each expressing opposition and confusion as to the elimination of the Statistics department. Hungarian statisticians, Pakistani historians and statisticians,</p>
<p>Statistics departments provide many services which are essential to modern research universities. At UNL, the statistics department also provides unique, valuable, and essential programs within the educational ecosystem of Nebraska. In addition, the department provides essential support for many other programs across the university. These contributions are discussed in <a href="#sec-program-analysis" class="quarto-xref">Section&nbsp;5</a>.</p>
</section>
</section>
<section id="sec-program-analysis" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Program Analysis</h1>
<section id="apc-criteria" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="apc-criteria"><span class="header-section-number">5.1</span> APC Criteria</h2>
<p>The APC procedures specify criteria for the reduction or elimination of academic programs. We will address each set of criteria separately to both show that the criteria in support of reduction or elimination are not met and to show that the criteria indicating that elimination is inadvisable are satisfied. These are taken from APC <a href="https://apc.unl.edu/procedures-be-invoked-significant-budget-reallocations-and-reductions/criteria/">Criteria for program evaluation</a>.</p>
<section id="addressing-the-criteria-in-support-of-reduction" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="addressing-the-criteria-in-support-of-reduction"><span class="header-section-number">5.1.1</span> Addressing the Criteria in Support of Reduction</h3>
<blockquote class="blockquote">
<ol type="1">
<li><p>The program’s present and probable future demand is insufficient to justify its maintenance at existing levels of support. Insufficient demand may be indicated by significant decline in one or more of these areas over a protracted period:</p></li>
<li><p>the number of completed applications for admission to the program;</p></li>
<li><p>the student credit hours generated in lower division, upper division, professional, and/or graduate level courses in the program;</p></li>
<li><p>the number of students who complete majors or degrees in the program;</p></li>
<li><p>in the case of instructional programs designed to prepare graduates for specific employment, the market demand for graduates of the program;</p></li>
<li><p>in the case of service programs, the level of demand for the service provided;</p></li>
<li><p>in the case of research programs, the quality and quantity of research being conducted;</p></li>
<li><p>in the case of research programs, the level of external funding, given the relative availability of funds.</p></li>
</ol>
</blockquote>
<p>Of the fastest growing occupations identified by the Bureau of Labor Statistics, Data Scienctists, Actuaries, and Operations research analysts are 4th, 8th, and 9th, respectively. All involve statistical training, and many data science jobs would have been advertised as requiring a statistics degree even 5 years ago. However, even if we confine ourself to Statisticians, the BLS expects 9% growth in statistics positions over the next decade, which is considerably faster growth than most other professions. Thus, we can see that the market demand for graduates of our programs at all levels is there. In addition, while statistics does not pull in grants which are comparable in size to those in lab-based sciences that require laboratory equipment, AI is one of the stated research priorities of the current administration. Most deep learning and large language models are built on a fundamental foundation of statistics.</p>
<p>While we are early in our undergraduate program, and have not yet existed long enough to graduate our first class, we expect that the increased demand for data scientists and statisticians should result in increased enrollment in the program over the near term, so long as we have sufficient support from the university for advertising and recruiting. Of course, it is easier to recruit students when it is possible to make statements about graduates having found jobs, or continued on to graduate school. For instance, we can advertise our Ph.D.&nbsp;program by saying that all graduates have found employment in their field, whether in academia, government, or industry. It is somewhat harder to recruit new students before the program has graduated its first class. This is one reason why the <a href="https://ccpe.nebraska.gov/sites/default/files/AP_Guidelines_Review%20of%20Existing%20Instructional%20Programs.pdf">NE Coordinating Commission for Postsecondary Education</a> rules require a five-year period to evaluate program enrollment and graduation rates.</p>
<p>Given the demand for statistics and data science education, Criteria 1.1.1.1-7 cannot be used to support elimination of the department<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
<blockquote class="blockquote">
<ol start="2" type="1">
<li>The program would normally be expected to be accredited but is not; or it is exposed to a substantial risk of loss of accreditation. If the program is not appropriate for accreditation, the program has been deemed to be of a quality or size that raises questions concerning its viability or continuation.</li>
</ol>
</blockquote>
<p>The graduate statistics program at UNL has been increasing in ranking over the past 5-10 years. It is seen as a small-but-quality program within our discipline, and our graduates all get jobs working within their field of study, whether in industry, government, or academia.</p>
<p>Our undergraduate statistics program is known for having a high proportion of statistics coursework, which is why many of our current students selected this program over Data Science and over programs at other institutions. While our undergraduate curriculum is still young, it was favorably evaluated at our last APR, which occurred before the first cohort started.</p>
<blockquote class="blockquote">
<p>“The undergraduate program plan is an outstanding one – we are impressed by the vision and effort that has gone into this already. We think this is very important for UNL and the State of Nebraska, given the enormous demand for people who are highly trained in statistics. Based on what has been observed nationwide, we expect this program to grow very quickly – potentially to hundreds of majors in the near future. Hence, developing and teaching thee courses, as well as addressing student advising needs will require considerable resources in terms of faculty and staff. It is important to be cognizant of the amount of time and effort to build this program. We note that three members of the external review team are in large statistics departments that have many more tenure-track faculty and teaching faculty than Statistics at Nebraska. Even with our resources, we have found it to be a challenging undertaking to find the people hours necessary to build new majors.” - <a href="documentation/2021-STAT-APR-Report.pdf">2021 APR Report</a></p>
</blockquote>
<p>Thus, we do not believe criteria 1.1.2 applies to the statistics department; it should not be used to support our elimination.</p>
<blockquote class="blockquote">
<ol start="3" type="1">
<li><p>The program’s productivity relative to the university’s investment in faculty, staff, and equipment, facilities, or other resources has declined significantly.</p>
<ol type="1">
<li>In the case of instructional programs, a significant decline in productivity might be indicated by a decrease in the generation of student credit hours of all courses per full-time equivalent (FTE) faculty over the past five years relative to UNL enrollment trends and by a low level of student credit hours per full-time equivalent (FTE) faculty in comparison to that of UNL’s peer institutions and/or similar programs at UNL.</li>
<li>In the case of non-instructional programs, productivity shall, where possible, be measured in terms of units of output appropriate to the program’s mission.</li>
</ol></li>
</ol>
</blockquote>
<p>At the request of the CASNR Dean, our department has implemented an undergraduate program in Statistics and Data Analytics (approved 2021, first cohort 2022) and is an important component of the undergraduate Data Science programs in CASNR, School of Computing, and the College of Arts and Science (approved 2022). The undergraduate program requires 51 hours of statistics coursework, making it unique within the ecosystem of undergraduate statistics programs; this was a factor for several of our current students who chose UNL over other options.</p>
<p>The department has developed the new courses for this program (typically without course releases, representing a significant increase in effective teaching workload), and has implemented this program without any of the promised increases in TT faculty or professors of practice to assist with the additional courses. These additional courses may be captured in the metrics in some ways – it is possible that research output might have decreased slightly given the large increase in teaching and course design load, as was predicted by the review team in the 2021 APR if we did not continue to increase the department size to manage the increased course load.</p>
<blockquote class="blockquote">
<p>The main resources needed to implement the undergraduate Statistics and Data Analytics major and the forthcoming Statistical Data Science major are people and energy. The major requires the development of a considerable number of new courses. To develop these courses with only the existing faculty would require major sacrificees to faculty research programs and to their ability to collaborate with IANR and other faculty at UNL. New faculty will need to be hired to develop coursework for the majors. - <a href="documentation/2021-STAT-APR-Report.pdf">2021 APR Report</a></p>
</blockquote>
<p>It is also possible that the average course size may have decreased in the department over the last 3-4 years due to the large increase in new courses along with relatively small initial cohorts as the major started but before we could advertise the job and graduate school placements of our graduates (we will have a couple of students graduating early in December and the rest of the first cohort graduating in May). However, we have done this at the request of our leadership, and the program we designed is both unique and well-regarded by our peers.</p>
<blockquote class="blockquote">
<p>The development of new undergraduate majors is very important not only to UNL but more broadly to the state of Nebraska given the urgent need for highly trained statisticians and data scientists. Furthermore, this program will generate substantial resources for IANR; the department needs resources to develop, deliver, and grow these programs. - <a href="documentation/2021-STAT-APR-Report.pdf">2021 APR Report</a></p>
</blockquote>
<blockquote class="blockquote">
<ol start="4" type="1">
<li>The instructional productivity of a program is substantially less than the average for UNL as a whole. The level of instruction and the mode of instruction appropriate to the program shall be considered, including particularly the average number of contact hours carried by the faculty.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="5" type="1">
<li>The program’s reduction or elimination will not substantially impair the viability or quality of other UNL programs.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="6" type="1">
<li>The program’s contribution to the UNL missions of instruction, research, and service is sufficiently marginal not to justify maintenance of its present size.</li>
</ol>
</blockquote>
</section>
<section id="addressing-the-criteria-indicating-that-elimination-is-inadvisable" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="addressing-the-criteria-indicating-that-elimination-is-inadvisable"><span class="header-section-number">5.1.2</span> Addressing the Criteria Indicating that Elimination is Inadvisable</h3>
<blockquote class="blockquote">
<ol type="1">
<li>The program has achieved a national or international reputation for quality as indicated by objective evaluations.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="2" type="1">
<li>The program supplies significant instruction, research, or service that UNL is better equipped to supply than other colleges or universities.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="3" type="1">
<li>The program is the only one of its kind within the State of Nebraska.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="4" type="1">
<li>The program is an essential program for every university.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="5" type="1">
<li>The program’s elimination would have a substantially negative impact on education and societal concerns in Nebraska.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="6" type="1">
<li>The program’s elimination would result in substantial loss of revenue currently derived from grants, contracts, endowments or gifts.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="7" type="1">
<li>The program represents a substantial capital investment in specialized physical plant or equipment that could not be effectively redirected to alternative uses.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="8" type="1">
<li>The program is central to maintaining the university’s affirmative action goals.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="9" type="1">
<li>The program gives the University of Nebraska-Lincoln its distinctive character.</li>
</ol>
</blockquote>
</section>
<section id="addressing-criteria-indicating-that-reduction-is-inadvisable" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="addressing-criteria-indicating-that-reduction-is-inadvisable"><span class="header-section-number">5.1.3</span> Addressing Criteria Indicating that Reduction is Inadvisable</h3>
<blockquote class="blockquote">
<ol type="1">
<li>The program’s nature is such that reduction would impair the critical mass necessary to have adequate quality.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="2" type="1">
<li>The program cannot be reduced without a substantial risk to accreditation.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="3" type="1">
<li>Current projections indicate that demand for the program or its graduates will increase substantially within the next five years.</li>
</ol>
</blockquote>
<blockquote class="blockquote">
<ol start="4" type="1">
<li>Scholarly research or creative activity of the faculty within this program, as shown by publications, creative productions, honors and awards, external funding, or other objective measure, is higher than others in the same or related peer disciplines.</li>
</ol>
</blockquote>
</section>
</section>
<section id="effects-of-proposed-cuts-on-outside-programs" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="effects-of-proposed-cuts-on-outside-programs"><span class="header-section-number">5.2</span> Effects of Proposed Cuts on Outside Programs</h2>
<section id="mathematics" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="mathematics"><span class="header-section-number">5.2.1</span> Mathematics</h3>
<p><a href="documentation/Effects%20of%20Proposed%20Cuts%20to%20Undergraduate%20Program-Math.docx"><em>This section was contributed by Alex Zupan, Undergraduate Chair, Mathematics, and Doug Pellatz, Senior Academic Advisor, College of Arts and Sciences</em></a></p>
<p>Cutting the Department of Statistics will have significant and lasting effects on the undergraduate program in the Department of Mathematics. Elimination of courses will be most deeply felt by students majoring in CAS Data Science and by students pursuing the Statistics and Data Science Option and Mathematical Finance Option within the Mathematics major. We were relieved to see IANR’s plan to continue to offer STAT 218, 318, 380, 462, and 463, which means there would be sufficient Statistics courses offered to complete the Data Science major and the Math major on the Mathematical Finance and the Statistics and Data Science options. However, the Statistical Modeling focus area of the Data Science major would likely need to be eliminated or greatly revised considering the proposed cuts. There would also be far fewer Statistics course options available with the Statistics and Data Science option of the Math major.</p>
<p>As of the beginning of the fall 2025 semester, a total of 26 students had declared a Math major within the Statistics and Data Science option, and 21 students had declared within the Mathematical Finance option. The number of students graduating in the former option has been continuously increasing since the introduction of this option in 2020. The CAS Data Science major has seen even more dramatic increases, with 17 declared majors in the fall of 2023, 59 declared majors in the fall of 2024, and 83 declared majors in the fall of 2025. The curriculum for these majors is well-balanced between Math, Computer Science, and Statistics courses, with input and shared leadership among all three departments, and we view this major as one of the most interdisciplinary majors in the university. Losing the statistics department would be a significant blow to this valued interdisciplinarity.</p>
<p>One motivating factor for the steep growth curve of the Data Science program is a strong positive jobs outlook. This field is highly regarded across disciplines. In a 2023 conversation with Stephen Cooper, the former Director of the Raikes program, he declared that within five years, he expected most Raikes students would have Data Science as one of their majors. Cutting one of the three pillars of the Data Science major would almost certainly hamper this growth. Students graduating within the Statistics and Data Science option of the Math major have thus far had excellent internship and career prospects. When they graduate, we ask students to fill out a voluntary exit survey, and in 2024 and 2025, students in this option have reported completing internships at companies such as Kiewit, 84.51°, the Federal Reserve Bank of Kansas City, and they report having jobs as data scientists, software engineers, and a number of other positions.<br>
This field and its employment prospects are enjoying a wave of growth and popularity, and we can choose to grow with it, or we can hamstring our efforts with cuts that may ultimately prove to be shortsighted.</p>
<p>Finally, we understand that statistics courses will continue to be taught at UNL, but we have grave concerns about the long-term ability of the university to attract high-achieving statistics faculty with modern knowledge about a quickly evolving field, the type of faculty members who can provide high-quality instruction to our majors and who have the expertise to lead undergraduate research projects in data science.<br>
The department has been in conversations about our curriculum with Bill Anderson, a retired data science expert who held leadership positions at Microsoft, United Healthcare, and Ford, and who has consulted for senior design groups within the Raikes School. In a recent meeting, Bill reported that the use of statistics in the real world is dramatically changing.<br>
The meteoric rise of AI tools has enabled data scientists to implement new solutions with unprecedented speed, but according to Bill, these solutions require statistics for measurement – to determine to what extent new techniques are working and whether they are reliable, ethical, and fair – and the industry has not yet fully realized this need. Our Data Science majors, with their unique synthesis of mathematical, computing, and statistical knowledge are well-positioned to be leaders in their fields upon graduating from UNL, and without a thriving Department of Statistics, we may not be able to continue making this assertion with confidence.</p>
</section>
<section id="university-wide-impact" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="university-wide-impact"><span class="header-section-number">5.2.2</span> University-Wide Impact</h3>
<p>The statistics department teaches courses which are required for degree programs across the university.</p>
<blockquote class="blockquote">
<p>The plan proposes to strategically deploy a portion of state-appropriated funds to continue to offer:</p>
<ul>
<li>Critical student competencies. Undergraduate and graduate students would continue to gain essential skills in statistics and data analytics for their future careers. We anticipate course offerings would include STAT 218, STAT 380, STAT 801, STAT 802, STAT 870, complemented by additional coursework in R programming, bioinformatics, computational biology, quantitative genetics/genomics, and data analysis interpretation and visualization offered through other units.</li>
</ul>
</blockquote>
<p>Unfortunately, the budget proposal has massively under-estimated the importance of statistics in curricula across campus, as shown in <a href="#tbl-stat-courses-reqd" class="quarto-xref">Table&nbsp;3</a>.</p>
<div class="cell">
<div id="tbl-stat-courses-reqd" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stat-courses-reqd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Statistics courses required by other programs across campus. The budget proposal calls for maintaining some statistics courses; programs which require courses that will not be offered are highlighted.
</figcaption>
<div aria-describedby="tbl-stat-courses-reqd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Program</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Level</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">College</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Classes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 15em;">Fisheries and Wildlife</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218 or STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Forensic Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Environmental Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Animal Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Regional and Community Forestry</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218 or STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Agricultural Leadership, Education and Communication, Agricultural and Environmental Sciences Communication Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Grassland Systems</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Plant Biology</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Insect Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Agricultural Economics, Quantitative Analysis Option</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CASNR</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Agricultural Systems Technology</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Biochemistry (CASNR), Computational and Systems Biochemistry Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Digital Agriculture Minor</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CASNR</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 151, 251, 218</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Actuarial Science (CAS)</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CAS</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 462, 463</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Biochemistry (CAS), Computational Biochemistry Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Meterology-Climatology</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Actuarial Science (Business)</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">Business</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 462, 463</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Secondary Education: Mathematics</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CEHS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Software Engineering</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Computer Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Mathematics, Education Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Mathematics, Mathematical Biology Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Mathematics, Mathematical Finance Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Mathematics, Statistics and Data Science Option</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CAS</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 380, 2 additional 300/400 level STAT courses</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Data Science, CAS</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CAS</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 218 or 380 + STAT 318 -or- STAT 101 + STAT 102; Included in focus areas: STAT 251, 351, 212, 301, 302, 325, 412, 414, 432, 443, 450, 462, 463, 464, 474, 475, 478, 468</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Data Science, Engineering</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">Engineering</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 218 or 380 + STAT 318 -or- STAT 101 + STAT 102; Included in focus areas: STAT 251, 351, 212, 301, 302, 325, 412, 414, 432, 443, 450, 462, 463, 464, 474, 475, 478, 468</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Agricultural Economics, PhD</td>
<td style="text-align: left; background-color: yellow !important;">G</td>
<td style="text-align: left; background-color: yellow !important;">CASNR</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 882</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Complex Biosystems, PhD</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;"></td>
<td style="text-align: left; width: 15em;">STAT 801</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Biomedical Engineering, PhD</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">3 credits of graduate level statistics</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Biological Engineering, PhD</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">3 credits of graduate level statistics</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Civil Engineering, PhD; specialization in Transportation</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">STAT 801</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Finance, PhD</td>
<td style="text-align: left; background-color: yellow !important;">G</td>
<td style="text-align: left; background-color: yellow !important;">Business</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">9 credits in graduate level statistics</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>In addition to the listed courses, many graduate statistics courses are taken as electives (or graduate committee-level requirements) to ensure that students have appropriate quantitative training for their research topics and fields. Courses like Stat 850 – Computing Tools for Statistics – teach R and python “data wrangling” skills, data visualization, reproducible research, and statistical simulation. The undergraduate computing sequence, Stat 151, 251, and 351, are similarly useful across multiple disciplines, though these courses were developed for the statistics undergraduate program. Relatively quickly after the courses were created, the Digital Agriculture minor was created with the requirement that students take Stat 151 and 251. Similarly, we believe that Stat 349, Technical Skills for Statisticians, might be useful to students in Computer Science who need a technical writing course, though this potential was only identified recently, and we would need to get ACE 2 certification for the course.</p>
<p>Statistics is one of three departments participating in the cross-college Data Science majors program; even though CASNR has indicated a desire to eliminate their Data Science option, there are still students in two other colleges who are required to take multiple statisics undergraduate courses for the major. Many focus areas require statistics courses, and the Statistical Modeling option would be impossible to complete without our courses. The credibility of a Data Science degree without the participation of statisticians is questionable - statistics is the foundation of data science, and many variations of “data science is a sexy word for statistician” - Nate Silver, Joint Statistical Meetings, 2013 have been uttered at different points as the phrase “data science” caught on.</p>
<p>The proposed budget reduction plan does not account for the costs of teaching Stat 218, 380, 801, 802, and 870. Currently, some of these courses are taught by graduate TAs, who will no longer exist if the graduate program is closed. The remainder of the courses are taught by Statistics faculty, who are slated to be eliminated as well. The one remaining head of consulting cannot physically teach all of the sections of Stat 218 which are currently taught, let alone teaching 380, 801, 802, and 870 on top of the Stat 218 courses. Stat 218 is taken by approximately 20% of undergraduates at UNL and is an extremely important course for building quantitative literacy among undergraduate students. Without a plan to ensure that Stat 218 is taught by people who understand statistical pedagogy, this proposal will majorly weaken quantitative education at UNL and diminish the value of a UNL degree.</p>
</section>
</section>
<section id="undergraduate-program" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="undergraduate-program"><span class="header-section-number">5.3</span> Undergraduate Program</h2>
</section>
<section id="ms-program" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="ms-program"><span class="header-section-number">5.4</span> MS Program</h2>
</section>
<section id="ph.d.-program" class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="ph.d.-program"><span class="header-section-number">5.5</span> Ph.D.&nbsp;Program</h2>
</section>
</section>
<section id="concentrated-vs.-distributed-statistics-model" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Concentrated vs.&nbsp;Distributed Statistics Model</h1>
<p>Circa 1998, “Demand for statistics instruction at both the graduate and undergraduate level has grown since World War II, paralleling the growth in interest in statistics nationwide. The growth of statistics at UNL has been hampered both by its lack of visibility within a Department of Mathematics and Statistics and by the fact that the resources which support undergraduate instruction in statistics have been spread across so many departments.” https://math.unl.edu/statistics-history-unl/</p>
<p>“Being housed entirely in IANR clarifies the flow of resources to the department and will ensure follow-through on commitments made to the department.” - 2021 APR Report</p>
</section>
<section id="sec-future" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Planning for the Future</h1>
</section>
<section id="appendix" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> Appendix</h1>
<section id="statistics-faculty-in-the-un-system" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="statistics-faculty-in-the-un-system"><span class="header-section-number">8.1</span> Statistics Faculty in the UN System</h2>
<div class="cell">
<div id="tbl-unmc-biostats" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-unmc-biostats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Tenured and tenure-track faculty in the Biostatistics Department at UNMC
</figcaption>
<div aria-describedby="tbl-unmc-biostats-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 17%">
<col style="width: 30%">
<col style="width: 32%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Rank</th>
<th style="text-align: left;">Degree</th>
<th style="text-align: left;">Institution</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Jane Meza</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">UNL</td>
</tr>
<tr class="even">
<td style="text-align: left;">Kendra Schmid</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">UNL</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lynette Smith</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">UNL</td>
</tr>
<tr class="even">
<td style="text-align: left;">Megan Tesar</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">UNL</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Christopher S. Wichman</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">UNL</td>
</tr>
<tr class="even">
<td style="text-align: left;">Jerrod Anzalone</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Biomedical Informatics</td>
<td style="text-align: left;">UNMC</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Harlan R Sayles</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Biostatistics</td>
<td style="text-align: left;">UNMC</td>
</tr>
<tr class="even">
<td style="text-align: left;">Su Chen</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">Oklahoma State University</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hongying (Daisy) Dai</td>
<td style="text-align: left;">Professor &amp; Associate Dean of Research</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">University of Kentucky</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ran Dai</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">Univ. of Chicago</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Jianghu (James) Dong</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">Simon Fraser University</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yeongjin Gwon</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">Univ. of Connecticut</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fang Yu</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">Univ. of Connecticut</td>
</tr>
<tr class="even">
<td style="text-align: left;">Gleb Haynatzki</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Statistics and Applied Probability</td>
<td style="text-align: left;">Univ. of California</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Yunju Im</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">Univ. of Iowa</td>
</tr>
<tr class="even">
<td style="text-align: left;">Yin Zhang</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
<td style="text-align: left;">Univ. of Washington</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<div class="cell">
<div id="tbl-uno-math" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-uno-math-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Tenured and Tenure-track faculty in the Mathematics Department at University of Nebraska – Omaha
</figcaption>
<div aria-describedby="tbl-uno-math-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 29%">
<col style="width: 28%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Name</th>
<th style="text-align: left;">Rank</th>
<th style="text-align: left;">Degree</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Xiaoyue Cheng</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mahbubul Majumder</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Statistics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Lochana Palayangoda</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Statistical Science</td>
</tr>
<tr class="even">
<td style="text-align: left;">Andrew W. Swift</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">D.Sc., Operations Research</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Michael Matthews</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Mathematics Education</td>
</tr>
<tr class="even">
<td style="text-align: left;">Elizabeth Wrightsman</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Mathematics Education</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Mahboub Baccouch</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Ying Hu</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Nicole Infante</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Betty N. Love</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Valentin Matache</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Janice Rech</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Andrzej Roslanowski</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vyacheslav Rykov</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Karina Uhing</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="even">
<td style="text-align: left;">Cong Wang</td>
<td style="text-align: left;">Assistant Professor</td>
<td style="text-align: left;">Ph.D., Mathematics</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Fabio Torres Vitor</td>
<td style="text-align: left;">Associate Professor</td>
<td style="text-align: left;">Ph.D., Industrial Engineering</td>
</tr>
<tr class="even">
<td style="text-align: left;">Dora Velcsov</td>
<td style="text-align: left;">Professor</td>
<td style="text-align: left;">Ph.D., Applied Mathematics</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
</section>
<section id="sec-metric-problems" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="sec-metric-problems"><span class="header-section-number">8.2</span> Problems with the Metrics</h2>
<section id="provision-of-data-and-interactive-consultation-process" class="level3" data-number="8.2.1">
<h3 data-number="8.2.1" class="anchored" data-anchor-id="provision-of-data-and-interactive-consultation-process"><span class="header-section-number">8.2.1</span> Provision of Data and Interactive Consultation Process</h3>
<p>APC Procedures Section 2.2:</p>
<blockquote class="blockquote">
<p>Information used in the reallocation and reduction process must be made available to the budget planning participants and affected programs in a timely manner so that corrections and explanations can be made before it is released to the public.</p>
</blockquote>
<p>APC Procedures Section 2.3:</p>
<blockquote class="blockquote">
<p>The process shall ensure that administrators, faculty, students, and staff are consulted. A shared definition of the word “consultation” is essential to ensure there is ample opportunity for advice prior to recommendations being developed. Consultation is <strong>more than just giving and receiving information</strong>; it allows all parties the opportunity and the time necessary to <strong>explore and offer alternatives before administrative decisions are made</strong>. Deans, directors,2 chairs and heads shall follow procedures as stipulated in their college and unit bylaws and allow advice, input, and discussion by faculty, staff, and, to the extent appropriate, students prior to proposals being submitted by unit administrators. Such consultation is intended to give administrators, students, staff, and faculty an opportunity for substantive interactions that go beyond simply sharing information. One of the keys to the success of this process will be the manner with which the information considered at various stages is handled. In the early stages, it will be critical that those individuals responsible for developing budget reduction/reallocation proposals have an opportunity for candid discussions regarding the wide range of options open to them. Such candor is likely to occur only if participants are assured that the discussions will remain confidential. As the process moves forward and proposals are developed, it is essential that the scope of these working discussions expand to include units potentially affected by the proposals prior to public release.</p>
</blockquote>
<p>Throughout this process, units have been unable to access the data used to compute the metrics. The Statistics department has identified that some of the grant numbers used seem to be incorrect, but have not been able to get the source numbers or computations from ORI. XXX TBD – meeting tomorrow XXX Moreover, the numbers for SCH seem to be off by a factor of 10 in 2020 relative to what they should be. The department has made enquiries about these issues, but has not made any progress with the making corrections component of the process.</p>
<p>Now, the statistics department received their own metrics in June, but, without any contextual information, it is hard to interpret the values (even with the codebook). As any statistician knows, a single data point (particularly in a multi-dimensional domain) is useless; data gains power only through comparison to relevant reference distributions. The inability to consult with upper administration and to correct data and processes which are not reliable is <em>critical</em> to a fair budget process. The statistics department has been denied this chance.</p>
<p>In addition, it appears that the registrar and the graduate college have been instructed not to provide departments with any data related to the budget process. XXX Attach emails from EDAD XXX This creates an us-vs-them environment where departments proposed for elimination are frozen out of the university and not allowed to share in governance processes or counter the facts presented within the proposal. This is not how the APC process should unfold.</p>
</section>
<section id="data-quality" class="level3" data-number="8.2.2">
<h3 data-number="8.2.2" class="anchored" data-anchor-id="data-quality"><span class="header-section-number">8.2.2</span> Data Quality</h3>
<p>There are many data quality problems which were discovered after the Chancellor’s proposal but which have not been corrected. The poor data quality and documentation of the data used to assemble the quantitative metrics, and the reliance on this data in the face of identified data quality issues and systematic biases clearly indicates that the administration’s committment to metric-driven improvement is at best limited to metrics that can be easily pulled from databases with minimal quality control. However, it is difficult to verify or correct data quality issues (as is required by the APC process – departments must be given the opportunity to correct the metrics and explain their performance) when the administration has instructed departments around campus not to share data associated with the budget reduction process^[.</p>
<p>Moreover, it is clear that whoever designed the data reduction method used in this analysis had internalized the idea of variable standardization but was unfamiliar with the central goal of statistics: interpreting and understanding data within it’s real-world context. No amount of numerical sophistication will fix an underlying mismatch between the data which is available and the data needed to answer the question of interest. The questions of interest to UNL should be:</p>
<ul>
<li>“which departments perform poorly relative to their peers?” followed by</li>
<li>“which departments have relatively little impact on other departments within the university and could thus be eliminated without cascading failures?”</li>
</ul>
<p>Instead, the analysis focuses on identifying departments which are different from other departments at UNL across a variety of metrics intended for discipline-specific comparisons. It is reasonable, for instance, to compare the per-capita grant funding brought in by one Statistics department to the per-capita grant funding brought in by another Statistics department at a different university. It would even be reasonable to compute this quantity for many departments across the country and to assemble a distribution of values or rank the department of interest compared to its peers.</p>
<p>However, apart from the SRI metric, which will be addressed separately, this is not what has been done, and it demonstrates a fundamental lack of understanding of the concept of a population:</p>
<blockquote class="blockquote">
<p>a set of similar items or events which is of interest for some question or experiment. A statistical population can be a group of existing objects or a hypothetical and potentially infinite group of objects conceived as a generalization from experience. – <a href="https://en.wikipedia.org/wiki/Statistical_population">Wikipedia, definition of “statistical population”</a></p>
</blockquote>
<p>That is, whoever created the statistical analysis methodology did not account for the fact that all departments in the analysis are not similar. For instance, instructional metrics are computed without regard to whether a department offers service courses at the undergraduate or graduate level (and how many of those courses are offered or required by other departments). This leads to nonsensical comparisons, such as comparing the EDAD department, which is graduate-only and doesn’t have service courses, to the English department, which teaches courses at all levels and has many service courses and electives as part of its portfolio. Ultimately, it is not reasonable to expect that the EDAD department would offer undergraduate courses in educational administration, a field that requires a graduate degree (for good reason). Thus, it is also not reasonable to explicitly compare these departments and their constitutent programs and course offerings. As graduate students are only a fraction of the students on campus, it is not reasonable to compare SCH generated at the graduate level in one department to SCH generated at both undergraduate and graduate levels in others.</p>
<p>This problem persists across research funding. SRI, a measure created by Academic Analytics, is perhaps the exception to this rule, but only in that it accounts for discipline-specific norms with respect to research outputs. Unfortunately, UNL’s administration used a custom SRI value which compares UNL departments to public AAU institutions, and then took that value and used it to compare UNL departments to each other across discipline boundaries. <a href="#sec-metric-sri-problems" class="quarto-xref">Section&nbsp;8.2.3</a> has more detail on SRI, but the broader issue of comparing numbers across departments which are not fundamentally similar is pervasive throughout both the research and instructional metrics. For instance, grants in English are not similarly sized to those in Physics and Astronomy, Agronomy, or Engineering, because English professors typically do not require large amounts of expensive equipment to complete their research. As a result, it does not make sense to group these departments into the same distribution, which is what the analysis implicitly does by calculating a z-score for each variable.</p>
</section>
<section id="sec-metric-sri-problems" class="level3" data-number="8.2.3">
<h3 data-number="8.2.3" class="anchored" data-anchor-id="sec-metric-sri-problems"><span class="header-section-number">8.2.3</span> Use of Scholarly Research Index</h3>
<section id="combination-of-multiple-sri-values" class="level4" data-number="8.2.3.1">
<h4 data-number="8.2.3.1" class="anchored" data-anchor-id="combination-of-multiple-sri-values"><span class="header-section-number">8.2.3.1</span> Combination of Multiple SRI Values</h4>
<p>Some departments have multiple SRI scores generated by Academic Analytics.</p>
<p>In some disciplines, departments might be book-focused or article focused, or might have members with different focuses. Examples in <a href="#fig-sri-multi-values" class="quarto-xref">Figure&nbsp;4</a> include Communication Studies, Sociology, Advertising, Landscape Architecture, Interior Design, and Broadcasting, among others.</p>
<p>Another reason a department might have multiple SRI scores is that it is composed of multiple different disciplines. Examples in <a href="#fig-sri-multi-values" class="quarto-xref">Figure&nbsp;4</a> include Agronomy &amp; Horticulture, Earth and Atmospheric Sciences, the School of Computing, Physics and Astronomy, and Electrical and Computer Engineering.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-sri-multi-values" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-sri-multi-values-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="2025-Stat-APC-report_files/figure-html/fig-sri-multi-values-1.png" class="img-fluid figure-img" width="864">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-sri-multi-values-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Some Units at UNL have multiple SRI values, either because different departments focus on books or articles within the discipline, or because departments have faculty from multiple disciplines.
</figcaption>
</figure>
</div>
</div>
</div>
<p>When there are two different norms within a discipline, SRI scores were reportedly averaged to create a mean SRI value. This is incorrect - because these values have different distributions, averaging them does not produce a meaningful result with a valid comparison distribution. A more reasonable combination method would be to evaluate each score to get a distributional measure (quantile, percentile, rank), and then to take the maximum of that measure - the departments peers would know what the focus area of the department is and which focus would be more appropriate.</p>
<p>In the case of a hybrid department, the scores were also averaged. This approach is also not reasonable, as SRI distributions are not the same across disciplines. It is critically important to go through the distribution, calculating a rank, percentile, or quantile rather than using averages. Then, if the goal is to assess the department’s performance, two reasonable approaches could be used to aggregate the percentile or quantile scores:</p>
<ul>
<li>take a weighted average of the percentile or quantile scores, with weight determined by the composition of the department.</li>
<li>take the maximum of the percentile or quantile scores in order to assess the overall opinion of the work done within the department in a community of peers. This makes more sense if the goal is to model how other people see UNL’s departments, as people tend to remember outstanding work in the field more than they remember or consider average work.</li>
</ul>
</section>
</section>
<section id="problems-with-overall-z-scores" class="level3" data-number="8.2.4">
<h3 data-number="8.2.4" class="anchored" data-anchor-id="problems-with-overall-z-scores"><span class="header-section-number">8.2.4</span> Problems with Overall Z-scores</h3>
<p>The UNL research z-score is created by standardizing each input measure with respect to all departments on campus before computing an unweighted average of each component z-score to form a single research index for each department. This is fundamentally problematic, as the SRI measure used by academic analytics not only incorporates many of the components used (federal expenditures, awards, books, citations), but also because the discipline-specific weightings are intended to allow for comparison within-disciplines, and they are being used here as a cross-discipline comparison. That is, the z-score method indicates a fundamental understanding of both the Academic Analytics (and AAU) metrics and the appropriate use of statistical methods. It would be quite reasonable to use the SRI percentile for each department, which compares the department’s research reputation relative to other departments in the same area, compute a normal quantile from the percentile, and then use that z-score to represent the department’s research reputation. This would also allow for use when averaging z-scores from other research metrics to produce a single research summary; which is a practice that is reductive and not particularly effective, but is also not definitively wrong.</p>
</section>
<section id="custom-unl-research-metrics" class="level3" data-number="8.2.5">
<h3 data-number="8.2.5" class="anchored" data-anchor-id="custom-unl-research-metrics"><span class="header-section-number">8.2.5</span> Custom UNL Research Metrics</h3>
<p>Moving past SRI, however, it is clear that there was some attempt to create a secondary SRI-like index with UNL data that accounts for some of the holes in Academic Analytics. There are many well known issues with Academic Analytics: only some journals are indexed, only NSF and NIH grants count for federal funding, excluding USDA, NIJ, DOE, NIST, and other sources of federally funded grant money, and only certain discipline-specific awards are counted as prestigious.</p>
<p>However, while UNL insists they did not weight the metrics used (as if that is an indication of unbiasedness), the number of variables measuring similar dimensions of research productivity certainly create an implicit weighting.</p>
<p>There are three different indicators of grant budget contributions. It’s unclear why the <code>total_sponsored_awards_inc_nuf_rsch_pub_serv_teach_avg_awards_budget</code> indicator was divided by total state appropriated budget, but the numbers for Statistics grants do not seem to be in the right ballpark. For instance, if we multiply the 0.362 value for statistics (before it is converted to a z-score) by the state permanent budget from 2025-26, we get 4.8118524^{5}. One PI in the department brought in 1.2 million dollars in grant money during the 2020-2024 period, so we can .</p>
<p><code>research_awards_growth_inc_nuf_fy20_fy24</code> looks at the percentage of growth of grant money attributable to the unit. Given that the grant totals are unreliable, it isn’t surprising that this percentage is also off, but the fact that the statistics department number is -455843.15 suggests that this isn’t a percentage at all and that there are some fundamentally problematic calculation errors (or the codebook is wrong, which also seems possible, particularly given the duplication of the entries for the last two research metrics).</p>
<p><code>p1_expenditures_normalized</code> seems to include some of the information in <code>total_sponsored_awards_inc_nuf_rsch_pub_serv_teach_avg_awards_budget</code>, which would double-count the awards from NSF and NIH indexed by Academic Analytics (in addition to counting them a third fractional time via SRI). However, again, these numbers do not seem to be calculated as described. We cannot find any evidence of accounting for faculty members with secondary appointments in the department, nor can we make the numbers generated for Statistics make sense given our self-reported data.</p>
<p><code>awards_normalized</code> would be directly reported by Academic Analytics and is already accounted for in the SRI metric. It is clear that the codebook was not checked for correctness by administration, either, given that the normalization is reported twice - it is unclear whether we to calculate this by dividing by the squared TT-FTE metric or by just the number of TT FTEs in the department. This metric is likely to be highly influenced by time in role and years since Ph.D., disadvantaging departments which are relatively young compared to those with a higher percentage of full professors. It should also be noted that not all professional organization awards are indexed by Academic Analytics, which represents a systematic bias when this metric is used to compare across departments and disciplines.</p>
<p><code>books_normalized</code> is again Academic Analytics data that has been factored into SRI already. This data is publisher reported, and not always correct (one member of our department had the 2nd edition of his book reported as having the year of the first edition, so it just doesn’t count). As some disciplines do not preference books and instead publish articles or conference papers, using this metric to compare across disciplines (via z-score calculation) is absolutely preferencing book-focused departments.</p>
<p><code>citations_normalized</code> has the same description as <code>books_normalized</code>; however, the numbers are not the same, so we presume this also uses Academic Analytics data for citations. Going into Academic Analytics, the citation data appears to include citations from journals which Acad Analytics indexes to journals which Acad. Analytics indexes, where the journal article was published between 2020 and 2023 and the citation occurred between 2020 and 2023. This is again a highly discipline-dependent metric – in fast-moving disciplines, such as Computer Science, a good paper will be cited many times within the first six months, while in slower disciplines, a paper might not be cited until 3 years later.</p>
<p>What is not included in UNL’s custom metrics is just as telling as what is included: they do NOT include any measure of articles published (beyond citations) and they don’t include any measures of conference papers published. This has the effect of biasing the metrics toward book-centric disciplines at the expense of article centric disciplines. When combined with the fact that grant award totals vary widely between disciplines (for instance, Statistics doesn’t require any lab equipment or supplies, so grants tend to fund students, travel, and summer salary), the metrics assembled by UNL are fundamentally unsuitable for cross-discipline comparisons. Pitting departments against each other using these metrics could be the result of a lack of understanding of statistics, or it could be that the metrics were assembled to produce a specific set of acceptable outcomes. In either case, however, it does not reflect particularly well on the UNL administration.</p>
</section>
</section>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p>As we have tried to do when assembling this report – it is not an easy or efficient process.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>This is only a partial list assembled from members of the R User Group on campus and other collaborators – there may well be others.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>Not all identified issues are outlined in that section, because our priority is in preserving our programs and department rather than engaging in pedantry. In addition, even reports posted on the internet have an effective size limit; we have opted to save paper and electrons and only detail the worst offenses in the data analysis which resulted in our unit being targeted for elimination.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The statistics department is typically on the main campus and the biostatistics department is typically located within the medical school organizational structure.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>R1 Universities offering non-medical undergraduate degrees without a Statistics or Data Science department: Boston College, CUNY Graduate School and University Center, Drexel University, Florida International University, University of Southern Mississippi, Brown University, Tulane University of Louisiana, University of Miami.<br>
Medical institutions with only a biostatistics presence on campus: Baylor College of Medicine, Medical University of South Carolina, University of California San Francisco, University of Nebraska Medical Center, University of Tennessee Health Science Center, University of Texas Health Science Center at Houston, University of Texas Health Science Center at San Antonio, University of Texas Southwestern Medical Center<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>AAU universities without a statistics or data science department: Brown University, Tulane University of Louisiana, University of Miami<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p> It will take some work to undo the damage from the public proposal to eliminate the program, but we believe the economic conditions are sufficient to make this a worthwhile investment for UNL. <a href="#sec-future" class="quarto-xref">Section&nbsp;7</a> discusses several options for the future of the program which could mitigate this obstacle and could significantly improve enrollment in the program. <a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>