<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Appendix C — A Statistical Commentary on the Metric Inputs and Calculations – Statistics: An Essential Department for a Modern R1 University</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./app-engagement-ori.html" rel="next">
<link href="./app-analysis-issues.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e1615be2c113e74b0a69323fdd91d2e9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./app-faculty-system.html">Appendices</a></li><li class="breadcrumb-item"><a href="./app-metrics-analysis.html"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A Statistical Commentary on the Metric Inputs and Calculations</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics: An Essential Department for a Modern R1 University</a> 
        <div class="sidebar-tools-main">
    <a href="./Statistics--An-Essential-Department-for-a-Modern-R1-University.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Executive Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unl-stats-dept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The UNL Statistics Department</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metrics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./peer-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Peer Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./program-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Program Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./centralized.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Centralized vs.&nbsp;Distributed Statistics Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluating-budget.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Evaluating the Budget Proposal Realistically</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./future.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Planning for the Future</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-faculty-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Statistics Faculty in the UN System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-analysis-issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Problems with the Analysis of Research and Teaching Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-metrics-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A Statistical Commentary on the Metric Inputs and Calculations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-engagement-ori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Attempts to Document Metrics and Data Issues</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2025-Stat-APC-report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Report to APC</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#general-descriptors" id="toc-general-descriptors" class="nav-link active" data-scroll-target="#general-descriptors"><span class="header-section-number">C.1</span> General Descriptors</a>
  <ul class="collapse">
  <li><a href="#identifiers" id="toc-identifiers" class="nav-link" data-scroll-target="#identifiers"><span class="header-section-number">C.1.1</span> Identifiers</a></li>
  <li><a href="#budget" id="toc-budget" class="nav-link" data-scroll-target="#budget"><span class="header-section-number">C.1.2</span> Budget</a></li>
  <li><a href="#appointments-headcount" id="toc-appointments-headcount" class="nav-link" data-scroll-target="#appointments-headcount"><span class="header-section-number">C.1.3</span> Appointments &amp; Headcount</a></li>
  </ul></li>
  <li><a href="#research" id="toc-research" class="nav-link" data-scroll-target="#research"><span class="header-section-number">C.2</span> Research</a>
  <ul class="collapse">
  <li><a href="#sri" id="toc-sri" class="nav-link" data-scroll-target="#sri"><span class="header-section-number">C.2.1</span> SRI</a></li>
  <li><a href="#awards" id="toc-awards" class="nav-link" data-scroll-target="#awards"><span class="header-section-number">C.2.2</span> Awards</a></li>
  <li><a href="#books" id="toc-books" class="nav-link" data-scroll-target="#books"><span class="header-section-number">C.2.3</span> Books</a></li>
  <li><a href="#citations" id="toc-citations" class="nav-link" data-scroll-target="#citations"><span class="header-section-number">C.2.4</span> Citations</a></li>
  <li><a href="#research-awards-inc-nuf" id="toc-research-awards-inc-nuf" class="nav-link" data-scroll-target="#research-awards-inc-nuf"><span class="header-section-number">C.2.5</span> Research Awards Inc NUF</a></li>
  <li><a href="#total-sponsored-awards-inc-nuf-rsch-pub-serv-teach" id="toc-total-sponsored-awards-inc-nuf-rsch-pub-serv-teach" class="nav-link" data-scroll-target="#total-sponsored-awards-inc-nuf-rsch-pub-serv-teach"><span class="header-section-number">C.2.6</span> Total Sponsored Awards Inc NUF RSCH PUB SERV TEACH</a></li>
  <li><a href="#p1-expenditures" id="toc-p1-expenditures" class="nav-link" data-scroll-target="#p1-expenditures"><span class="header-section-number">C.2.7</span> P1 Expenditures</a></li>
  </ul></li>
  <li><a href="#teaching" id="toc-teaching" class="nav-link" data-scroll-target="#teaching"><span class="header-section-number">C.3</span> Teaching</a>
  <ul class="collapse">
  <li><a href="#sch-tuition" id="toc-sch-tuition" class="nav-link" data-scroll-target="#sch-tuition"><span class="header-section-number">C.3.1</span> SCH &amp; Tuition</a></li>
  <li><a href="#ratios" id="toc-ratios" class="nav-link" data-scroll-target="#ratios"><span class="header-section-number">C.3.2</span> Ratios</a></li>
  </ul></li>
  <li><a href="#instructional-z-scores-in-institutional-metrics" id="toc-instructional-z-scores-in-institutional-metrics" class="nav-link" data-scroll-target="#instructional-z-scores-in-institutional-metrics"><span class="header-section-number">C.4</span> Instructional Z-scores in Institutional Metrics</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./app-faculty-system.html">Appendices</a></li><li class="breadcrumb-item"><a href="./app-metrics-analysis.html"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A Statistical Commentary on the Metric Inputs and Calculations</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-codebook-analysis" class="quarto-section-identifier">Appendix C — A Statistical Commentary on the Metric Inputs and Calculations</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>This section contains a reorganized version of the code book provided to departments. The code book describes how the various measures used to evaluate departments were assembled and calculated. Measure definitions have been rearranged to form coherent categories (the <a href="documentation/Measure Definitions 5_16_25.pdf">original document</a> is difficult to follow in part because derivative measures are sometimes not close to their inputs).</p>
<div id="wrn-demo" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.1
</div>
</div>
<div class="callout-body-container callout-body">
<p>Comments on the validity of various measures are contained in highlighted blocks to differentiate them from the official metric definitions. In most cases, these comments are focused on the problems discovered by the Statistics department, however, it seems likely that most issues cut across many departments.</p>
</div>
</div>
<section id="general-descriptors" class="level2" data-number="C.1">
<h2 data-number="C.1" class="anchored" data-anchor-id="general-descriptors"><span class="header-section-number">C.1</span> General Descriptors</h2>
<section id="identifiers" class="level3" data-number="C.1.1">
<h3 data-number="C.1.1" class="anchored" data-anchor-id="identifiers"><span class="header-section-number">C.1.1</span> Identifiers</h3>
<p>1.1.1 <code>lowest_level_key</code> Numeric key of lowest level unit.</p>
<p>1.1.2 <code>lowest_level_short_name</code> Short name of lowest level unit.</p>
<p>1.1.3 <code>lowest_level_name</code> Full name of lowest level unit.</p>
<p>1.2 <code>vcvp</code> Vice Chancellor that unit belongs to: EVC or IANR.</p>
<p>1.3 <code>college</code> College for units that belong to a college.</p>
<p>1.4 <code>department</code> Department for units that belong to an academic department.</p>
<p>1.5 <code>has_finance_org</code> Indicator variable: 1 if the unit has a financial org, 0 otherwise.</p>
<p>1.6 <code>has_acad_org</code> Indicator variable: 1 if the unit has a academic org, 0 otherwise.</p>
<p>1.7 <code>has_hr_org</code> Indicator variable: 1 if the unit has a HR org, 0 otherwise.</p>
<p>1.8 <code>acad_end_year</code> Academic ending year. E.g., 2024 for 2023-2024 AY.</p>
</section>
<section id="budget" class="level3" data-number="C.1.2">
<h3 data-number="C.1.2" class="anchored" data-anchor-id="budget"><span class="header-section-number">C.1.2</span> Budget</h3>
<p>1.17 <code>original_sa_budget</code> Original state-aided budget (total). Original budget includes all permanent funding as of July 1. Temporary funding and cash carryforwards are excluded. This also shows up at Budget in final metrics.</p>
<p>1.18 <code>original_sa_budget_gse</code> Original state-aided budget with General State-Aided fund subtype.</p>
<p>1.19 <code>original_sa_budget_dt</code> Original state-aided budget with Differential Tuition fund subtype.</p>
<p>1.20 <code>original_sa_budget_poe</code> Original state-aided budget with Programs of Excellence fund subtype.</p>
<p>1.21 <code>original_sa_budget_other</code> Original state-aided budget with other fund subtypes, including Distance Education, Facilities &amp; Administrative, Tobacco and etc.</p>
<hr>
<p>1.32 <code>teaching_outlay</code> Appointment budgeted salary * appointment teaching apportionment (%) summed for unit.</p>
<p>1.95 <code>instruction_budget</code> Original state-aided budget multiplied by teaching fte as a percentage of total fte for unit.</p>
<p>1.33 <code>research_outlay</code> Appointment budgeted salary * appointment research apportionment (%) summed for unit.</p>
<p>1.96 <code>research_budget</code> Original state-aided budget multiplied by research fte as a percentage of total fte for unit.</p>
<p>1.34 <code>service_outlay</code> Appointment budgeted salary * appointment service apportionment (%) summed for unit.</p>
<p>1.97 <code>service_budget</code> Original state-aided budget multiplied by service fte as a percentage of total fte for unit.</p>
<p>1.35 <code>extension_outlay</code> Appointment budgeted salary * appointment extension apportionment (%) summed for unit.</p>
<p>1.98 <code>extension_budget</code> Original state-aided budget multiplied by extension fte as a percentage of total fte for unit.</p>
<p>1.36 <code>admin_outlay</code> Appointment budgeted salary * appointment administration apportionment (%) summed for unit.</p>
<p>1.99 <code>admin_budget</code> Original state-aided budget multiplied by admin fte as a percentage of total fte for unit.</p>
<hr>
<p>1.72 <code>budget_from_evc_file_state_appropriated_budget</code> State-aided budget.</p>
<p>1.991 <code>total_realizable_base_tuition_less_budget</code> This is estimated by <code>total_realizable_base_tuition</code> (1.49) less original state-aided budget, apportioned for <code>percent_teaching</code> (also <code>instruction_budget</code>, see 1.95 above).</p>
</section>
<section id="appointments-headcount" class="level3" data-number="C.1.3">
<h3 data-number="C.1.3" class="anchored" data-anchor-id="appointments-headcount"><span class="header-section-number">C.1.3</span> Appointments &amp; Headcount</h3>
<div id="wrn-apportionment" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.2: Apportionment problem: Partial-year data not included
</div>
</div>
<div class="callout-body-container callout-body">
<p>This information seems to have been assembled from a source that does not take into account mid-year hires. Susan Vanderplas started at UNL in January 2020 and has a 20% Extension appointment, so for the 2019-2020 academic year, she would have been paid for between 5 and 6 months, depending on how 9-month contracts are handled. The Details tab of the metrics show a 0.0 percent extension FTE appointment for 2020, with subsequent years matching the 0.200 in the appointment.</p>
</div>
</div>
<div id="wrn-headcount" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.3: Headcount problem: Lack of Public Data Confirmation
</div>
</div>
<div class="callout-body-container callout-body">
<p>There is relatively little clarity to be had about how apportionment was counted in these metrics. The only public data available to us is the <a href="https://nebraska.edu/offices-policies/business-finance/budget-and-planning">UN System Budget &amp; Salary Information</a>, which contains spreadsheets (“Budgeted Employees as of…”) and PDF documents (“University of Nebraska Salary Information”). Historical data is available.</p>
<p>The salary <strong>spreadsheets</strong> appear to show the cost distribution for a position (e.g.&nbsp;where the money comes from), but only when the position is more complicated than just having funding from multiple departments indicating a partial appointment, as shown in <a href="#fig-salary-sources" class="quarto-xref">Figure&nbsp;<span>C.1</span></a>. This happens most frequently when someone has administrative responsibilities in addition to standard research or teaching responsibilities.</p>
<div id="fig-salary-sources" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-salary-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/salary-position-info.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;C.1: An example of someone with multiple salary sources – a fellowship, a normal professor salary, and a director position that comes from non-state-aided funds."><img src="images/salary-position-info.png" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-salary-sources-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;C.1: An example of someone with multiple salary sources – a fellowship, a normal professor salary, and a director position that comes from non-state-aided funds.
</figcaption>
</figure>
</div>
<p>The <strong>PDF tables of salary information</strong> show a set of information that sometimes matches, but sometimes does not.</p>
<div id="fig-position-information" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-position-information-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/roster-position-info.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;C.2: "><img src="images/roster-position-info.png" id="fig-position-information" class="img-fluid figure-img"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig quarto-uncaptioned" id="fig-position-information-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;C.2
</figcaption>
</figure>
</div>
<p>It seems <em>likely</em> that the proportions in the FTE column (next from the last) of <a href="#fig-position-information" class="quarto-xref">Figure&nbsp;<span>C.2</span></a> would represent the apportionment, but that doesn’t seem to always match what the individual understood their apportionment to be. When apportionments change, the university is supposed to provide written notice of the new contractual arrangement and it should be signed. In at least one case in Statistics, we could not find paperwork to match the effort allocation reported in the PDF FTE column. More importantly, however, it seems that the FTE column in the PDF doesn’t match the information assembled by the office of research and innovation to allocate research productivity to departments.</p>
<p>What this boils down to is that the Statistics department cannot get administration to explain why their numbers for people (and fractional people) in the department don’t match the administrations numbers. That is, we don’t even count department members the same way! Note that the individuals in question are longstanding members of the department who have e.g.&nbsp;taught Statistics courses, advised students, served on hiring committees - this issue spans most of the decade of research productivity metrics, and as a result, the impact cannot be assumed to be insignificant.</p>
<p>Perhaps if we could get data which matches our paperwork (if those columns exist in a database) and compare the different metrics, it would be possible to agree on a standard methodology for apportioning research productivity. These decisions happen in every data analysis, but we teach our students to (1) document the options which existed, (2) justify their selection of a particular option, and (3) conduct a sensitivity analysis after the analysis to see how much the results change based on the selection of a different way to measure a variable. The Office of Research and Innovation apparently did not do any of these things – and they also will not provide us with the data to validate their numbers ourselves.</p>
</div>
</div>
<p>1.9 <code>appointment_apportionment_fte</code> Total apportioned FTE across all appointments.</p>
<p>1.10 <code>appointment_apportionment_percent_teaching_fte</code> Sum of faculty teaching apportionment by appointment times FTE by unit.</p>
<p>1.11 <code>appointment_apportionment_percent_research_fte</code> Sum of faculty research apportionment by appointment times FTE by unit.</p>
<p>1.12 <code>appointment_apportionment_percent_service_fte</code> Sum of faculty service apportionment by appointment times FTE by unit.</p>
<p>1.13 <code>appointment_apportionment_percent_extension_fte</code> Sum of faculty extension apportionment by appointment times FTE by unit.</p>
<p>1.14 <code>appointment_apportionment_percent_admin_fte</code> Sum of faculty admin apportionment by appointment times FTE by unit.</p>
<p>1.15 <code>total_instructor_fte</code> Sum of <code>appointment_apportionment_fte</code> by unit.</p>
<div id="wrn-instructor-fte" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.4: Instructor FTE Problem
</div>
</div>
<div class="callout-body-container callout-body">
<p>This metric definition doesn’t make any sense. There is a single column of <code>appointment_apportionment_fte</code> for each unit.</p>
<p>If instead, this is intended to mean the sum of <code>appointment_apportionment_percent_teaching_fte</code> through <code>appointment_apportionment_percent_admin_fte</code>, it doesn’t make sense either, because those values should sum to <code>appointment_apportionment_fte</code> instead.</p>
<div class="cell">
<div id="tbl-instructor-fte" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-instructor-fte-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;C.1: Top and Bottom 15 departments by ratio of total instructor FTE to appointment apportionment FTE. Only departments with nonzero total instructor FTE are included.
</figcaption>
<div aria-describedby="tbl-instructor-fte-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 7%">
<col style="width: 84%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Rank</th>
<th style="text-align: left;">Dept</th>
<th style="text-align: right;">Ratio</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">1</td>
<td style="text-align: left;">Agricultural Leadership, Education and Communication</td>
<td style="text-align: right;">8.802</td>
</tr>
<tr class="even">
<td style="text-align: right;">2</td>
<td style="text-align: left;">Glenn Korff School of Music</td>
<td style="text-align: right;">8.375</td>
</tr>
<tr class="odd">
<td style="text-align: right;">3</td>
<td style="text-align: left;">Broadcasting</td>
<td style="text-align: right;">6.091</td>
</tr>
<tr class="even">
<td style="text-align: right;">4</td>
<td style="text-align: left;">Program in English as a Second Language</td>
<td style="text-align: right;">6.000</td>
</tr>
<tr class="odd">
<td style="text-align: right;">5</td>
<td style="text-align: left;">School of Global Integrative Studies</td>
<td style="text-align: right;">5.729</td>
</tr>
<tr class="even">
<td style="text-align: right;">6</td>
<td style="text-align: left;">Textiles, Merchandising &amp; Fashion Design</td>
<td style="text-align: right;">5.479</td>
</tr>
<tr class="odd">
<td style="text-align: right;">7</td>
<td style="text-align: left;">Johnny Carson School of Theatre &amp; Film</td>
<td style="text-align: right;">5.204</td>
</tr>
<tr class="even">
<td style="text-align: right;">8</td>
<td style="text-align: left;">Advertising &amp; Public Relations</td>
<td style="text-align: right;">4.915</td>
</tr>
<tr class="odd">
<td style="text-align: right;">9</td>
<td style="text-align: left;">School of Biological Sciences</td>
<td style="text-align: right;">4.698</td>
</tr>
<tr class="even">
<td style="text-align: right;">10</td>
<td style="text-align: left;">School of Art, Art History &amp; Design</td>
<td style="text-align: right;">4.548</td>
</tr>
<tr class="odd">
<td style="text-align: right;">11</td>
<td style="text-align: left;">Journalism</td>
<td style="text-align: right;">4.450</td>
</tr>
<tr class="even">
<td style="text-align: right;">12</td>
<td style="text-align: left;">Durham School of Architectural Engineering &amp; Construction</td>
<td style="text-align: right;">4.323</td>
</tr>
<tr class="odd">
<td style="text-align: right;">13</td>
<td style="text-align: left;">Modern Languages &amp; Literatures</td>
<td style="text-align: right;">4.275</td>
</tr>
<tr class="even">
<td style="text-align: right;">14</td>
<td style="text-align: left;">Educational Administration</td>
<td style="text-align: right;">4.187</td>
</tr>
<tr class="odd">
<td style="text-align: right;">15</td>
<td style="text-align: left;">Classics &amp; Religious Studies</td>
<td style="text-align: right;">4.140</td>
</tr>
<tr class="even">
<td style="text-align: right;"></td>
<td style="text-align: left;">…</td>
<td style="text-align: right;"></td>
</tr>
<tr class="odd">
<td style="text-align: right;">49</td>
<td style="text-align: left;">Earth and Atmospheric Sciences</td>
<td style="text-align: right;">1.847</td>
</tr>
<tr class="even">
<td style="text-align: right;">50</td>
<td style="text-align: left;">Mathematics</td>
<td style="text-align: right;">1.844</td>
</tr>
<tr class="odd">
<td style="text-align: right;">51</td>
<td style="text-align: left;">School of Veterinary Medicine and Biomedical Sciences</td>
<td style="text-align: right;">1.797</td>
</tr>
<tr class="even">
<td style="text-align: right;">52</td>
<td style="text-align: left;">Chemistry</td>
<td style="text-align: right;">1.658</td>
</tr>
<tr class="odd">
<td style="text-align: right;">53</td>
<td style="text-align: left;">Statistics</td>
<td style="text-align: right;">1.533</td>
</tr>
<tr class="even">
<td style="text-align: right;">54</td>
<td style="text-align: left;">Animal Science</td>
<td style="text-align: right;">1.533</td>
</tr>
<tr class="odd">
<td style="text-align: right;">55</td>
<td style="text-align: left;">Entomology</td>
<td style="text-align: right;">1.484</td>
</tr>
<tr class="even">
<td style="text-align: right;">56</td>
<td style="text-align: left;">Biochemistry</td>
<td style="text-align: right;">1.480</td>
</tr>
<tr class="odd">
<td style="text-align: right;">57</td>
<td style="text-align: left;">Women’s &amp; Gender Studies</td>
<td style="text-align: right;">1.441</td>
</tr>
<tr class="even">
<td style="text-align: right;">58</td>
<td style="text-align: left;">Agricultural Economics</td>
<td style="text-align: right;">1.236</td>
</tr>
<tr class="odd">
<td style="text-align: right;">59</td>
<td style="text-align: left;">Physics &amp; Astronomy</td>
<td style="text-align: right;">0.821</td>
</tr>
<tr class="even">
<td style="text-align: right;">60</td>
<td style="text-align: left;">Plant Pathology</td>
<td style="text-align: right;">0.537</td>
</tr>
<tr class="odd">
<td style="text-align: right;">61</td>
<td style="text-align: left;">School of Natural Resources</td>
<td style="text-align: right;">0.390</td>
</tr>
<tr class="even">
<td style="text-align: right;">62</td>
<td style="text-align: left;">Center on Children Families &amp; the Law</td>
<td style="text-align: right;">0.269</td>
</tr>
<tr class="odd">
<td style="text-align: right;">63</td>
<td style="text-align: left;">School of Veterinary Medicine and Biomedical Sciences</td>
<td style="text-align: right;">0.183</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>It is not clear what this is measuring, but departments which seem to have more extension-focused non-teaching appointments seem to be lower on the list. Departments which have more professors of practice seem to be higher on the list.</p>
</div>
</div>
<hr>
<p>1.37 <code>percent_teaching</code> <code>sum(appointment_apportionment_percent_teaching_fte) / sum(appointment_apportionment_fte)</code> for unit. This is set to zero when there is no teaching apportionment.</p>
<p>1.38 <code>percent_research</code> <code>sum(appointment_apportionment_percent_research_fte) / sum(appointment_apportionment_fte)</code> for unit. This is set to zero when there is no research apportionment.</p>
<p>1.39 <code>percent_service</code> <code>sum(appointment_apportionment_percent_service_fte) / sum(appointment_apportionment_fte)</code> for unit. This is set to zero when there is no service apportionment.</p>
<p>1.40 <code>percent_extension</code> <code>sum(appointment_apportionment_percent_extension_fte) / sum(appointment_apportionment_fte)</code> for unit. This is set to zero when there is no extension apportionment.</p>
<p>1.41 <code>percent_admin</code> <code>sum(appointment_apportionment_percent_admin_fte) / sum(appointment_apportionment_fte) for unit</code>. This is set to zero when there is no admin apportionment.</p>
<hr>
<p>1.66 <code>t_tt_headcount_2014_2023_avg</code> The average of the full-time employees with faculty status who are on the tenure track or tenured as reported to the National Center for Education Statistics IPEDS Data Center. Headcounts were assigned to departments using the HR tenure org unit.</p>
<div id="wrn-research-ntt" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.5: Research Contributions by NTT Professors
</div>
</div>
<div class="callout-body-container callout-body">
<p>Our department had a long-time Professor of Practice, Kathy Hanford, who had a research and teaching apportionment and was the professor in charge of the SC3L. She retired at the end of 2023, so she <em>should</em> be included in most of our metrics, but isn’t because she was not tenure track. She does, however, count against our budget. Her research productivity, grant productivity, and collaborations across campus should count when evaluating the department’s importance within UNL, but they do not currently. The focus on tenure track positions to the exclusion of all others is incredibly damaging, particularly when a department is as small as we are. If Kathy had been hired more recently, the position would have likely been tenure track (and when the position was posted to find her replacement, it was posted as tenure track). The current head of SC3L, Dr.&nbsp;Reka Howard, is an associate professor in the department.</p>
</div>
</div>
<div id="wrn-per-capita" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.6: Per-capita measures
</div>
</div>
<div class="callout-body-container callout-body">
<p>Different denominators are used to measure per-capita productivity in teaching and research across the analysis. In some cases, these are reasonable (e.g.&nbsp;it is reasonable to use total teaching FTE to calculate SCH per FTE values), but in others, these differences seem to arise primarily from the desire to conform to Academic Analytics or AAU metrics. While it is understandable that our administration wants to use metrics from other organizations rather than develop their own (this document exists because they don’t have the statistics training to design effective measures of variables of interest), this leads to significant and strange differences in productivity measures. It would be a far more coherent overall <strong>analysis</strong> if admin had used a single set of FTE measures consistently, rather than switching these measures up for different variables.</p>
</div>
</div>
<p>1.50 <code>vsip_eligible_n</code> The count of VSIP-eligible tenure-track faculty as of summer, 2026. If this follows past methodology, this is the count of faculty who:</p>
<ul>
<li>are tenured</li>
<li>are 62 years of age as of their eligibility date: June 30, 2026 (FY contract length) or August 27, 2026 (AY contract length)</li>
<li>have 10 years of service as of their eligibility date</li>
</ul>
<p>This is an estimate. At present, it is impossible to determine how many would meet the final criterion: No accepted retirement contract/letter in place.</p>
<p>1.51 <code>vsip_eligible_pct</code> The proportion of the unit’s tenure-track faculty who would be eligible for VSIP in summer, 2026.</p>
<div id="wrn-vsip" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.7: VSIP percentage
</div>
</div>
<div class="callout-body-container callout-body">
<p>Tracking this makes sense, but it’s unclear how this metric might factor into a final decision to combine or eliminate departments. Is it better to eliminate a department with a high percentage of VSIP eligible faculty, since the department might not be able to function after VSIP anyways? Or would it be better to eliminate a department without VSIP eligible faculty, since those savings won’t be double-counted by both VSIP and the elimination of the department, as the current analysis seems to do for the departments which will be combined (ALEC and Agricultural Economics, Entomology and Plant Pathology).</p>
</div>
</div>
</section>
</section>
<section id="research" class="level2" data-number="C.2">
<h2 data-number="C.2" class="anchored" data-anchor-id="research"><span class="header-section-number">C.2</span> Research</h2>
<div id="wrn-z-scores-research" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.8: Z-scores for research
</div>
</div>
<div class="callout-body-container callout-body">
<p>There are so many problems with the constitutent components of the research metrics (even before they are standardized) that the resulting research average z-score is utterly unreliable and not useful for cross-department comparison.</p>
<p>Fundamentally, as statisticians, if you take the average of standardized garbage, you still get garbage. Garbage in, garbage out, or GIGO, is a fairly standard abbreviation used to describe this problem.</p>
</div>
</div>
<p>1.57 <code>research_average</code> (Research Average z-score) Average research z-score with non-departmental units (including Dean’s offices) removed.</p>
<p>1.58 <code>research_avg_z_score_equally_weighted</code> Alternate calculation of research average with non-departmental units included in population with zero research productivity.</p>
<p>1.83 <code>comments</code> Comments from ORI regarding research metrics, their crosswalk to instructional units, etc.</p>
<section id="sri" class="level3" data-number="C.2.1">
<h3 data-number="C.2.1" class="anchored" data-anchor-id="sri"><span class="header-section-number">C.2.1</span> SRI</h3>
<p>1.82 <code>sri_aau_public_peers</code> Academic Analytics SRI score when comparing units to Public AAU Institutions. If a unit has multiple SRI scores available, they were averaged.</p>
<blockquote class="blockquote">
<p>The Scholarly Research Index (SRI) is a measure developed by Academic Analytics to evaluate the research performance of individuals and entities with respect to</p>
<ol type="1">
<li>scholarly products, such as conference proceedings, research articles, books, and book chapters,</li>
<li>recognition from the community in form of citations and awards, and</li>
<li>federal sponsoring of research projects measured by the number of grants and their amounts.</li>
</ol>
<p>Different disciplines operate differently. The weighting of each of these measures is therefore adjusted discipline specific (based on a factor analysis by Academic Analytics).</p>
</blockquote>
<p>1.59 <code>sri_aau_public_peers_z_score</code> Z score of sri_aau_public_peers</p>
<div id="wrn-sri-1" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.9: SRI Problem 1 - Averaging Multiple SRI scores
</div>
</div>
<div class="callout-body-container callout-body">
<p>Some departments have multiple SRI scores generated by Academic Analytics.</p>
<p>In some disciplines, departments might be book-focused or article focused, or might have members with different focuses. Examples in <a href="app-analysis-issues.html#fig-sri-multi-values" class="quarto-xref">Figure&nbsp;<span>B.1</span></a> include Communication Studies, Sociology, Advertising, Landscape Architecture, Interior Design, and Broadcasting, among others.</p>
<p>Another reason a department might have multiple SRI scores is that it is composed of multiple different disciplines. Examples in <a href="app-analysis-issues.html#fig-sri-multi-values" class="quarto-xref">Figure&nbsp;<span>B.1</span></a> include Agronomy &amp; Horticulture, Earth and Atmospheric Sciences, the School of Computing, Physics and Astronomy, and Electrical and Computer Engineering.</p>
<p>When there are two different norms within a discipline, SRI scores were reportedly averaged to create a mean SRI value. This is incorrect - because these values have different distributions, averaging them does not produce a meaningful result with a valid comparison distribution. A more reasonable combination method would be to evaluate each score to get a distributional measure (quantile, percentile, rank), and then to take the maximum of that measure - the departments peers would know what the focus area of the department is and which focus would be more appropriate.</p>
<p>In the case of a hybrid department, the scores were also averaged. This approach is also not reasonable, as SRI distributions are not the same across disciplines. It is critically important to go through the distribution, calculating a rank, percentile, or quantile rather than using averages. Then, if the goal is to assess the department’s performance, two reasonable approaches could be used to aggregate the percentile or quantile scores:</p>
<ul>
<li>take a weighted average of the percentile or quantile scores, with weight determined by the composition of the department.</li>
<li>take the maximum of the percentile or quantile scores in order to assess the overall opinion of the work done within the department in a community of peers. This makes more sense if the goal is to model how other people see UNL’s departments, as people tend to remember outstanding work in the field more than they remember or consider average work.</li>
</ul>
</div>
</div>
<div id="wrn-sri-2" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.10: SRI Problem 2 - Cross-Department Comparisons
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is <strong>completely inappropriate</strong> to use SRI values to compare departments to other departments within the same university. SRI values have a distribution that is discipline specific, with different means and variances. As-is they are not comparable outside of that distribution, as shown in <a href="#tbl-sri-incomparable" class="quarto-xref">Table&nbsp;<span>C.2</span></a></p>
<div class="cell">
<div id="tbl-sri-incomparable" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-sri-incomparable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;C.2: Departments at UNL with an SRI of 0.4 (calculated using all AcA universities), but with considerable variance in SRI percentile. Note that while the SRI values and percentiles would be different if the comparison population were limited to public AAU universities, the concept is still important. Changing or reducing the comparison population only changes how many universities are available for eCDF estimation and percentile calculation and shifts the population mean and variance to some degree.
</figcaption>
<div aria-describedby="tbl-sri-incomparable-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<colgroup>
<col style="width: 60%">
<col style="width: 3%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Unit</th>
<th style="text-align: right;">SRI</th>
<th style="text-align: right;">SRI Percentile</th>
<th style="text-align: right;">Number of Units</th>
<th style="text-align: right;">SRI Rank</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Agronomy and Horticulture, Department of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">92.31</td>
<td style="text-align: right;">26</td>
<td style="text-align: right;">3</td>
</tr>
<tr class="even">
<td style="text-align: left;">Computing, School of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">91.38</td>
<td style="text-align: right;">325</td>
<td style="text-align: right;">29</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Modern Languages and Literatures, Department of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">85.84</td>
<td style="text-align: right;">219</td>
<td style="text-align: right;">32</td>
</tr>
<tr class="even">
<td style="text-align: left;">Accountancy, School of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">82.93</td>
<td style="text-align: right;">205</td>
<td style="text-align: right;">36</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Educational Administration, Department of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">79.38</td>
<td style="text-align: right;">160</td>
<td style="text-align: right;">34</td>
</tr>
<tr class="even">
<td style="text-align: left;">Statistics, Department of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">75.80</td>
<td style="text-align: right;">157</td>
<td style="text-align: right;">39</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Teaching, Learning and Teacher Education, Department of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">74.68</td>
<td style="text-align: right;">79</td>
<td style="text-align: right;">21</td>
</tr>
<tr class="even">
<td style="text-align: left;">Special Education and Communication Disorders, Department of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">73.68</td>
<td style="text-align: right;">95</td>
<td style="text-align: right;">26</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Agricultural Leadership, Education and Communication, Department of</td>
<td style="text-align: right;">0.4</td>
<td style="text-align: right;">71.28</td>
<td style="text-align: right;">94</td>
<td style="text-align: right;">28</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Calculating a mean and standard deviation to create a z-score for SRI values across disciplines destroys any information which could have been found in the SRI measure.</p>
<p>Note that this is <em>not</em> an objection to SRI as a concept. It seems that SRI is a more fair method of comparison than other attempts to replicate SRI used in the budget reduction process, because at least all departments across a discipline are compared using the same (sometimes flawed) data<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. As it is, the metrics assembled by UNL, while applied to all departments equally, have unequal effects on different departments because the metrics used favor one discipline over another due to norms within that discipline. The problem with SRI is that it must be used in the context for which it was intended: comparing departments to other similar departments. The misuse of SRI results in eliminating programs which compare perfectly well to both Academic Analytics institutions and to AAU peers, as shown in <a href="metrics.html#fig-sri-percentile-all-depts" class="quarto-xref">Figure&nbsp;<span>4.1</span></a>.</p>
<p>While we do not have access to the complete data for all departments and their comparison units, we do have access to the statistics data, which is shown in <a href="metrics.html#fig-sri-by-class" class="quarto-xref">Figure&nbsp;<span>4.2</span></a>. The statistics department’s SRI value is at the top of the non-AAU R1 institutions, and is well within the bounds of the SRI range of AAU institutions. Note that we would not expect that a department be at the top of the AAU university SRI values (which is why the custom SRI score isn’t that useful, though the percentile is somewhat helpful) – what is necessary is for the department’s SRI to be above the minimum (preferably comfortably above) of the comparable AAU department SRI values.</p>
<p><strong>Problem</strong> Under the UNL proposed method (using the SRI relative to public AAU institutions), it seems that custom SRI is used instead of percentile. This renders any calculations done on SRI, and any calculations which use <code>sri_aau_public_peers</code> or <code>sri_aau_public_peers_z_score</code>, functionally meaningless as they are not comparing values drawn from the same distribution to each other. Without a common reference distribution, it is inappropriate to pool values by calculating a common mean and variance, and then to use that common mean and variance to produce a z-score.</p>
<p><strong>Solution</strong> SRI should be converted to a percentile (or corresponding quantile, if the goal is a z-score), and in disciplines without sufficient comparison departments, there will be a lot of variability in the percentile (which should be treated as an estimate). SRI should be used to evaluate research productivity instead of attempting to create a multi-metric that adds additional weight to awards, books, citations, and grants x3, as Academic Analytics has already done the factor analysis to determine which of these are relevant to which disciplines.</p>
<p><strong>Theory &amp; Statistical Rationale</strong> The Glivenko-Cantelli theorem guarantees that as <span class="math inline">\(n\rightarrow\infty\)</span> the empirical CDF (eCDF) converges to the distribution CDF <a href="https://demonstrations.wolfram.com/ConvergenceOfTheEmpiricalDistributionFunctionOfASample/">demonstration via WolframAlpha</a>. While there is no guideline for sufficient <span class="math inline">\(n\)</span>, the eCDF will be extremely blocky and step-function like at first, and as <span class="math inline">\(n\)</span> increases, the average distance between discontinuity points will decrease, producing an increasingly smooth function. The variance of the estimated percentile can be estimated by treating the percentile as a proportion and using a <a href="https://en.wikipedia.org/wiki/Binomial_proportion_confidence_interval">binomial confidence interval</a> to get a sense of the variability. Then, this binomial confidence interval can be mapped back to normal quantiles if a z-score range is desired.</p>
</div>
</div>
<div id="wrn-sri-3" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.11: SRI Problem 3 - Comparison Groups and TMFD
</div>
</div>
<div class="callout-body-container callout-body">
<p>The case of Textiles, Merchandising, and Fashion Design illustrates the problem of comparison groups quite nicely. TMFD is in the bottom quintile - ranked 25 out of 41 peers - in <a href="metrics.html#fig-sri-percentile-all-depts" class="quarto-xref">Figure&nbsp;<span>4.1</span></a>. Except the department should have 127 peers, because every land-grant university has a similar department. Looking more closely, we find that the peer group for the department in Academic Analytics is listed as “Consumer and Human Sciences, various”. Word of caution: whenever someone describes your work as ‘something with’, ‘various’, or ‘whatever’, they don’t really know what you are doing. So why doesn’t Academic Analytics know what TMDF does?</p>
<p>Academic Analytics uses CIP (Classification of Instructional Programs) codes defined by the National Center for Education Statistics to create peer groups. Merely glancing over the <a href="https://nces.ed.gov/ipeds/cipcode/cipdetail.aspx?y=56&amp;cipid=90647">Textile related cip codes</a>, it is clear that there are more fitting choices than ‘Consumer and Human Sciences, various’:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>CIP Code</th>
<th>Program Name</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>19.0901</td>
<td>Apparel and Textiles, General</td>
</tr>
<tr class="even">
<td>19.0902</td>
<td>Apparel and Textile Manufacture</td>
</tr>
<tr class="odd">
<td>19.0904</td>
<td>Textile Science</td>
</tr>
<tr class="even">
<td>19.0905</td>
<td>Apparel and Textile Marketing Management</td>
</tr>
<tr class="odd">
<td>19.0906</td>
<td>Fashion and Fabric Consultant</td>
</tr>
<tr class="even">
<td>19.0999</td>
<td>Apparel and Textiles, Other</td>
</tr>
</tbody>
</table>
<p>So why does Academic Analytics not pick a better peer group for comparisons?</p>
<p>It turns out, that Academic Analytics relies on the submitting organization to provide CIP codes:</p>
<blockquote class="blockquote">
<p>CIP Codes (to units and Ph.D.&nbsp;programs as classified in institution’s system) Note that while CIP Codes are referenced in the creation of the Academic Analytics Taxonomy and are requested in the submission instructions, they are currently used for reference only. Reporting by CIP is not available. Not all requested fields are available in the comparative database. Some data remain incomplete because institutions have not submitted those fields. However, they are archived because they may prove useful for clients and Academic Analytics, particularly in the data matching processes.</p>
</blockquote>
<p>So, at some point someone at UNL listed TMFD as “Consumer and Human Sciences, various” instead of the proper CIP code, and it is TMFD’s job to find the error, get someone in ORI to listen to the problem and fix the error, and then hope that the metrics are updated before their APC hearing. Ultimately, there just is not enough time for that process to occur, even if ORI was willing to engage and fix the analysis.</p>
</div>
</div>
</section>
<section id="awards" class="level3" data-number="C.2.2">
<h3 data-number="C.2.2" class="anchored" data-anchor-id="awards"><span class="header-section-number">C.2.2</span> Awards</h3>
<p>1.68 <code>awards_ltd_2023_total</code> NCR highly prestigious awards, including national academy memberships in engineering, medicine and science. The data source AAU uses for highly prestigious awards is Academic Analytics (AcA) and only awards for T/TT faculty in benchmarked AcA units is reported to the AAU. Highly prestigious awards are tracked over the life of the faculty member’s career and are credited to the institution where they are currently employed. Once a faculty member retires or leaves an institution, their highly prestigious awards are no longer included in the data reported to AAU. Put another way, the highly prestigious awards follow the faculty member. From the AAU Membership Policy: AAU collects the number of faculty members by institution receiving awards, fellowships, and memberships in the National Research Council (NRC) list of highly prestigious awards that included: research/scholarship awards, teaching awards, prestigious fellowships or memberships in honorary societies. Each data year represents the faculty’s lifetime honors and awards, not new honors and awards. University of Maryland, College Park data includes University of Maryland, Baltimore beginning in 2019. The Faculty Scholarly Productivity (FSP) Database. These data are reproduced under a license agreement with Academic Analytics. http://academicanalytics.com/ . The list of the NRC highly prestigious awards can be found at: National Research Council List of Highly Prestigious Awards | Association of American Universities (AAU). Memberships in the National Academies (NAS, NAE, NAM) compiled from the membership lists of each academy; lists can be found at: National Academy of Sciences: http://www.nasonline.org/member-directory/, National Academy of Engineering: http://www.nae.edu/default.aspx?id=20412, National Academy of Medicine: https://nam.edu/directory-search-form/</p>
<div id="wrn-awards" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.12
</div>
</div>
<div class="callout-body-container callout-body">
<p>Award comparisons should be made within discipline, not across disciplines, as the AAU list of prestigious awards does not include the <a href="https://www.aera.net/About-AERA/AERA-Awards">AERA</a> awards for education. As the national academies listed do not induct professors teaching in education, it is irrational to compare e.g.&nbsp;the physics department, whose members could conceivably be inducted into the NAS, NAE, or both depending on the subfield. This is one reason why Academic Analytics compares within discipline and not across disciplines.</p>
</div>
</div>
<p>1.79 <code>awards_normalized</code> <code>awards_ltd_2023_total</code> divided by <code>t_tt_headcount_2014_2023_avg.</code></p>
<p>1.63 <code>awards_normalized_z_score</code> Z score of <code>awards_normalized</code> Normalized highly prestigious awards, fellowships and memberships as defined by the AAU membership policy for awards received LTD up to 2023. Data is normalized by the average T/TT faculty headcount over the same time period as reported to IPEDS.</p>
</section>
<section id="books" class="level3" data-number="C.2.3">
<h3 data-number="C.2.3" class="anchored" data-anchor-id="books"><span class="header-section-number">C.2.3</span> Books</h3>
<p>1.69 <code>books_2014_2023_total</code> The total number of books published over the time period 2014-2023. The data source AAU uses for highly prestigious awards is Academic Analytics (AcA) and only books published for T/TT faculty in benchmarked AcA units are reported to the AAU. Book publications reported to AAU by AcA include books, casebooks, edited volumes, encyclopedias, and textbooks. AcA book types not reported include journals, proceedings, study guides and book chapters. Book publications are credited to departments based on the author’s HR tenure org unit. From the AAU Membership Policy: The total number of books published by the institution for the most recent ten-year period. The Faculty Scholarly Productivity (FSP) Database. These data are reproduced under a license agreement with Academic Analytics. http://academicanalytics.com/</p>
<p>1.80 <code>books_normalized</code> <code>books_2014_2023_total</code> divided by <code>t_tt_headcount_2014_2023_avg</code></p>
<p>1.64 <code>books_normalized_z_score</code> Z score of <code>books_normalized</code> Normalized book publications as defined by the AAU membership policy for the time period of FY2014 to FY2023. Data is normalized by the average T/TT faculty headcount over the same time period as reported to IPEDS.</p>
<div id="wrn-book-disciplines" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.13: Book Disciplines and Book Data
</div>
</div>
<div class="callout-body-container callout-body">
<p>While the book data from Academic Analytics is overall quite high quality, it does have some issues in that it is dependent on publisher reporting. The statistics department found at least one book which was misreported by the publisher, affecting the totals. More importantly, individuals do not have access to Academic Analytics – typically, only unit leads have access. Unit leads have neither the time nor the precise information to audit this information for correctness and follow up to ensure that it is fixed. These errors are likely more consequential for small departments, particularly in disciplines that are not book-centric as measured by Academic Analytics weights.</p>
<p>Books published by faculty members in the department during the decade-long interval are not included if the faculty member left the department or retired before 2024, despite the fact that these individuals contributed to the reputation of the department during the decade of interest. Dr.&nbsp;Walter Stroup published 3 extremely well-respected and popular books between 2014 and 2023, but these are not counted in the department metrics, even though Dr.&nbsp;Stroup was a past chair of the department and is an important part of our reputation for excellence, even after his retirement.</p>
<p>In addition, books are normalized by average tenure-track headcount without accounting for apportionment. Most (but not all) books published are research-centric, with textbooks as the exception. However, even textbooks are typically written while on research leave. As a result, it is probably more reasonable to normalize this value by average research FTEs rather than average number of tenure-track FTEs.</p>
</div>
</div>
</section>
<section id="citations" class="level3" data-number="C.2.4">
<h3 data-number="C.2.4" class="anchored" data-anchor-id="citations"><span class="header-section-number">C.2.4</span> Citations</h3>
<p>1.70 <code>citations_2014_2023_avg</code> The average number of citations on peer-reviewed articles for the most recent ten-year period. AcA reports citations in the year of the publication. Citations for articles coauthored by more than one UNL faculty member have been split equally across authors. AAU uses Web of Science InCites for the citations data. UNL does not currently subscribe to InCites and so is using Academic Analytics to track and report this data. Citations are credited to departments based on the author’s HR tenure org unit. From the AAU Membership Policy: Average number of times an institution’s Web of Science Documents have collectively been cited for the most recent ten-year period. InCitesTM, Clarivate (2023). Web of Science. ® These data are reproduced under a license agreement from Clarivate. http://incites.clarivate.com/</p>
<div id="wrn-citation-window" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.14: Citation Window
</div>
</div>
<div class="callout-body-container callout-body">
<p>The choice to use Academic Analytics citations is not discipline-neutral. The InCites citation window is 10 years, which is long enough for most disciplines. However, Academic Analytics citation counts for the statistics department are lower than the corresponding citation counts from InCites – 77 vs.&nbsp;127 for Susan Vanderplas, for example. In some disciplines (statistics, math), papers can reach peak average citation frequency after 15 years or more (Galiani &amp; Galvez 2017).</p>
<blockquote class="blockquote">
<p>Galiani, Sebastian and Gálvez, Ramiro H., The Life Cycle of Scholarly Articles Across Fields of Research (May 2, 2017). <a href="http://dx.doi.org/10.2139/ssrn.2964565">http://dx.doi.org/10.2139/ssrn.2964565</a></p>
</blockquote>
<p>When interpreting 10-year citation counts, it is also important to consider the age of the department. For instance, consider Dr.&nbsp;Vanderplas, who received her Ph.D.&nbsp;in 2015. It is unlikely that she had any highly cited papers before she received her Ph.D., and even unlikely in the years immediately after receiving her Ph.D., as young researchers are often not cited as frequently as more established colleagues. A department made up of primarily assistant and associate professors will be at a very large disadvantage relative to more established departments. If the number of people in the department is also small, the variability in citation counts also becomes a factor.</p>
</div>
</div>
<p>1.81 <code>citations_normalized</code> <code>citations_2014_2023_avg</code> divided by <code>t_tt_headcount_2014_2023_avg.</code></p>
<div id="wrn-citation-norm" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.15: Citation normalization
</div>
</div>
<div class="callout-body-container callout-body">
<p>Normalizing citations by tenure-track headcount instead of by effective research FTE is problematic. Some departments have a significant number of non-TT faculty in research/extension positions who contribute to the scholarly literature in their field. In addition, some departments have a vastly different apportionment between research and teaching, and this would translate into different publication rates and accumulation of citations.</p>
<p>These factors are more critical when they are used to compare across departments within a university – when Academic Analytics makes comparisons using tenure-track headcount, that leaves out some information, but it would be expected to hurt similar departments similarly. This is not the case when using these metrics to compare across departments – in these situations, discipline specific norms must be accounted for in some way.</p>
</div>
</div>
<p>1.65 <code>citations_normalized_z_score</code> Z score of <code>citations_normalized</code> Normalized citations as defined by the AAU membership policy (using Academic Analytics as a proxy for InCites) for the time period of FY2014 to FY2023. Data is normalized by the average T/TT faculty headcount over the same time period as reported to IPEDS.</p>
<div id="wrn-citation-count" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.16: Citation counts
</div>
</div>
<div class="callout-body-container callout-body">
<p>Citation counts differ wildly by discipline, and are affected both by how many researchers and papers there are in the discipline and by citation norms within that discipline. Using z-scores makes the assumption that all departments are from a similar distribution (which is clearly not the case). Comparing departments on normalized citations ensures that these discipline-specific norms dominate the signal, which biases a metric that might have been intended to indicate department research quality and reception so that it just becomes a signal for citation norms and research appointment practices.</p>
</div>
</div>
</section>
<section id="research-awards-inc-nuf" class="level3" data-number="C.2.5">
<h3 data-number="C.2.5" class="anchored" data-anchor-id="research-awards-inc-nuf"><span class="header-section-number">C.2.5</span> Research Awards Inc NUF</h3>
<div id="wrn-grant-metrics" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.17: Grant Metric Problems
</div>
</div>
<div class="callout-body-container callout-body">
<p>All of the grant metrics are affected by a common flaw: disciplines do not (usually) compete against each other within a university for awards<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. Rather, the English department might get awards from the National Endowment for the Arts or various private foundations. The Physics department likely gets grants primarily from NSF, and Engineering departments have some options - NSF, Dept of Energy, Department of Defense. Life sciences might get grants from NSF, but also NIH, CDC, Dept of Health, and the Veterans Administration. Agriculture grants will primarily come from USDA but may also come from NSF, NIH, and others because ultimately agriculture spans both applied and hard science topics across a wide range of applications.</p>
<p>What is important about this is that the amount of funding available (and size of available grants) is dramatically different between departments. That is, departments cannot be thought of as one single population! It is clear that someone putting these metrics together paid enough attention in a statistics class to remember how to compute a z-score, but apparently they missed the part where it makes no sense to compute z-scores when you don’t have a defined reference population. Or, in this case, when you absurdly claim that something that is clearly a mixture of several populations can be used as a single reference population.</p>
<p>Ignoring population heterogeneity (having multiple groups with different values in a population) is a common precursor to <a href="https://en.wikipedia.org/wiki/Simpson%27s_paradox">Simpson’s paradox</a>, where a trend of the overall data reverses direction once the groups are accounted for in the model. Without the raw data for the individuals across the university, we cannot conclusively demonstrate that this is what is happening, but it seems possible. Alternate explanations are that the data quality is not particularly good (also possible). In any case, the research award metrics ultimately cannot be used for doing more than differentiating low-grant fields from high-grant fields.</p>
<p>In addition, smaller departments will have more variability in grant funding year-to-year than larger departments. When funding rates are low (10-20%), small departments may have $0 grant funding in one year and several awards come through in subsequent years, while large departments will have a more consistent funding level. While it is not clear how funding is counted on an annual basis (e.g.&nbsp;whether <code>research_awards_growth_inc_nuf_fy2020_total_research_awards</code> counts awards which started in 2020, were awarded in 2020, or incremental funding on multi-year awards that happened to be received by the university in 2020), if funding is counted at the award level and not the amount received per year, this measure gets to be even more “lumpy” and inconsistent from year to year. When taking a ratio of differences, as in <code>research_awards_growth_inc_nuf_percent_of_total</code>, this inconsistent behavior becomes even more problematic. It would be far better to fit a trend line with 4 or even 10 years of per-capita funding data to each department, and then do inference based on the slope of that line, generating a confidence interval or even a z-score for the slope of the line. Note that we do <em>not</em> recommend comparing departments based on that z-score, because the amount of funding available will be conditional on the department discipline, and picking winners and losers within UNL based on federal grant funding availability is short-sighted. Metrics are useful for description even when they are not used for inference.</p>
</div>
</div>
<div id="wrn-cauchy-research" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.18: Problems with <code>research_awards_growth_inc_nuf_fy20_fy24</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>Of all of the random variables created in this analysis, the most problematic from a statistical theory perspective might be <code>research_awards_growth_inc_nuf_fy20_fy24</code> (and its instructional companion, <code>instructional_sch_4Y_share_growth</code>). This is the ratio of two differences, where we might reasonably model each value in the numerator as a normal random variable with mean <span class="math inline">\(\mu_d\)</span> and standard deviation <span class="math inline">\(\sigma_d\)</span> (<span class="math inline">\(d\)</span> for department), and each value in the denominator as random variables with mean <span class="math inline">\(\mu_u\)</span> and standard deviation <span class="math inline">\(\sigma_u\)</span> (<span class="math inline">\(u\)</span> for university). The problem with this is that the two differences, <span class="math inline">\(\mu_{d,2024} - \mu_{d,2020}\)</span> and <span class="math inline">\(\mu_{u,2024} - \mu_{u,2020}\)</span> have mean zero, which leads to a <span class="math inline">\(\frac{0}{0}\)</span> situation that is mathematically undefined.</p>
<p>In statistical terms, if the numerator and denominator have mean 0, then the random variable representing the ratio is <strong>Cauchy</strong> distributed. Cauchy distributions are heavy-tailed (values far away from the mean are much more likely than they would be with a normal distribution), that is, they generate extreme values more frequency. Cauchy distributions are difficult to work with because they do not have a (meaningful) mean or a standard deviation. It is possible to generate draws from a Cauchy distribution, and even to take the mean and standard deviation of those draws, but the values do not describe anything useful about the underlying data. The mean will never converge to a single value, even with a million or billion samples, unlike nearly every other common distribution.</p>
<p>As a result, calculating the z-score for something that has or might be expected to have a Cauchy distribution is fundamentally problematic, because neither the mean or the standard deviation will have any real-world meaning or even be numerically stable. The Central Limit Theorem requires that variables have finite variance precisely because of the counterexample of the Cauchy distribution.</p>
<p>Cauchy random variables are typically not covered in undergraduate math-stat and probability courses, except perhaps a mention in passing. That they arise so readily in this type of analysis is just another example why it is fundamentally necessary to have graduate statistical training or oversight in order to use complex functions of random variables to make practical decisions that will hold up under scrutiny.</p>
</div>
</div>
<p>1.74 <code>research_awards_growth_inc_nuf_fy2020_total_research_awards</code> Total sponsored research awards received in FY2020. Included are all sponsor types: federal, industry, state agencies, associations/nonprofits and the NU Foundation. This includes purpose code research only. Awards are credited to departments using NuRamp routing forms. For PI/co-PIs who routed their credit through a unit outside a department, efforts were made to credit a department using the individual’s HR tenure org unit, primary org unit and any secondary appointments.</p>
<p>1.75 <code>research_awards_growth_inc_nuf_fy2024_total_research_awards</code> Total sponsored research awards received in FY2024. Included are all sponsor types: federal, industry, state agencies, associations/nonprofits and the NU Foundation. This includes purpose code research only. Awards are credited to departments using NuRamp routing forms. For PI/co-PIs who routed their credit through a unit outside a department, efforts were made to credit a department using the individual’s HR tenure org unit, primary org unit and any secondary appointments.</p>
<p>1.76 <code>research_awards_growth_inc_nuf_fy20_fy24</code> <code>research_awards_growth_inc_nuf_fy2024_total_research_awards</code> minus <code>research_awards_growth_inc_nuf_fy2020_total_research_awards</code> Growth of sponsored research awards from FY20 to FY24. Included are all sponsor types: federal, industry, state agencies, associations/nonprofits and the NU Foundation. This was calculated by taking the dollar growth over the time period of FY24 – FY20 as a percentage of total growth for the institution resulting in that unit’s share of the overall growth dollars for the institution over the reported time period.</p>
<p>1.77 <code>research_awards_growth_inc_nuf_percent_of_total</code> <code>research_awards_growth_inc_nuf_fy20_fy24</code> for the department/unit divided by <code>research_awards_growth_inc_nuf_fy20_fy24</code> for UNL as a whole</p>
<p>1.61 <code>research_awards_growth_inc_nuf_z_score</code> Z score of <code>research_awards_growth_inc_nuf_fy20_fy24</code></p>
</section>
<section id="total-sponsored-awards-inc-nuf-rsch-pub-serv-teach" class="level3" data-number="C.2.6">
<h3 data-number="C.2.6" class="anchored" data-anchor-id="total-sponsored-awards-inc-nuf-rsch-pub-serv-teach"><span class="header-section-number">C.2.6</span> Total Sponsored Awards Inc NUF RSCH PUB SERV TEACH</h3>
<p>1.71 <code>average_total_sponsored_awards_inc_nuf_rsch_pub_serv_teach_fy2020_fy2024</code> Average annual sponsored awards received in FY20 to FY24. Included are all sponsor types: federal, industry, state agencies, associations/nonprofits and the NU Foundation. Purpose codes reported include research, teaching and public service which are summed and divided by total state appropriated budget. Awards are credited to departments using NuRamp routing forms. For PI/co-PIs who routed their credit through a unit outside a department, efforts were made to credit a department using the individual’s HR tenure org unit, primary org unit and any secondary appointments.</p>
<p>1.73 <code>total_sponsored_awards_inc_nuf_rsch_pub_serv_teach_avg_awards_budget</code> <code>Average_total_sponsored_awards_inc_nuf_rsch_pub_serv_teach_fy2020_fy2024</code> divided by <code>budget_from_evc_file_state_appropriated_budget</code> Average sponsored awards for FY20-24. Included are all sponsor types: federal, industry, state agencies, associations/nonprofits and the NU Foundation, for purpose codes research, teaching and public service divided by total state appropriated budget.</p>
<div id="wrn-total-sponsored" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.19: Problems with total_sponsored_awards_inc_nuf_rsch_pub_serv_teach_avg_awards_budget
</div>
</div>
<div class="callout-body-container callout-body">
<p>It’s unclear why the <code>total_sponsored_awards_inc_nuf_rsch_pub_serv_teach_avg_awards_budget</code> indicator was divided by total state appropriated budget, but the numbers for Statistics grants are all over the place. For instance, if we multiply the 0.362 value for statistics (before it is converted to a z-score) by the state permanent budget from 2025-26, we get 4.8118524^{5}. One PI in the department brought in 1.2 million dollars in grant money during the 2020-2024 period. Thus, we have had a difficult time validating these numbers in any way.</p>
</div>
</div>
<p>1.60 <code>awards_budget_inc_nuf_z_score</code> Z score of <code>total_sponsored_awards_inc_nuf_rsch_pub_serv_teach_avg_awards_budget</code></p>
</section>
<section id="p1-expenditures" class="level3" data-number="C.2.7">
<h3 data-number="C.2.7" class="anchored" data-anchor-id="p1-expenditures"><span class="header-section-number">C.2.7</span> P1 Expenditures</h3>
<p>1.67 <code>p1_expenditures_2014_2023_avg</code> The average competitively funded federal research support as defined by the AAU membership policy, federal research expenditures less USDA research expenditures adding in awards from USDA Agriculture Food and Research Initiative (AFRI). Expenditures and AFRI awards are credited to departments using NuRamp routing forms. For PI/co-PIs who routed their credit through a unit outside a department, efforts were made to credit a department using the individual’s HR tenure org unit, primary org unit and any secondary appointments. From the AAU Membership Policy: Competitively funded federal research support: federal R&amp;D expenditures. A ten-year average of federal research expenditures (including S&amp;E and non-S&amp;E) adjusted to exclude USDA formula-allocated research expenditures. This indicator includes obligations for the AFRI program funded by USDA. National Science Foundation (NSF) Survey of Research and Development Expenditures at Universities and Colleges/Higher Education Research and Development Survey (HERD), data for the most recently available ten-year average. AFRI Obligations, data for the ten years that match the years from HERD.</p>
<p>1.78 <code>p1_expenditures_normalized</code> <code>p1_expenditures_2014_2023_avg</code> divided by <code>t_tt_headcount_2014_2023_avg.</code></p>
<p>1.62 <code>p1_expenditures_normalized_z_score</code> Z score of <code>p1_expenditures_normalized</code> Normalized competitively funded federal research expenditures as defined by the AAU membership policy for the time period of FY2014 to FY2023. Data is normalized by the average T/TT faculty headcount over the same time period as reported to IPEDS.</p>
</section>
</section>
<section id="teaching" class="level2" data-number="C.3">
<h2 data-number="C.3" class="anchored" data-anchor-id="teaching"><span class="header-section-number">C.3</span> Teaching</h2>
<div id="wrn-data-validation" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.20: Data Lockout and Validation
</div>
</div>
<div class="callout-body-container callout-body">
<p>It is hard to validate the teaching metrics, because the administration has directed the registrar’s office and the graduate college “not to distribute data related to proposed budget reductions at this time” (<a href="documentation/Fw_ Sarah Z - EDAD Data Request.eml">email between Sarah Zuckerman and Debra Hope, Graduate College</a>).</p>
<p>The Statistics department had similar trouble getting data from Chad Brasil, though most of it could be assembled (sometimes manually) using published Tableau dashboards. As a result, it is much harder to comment on or validate the teaching metrics. There are likely similar problems with the way variables were assembled, but because of the administrative lockout, we cannot do the necessary detective work to identify those problems.</p>
</div>
</div>
<section id="enrollment" class="level4" data-number="C.3.0.1">
<h4 data-number="C.3.0.1" class="anchored" data-anchor-id="enrollment"><span class="header-section-number">C.3.0.1</span> Enrollment</h4>
<p>1.42 <code>U_major_n</code> Count of undergraduate majors, including non-primary majors. 1.44 <code>G_major_n</code> Count of graduate majors, including non-primary majors. 1.46 <code>P_major_n</code> Count of professional majors, including non-primary majors. 1.87 <code>majors</code> Sum of U, G, and P majors (all majors).</p>
<hr>
<p>1.22 <code>major_completions_bachelor_degree</code> Count of all Bachelors completions within major (including non-primary majors).</p>
<p>1.24 <code>major_completions_two_years_college</code> Count of all graduate certificate completions within major (including non-primary majors).</p>
<p>1.26 <code>major_completions_masters_degree</code> Count of all Masters completions within major (including non-primary majors).</p>
<p>1.28 <code>major_completions_doctorate_degree</code> Count of all Doctorate completions within major (including non-primary majors).</p>
<p>1.30 <code>major_completions_post_masters</code> Count of all Post Masters completions within major (including non-primary majors).</p>
<hr>
<p>1.43 <code>U_primary_major_n</code> Count of undergraduate primary majors.</p>
<p>1.45 <code>G_primary_major_n</code> Count of graduate primary majors.</p>
<p>1.47 <code>P_primary_major_n</code> Count of professional primary majors.</p>
<hr>
<p>1.23 <code>degree_n_bachelor_degree</code> Count of all Bachelors degrees with attached major (primary)</p>
<p>1.25 <code>degree_n_two_years_college</code> Count of all graduate certificates with attached major (primary).</p>
<p>1.27 <code>degree_n_masters_degree</code> Count of all Masters degrees with attached major (primary).</p>
<p>1.29 <code>degree_n_doctorate_degree</code> Count of all Doctorate degrees with attached major (primary).</p>
<p>1.31 <code>degree_n_post_masters</code> Count of all Post Masters degrees with attached major (primary).</p>
<p>1.88 <code>degrees</code> Sum of Bachelors, Masters, Doctorate, and Post Masters primary degrees</p>
<hr>
<p>1.89 <code>ratio_completions_majors</code> Ratio of all degree completions (all majors attached to a degree) to all majors, including non-primary.</p>
<div id="wrn-major-completion" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.21: Completions to Majors for New Programs
</div>
</div>
<div class="callout-body-container callout-body">
<p>The statistics department has a new undergraduate program that, for AY 2024 (the last AY with statistics), had two cohorts of students. These students are included in the denominator as majors, but could not possibly have completed the program. As a result, of course, the department looks like we have a large dropout rate or are otherwise performing poorly.</p>
<p>It would be more reasonable to exclude new majors from this count until the program is mature and has all cohorts filled. In prior years, the statistics department has hovered around a 25% - 28% completion ratio, which reflects that our MS students take approximately 2 years to finish and our Ph.D.&nbsp;students take between 4 and 6 years to finish. We fully expect that our ratio will return to about that level when our undergraduate program is mature (if, of course, the university decides to keep this program), but it will likely decrease until that point, because we continued adding students who will take 4 years to graduate in AY 2025, and our first cohort is not expected to graduate until 2026.</p>
</div>
</div>
<hr>
<p>1.871 <code>minors_U</code> Count of all undergraduate students in one or more minors offered by the unit.</p>
<p>1.872 <code>minors_G</code> Count of all graduate students in one or more minors offered by the unit.</p>
<hr>
<p>1.86 <code>enrollment</code> Sum of U, G, and P unduplicated AY headcount</p>
<p>1.94 <code>average_enrollment</code> Mean of unduplicated enrollment headcount by unit.</p>
<hr>
<p>1.93 <code>all_majors_share_growth</code> Change in share (percentage) of total (duplicated) majors from AY2020 to AY2024.</p>
<p>1.53 <code>retention_rate</code> First-year to second-year retention rate (cohort = AY - 1).</p>
<p>1.54 <code>avg_retention_rate</code> Average of first-year to second-year retention rates of last 5 cohorts. Note that average retention rates for units with average starting cohorts less than 5 were nullified.</p>
<div id="wrn-retention-rates" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.22: Retention rates
</div>
</div>
<div class="callout-body-container callout-body">
<p>Average retention rates for new programs were nullified, even if they were good. However, as discussed in <a href="#wrn-major-completion" class="quarto-xref">Warning&nbsp;<span>C.21</span></a>, there was no such nullification for the ratio of completions to majors for new programs, even though this value is equally misleading when a program is too new to have graduates. Inconsistencies in how censoring for new programs is applied causes problems – it is important to think carefully about how to ensure that measures do not produce misleading results for edge cases.</p>
</div>
</div>
<p>1.55 <code>grad_rate6</code> Six-year graduation rate (cohort = AY - 5). Graduation rate includes students that graduated from UNL.</p>
<p>1.56 <code>avg_grad6</code> Average of six-year graduation rates of last 5 cohorts. Note that average graduation rates for units with average starting cohorts less than 5 were nullified.</p>
<div id="wrn-grad-rates" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.23: Graduation Rates Shouldn’t Be Pooled
</div>
</div>
<div class="callout-body-container callout-body">
<p>Most undergraduate programs take 4 years to complete. Most MS programs take 1-2 years to complete. Ph.D.&nbsp;programs vary considerably, but post-MS work might take between 2 to 4 years to complete, assuming the MS work transfers.</p>
<p>It is utterly confusing, then, to compute six-year graduation rates when the expected time to degree completion is so widely variable – six years is enough time for 5 different MS cohorts to complete their degrees, but only 2-3 undergraduate and Ph.D.&nbsp;cohorts! It’s also not uncommon for statistics students to get an MS and a PhD within 6 years - are those students counted twice?</p>
<p>Ultimately, graduation rates should be computed separately for each program, and if those are then averaged somehow that would be at least potentially sensible. But it is important to consider expected time to degree when computing graduation rates.</p>
</div>
</div>
</section>
<section id="sch-tuition" class="level3" data-number="C.3.1">
<h3 data-number="C.3.1" class="anchored" data-anchor-id="sch-tuition"><span class="header-section-number">C.3.1</span> SCH &amp; Tuition</h3>
<p>1.48 <code>sch</code> Sum of course SCH by owner of course subject code.</p>
<div id="wrn-2020-anomalies" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.24: 2020 anomalies
</div>
</div>
<div class="callout-body-container callout-body">
<p>The SCH reported for AY 2020 are almost universally off by a factor of around 10. This anomaly needs to be tracked down and investigated, because while it may not affect any department differently, it puts the provenance of the data and the quality control measures in question. Systematic errors are a red flag to go back and consider whether the data quality is sufficiently high to be making decisions based on this data.</p>
</div>
</div>
<p>1.49 <code>total_realizable_base_tuition</code> sch by course career and student residency times base tuition rate. For AY2024, these rates were: Career | Resident | Non-resident — | — | — UG | $268 | $859 G/P | $353 | $1031</p>
<p>1.52 <code>instructor_sch</code> The logic for Instructional SCH is:</p>
<ul>
<li>If a course prefix maps to a “unit” that is instructed by a faculty member with an appointment in that “unit” then the SCH will be assigned to that “unit”.</li>
<li>If a course prefix maps to a “unit” that is instructed by a faculty member WITHOUT an appointment in that “unit” then the SCH will be assigned to the “unit” where the faculty member has their largest percentage of appointment (primary appointment home).</li>
<li>If a course maps to a “unit” that is instructed by a faculty member without an appointment e.g., no instructor of record recorded, then the SCH is assigned to the “unit” according to the course prefix.</li>
</ul>
<p>1.84 <code>instructional_sch</code> Sum of SCH attributed to instructors’ home departments. The formula takes the percentages designated to each instructor in Peoplesoft. <code>Sum(Section SCH x Instructor %)</code></p>
<p><a href="images/instructional-sch-calc.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3"><img src="images/instructional-sch-calc.png" class="img-fluid"></a></p>
<p>1.90 <code>instructional_sch_to_instructional_fte</code> Instructional SCH divided by apportioned teaching FTE</p>
<p>1.91 <code>average_instructional_sch</code> Mean of instructional SCH by unit.</p>
<p>1.92 <code>instructional_sch_4Y_share_growth</code> Change in share (percentage) of total instructional SCH from AY2020 to AY2024.</p>
<div id="wrn-cauchy-teaching" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.25: Problem: <code>instructional_sch_4Y_share_growth</code>
</div>
</div>
<div class="callout-body-container callout-body">
<p>This is another variable which is likely Cauchy distributed (see <a href="#wrn-cauchy-research" class="quarto-xref">Warning&nbsp;<span>C.18</span></a>), that is, it is the statistical equivalent of dividing by zero - the mean of the numerator is likely to be zero (in distribution) and the mean of the denominator is likely to be zero (in distribution) – each year’s SCH would be expected to be sampled from the same distribution at the department and university level.</p>
<p>The problem is that these variables do not have a distribution mean and have infinite variance. It is obviously possible to take the average of observations from this distribution, but the average will never converge (unlike samples from almost any other distribution - the average of an increasing number of samples will converge to the distribution mean, but only if the distribution has finite variance).</p>
<p>Taking a variable like this, and then calculating the mean and standard deviation across departments to standardize these variables makes this even more problematic, because it removes any meaningful information in the variable. Then, averaging these z-scores as part of an omnibus instructional z-score only serves to erase any meaningful information in the instructional z-score.</p>
<p>These problems exist in both the instructional and research z-scores, which renders the entire metric analysis statistically uninformative. Cauchy random variables are the bane of every statistics graduate student’s existence - they are primarily useful for counterexamples in proofs, but when they pop up in practice, they are always a pain to deal with, and if you don’t handle them correctly, they will ruin everything.</p>
<p>Unfortunately, the UNL administration will learn this the hard way, either by acknowledging the issue and reworking the budget reduction plan, or by eliminating highly ranked and high-performing departments because of a badly-executed statistical analysis.</p>
</div>
</div>
</section>
<section id="ratios" class="level3" data-number="C.3.2">
<h3 data-number="C.3.2" class="anchored" data-anchor-id="ratios"><span class="header-section-number">C.3.2</span> Ratios</h3>
<div id="wrn-ratios-nightmare" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.26: Ratios are Stochastic Nightmares
</div>
</div>
<div class="callout-body-container callout-body">
<p>The variability of calculated ratios complicates statistical analysis. While in some cases ratios are necessary, <strong>extreme</strong> care must be taken to ensure that there is no possibility of the ratio having a 0 in the denominator, either in observations or in the distribution (that is, it’s also bad if the <strong>distribution</strong> of the denominator has a mean of 0, even if no recorded observations actually have a mean of 0).</p>
<p>If a ratio is taken of variables with mean zero, the resulting random variable does not have a mean, standard deviation, or any other “statistical moments” (these variables have a Cauchy distribution, which does not have a mean). This does not mean that you can’t take the average of Cauchy distributed random variables – it only means that that number does not have any real-world meaning.</p>
<p>Even when the variables don’t have zero mean, taking ratios of numbers like this that have some stochastic noise can be problematic, as variability in the denominator has an outsized effect on the overall value.</p>
</div>
</div>
<p>1.85 <code>budget_to_sch</code> total original state aided budget divided by SCH</p>
<p>1.16 <code>instructional_sch_to_instructional_fte</code> Sum of each instructor’s section instruction percentage times section sch by home department of appointment divided by <code>total_instructor_fte.</code></p>
</section>
</section>
<section id="instructional-z-scores-in-institutional-metrics" class="level2" data-number="C.4">
<h2 data-number="C.4" class="anchored" data-anchor-id="instructional-z-scores-in-institutional-metrics"><span class="header-section-number">C.4</span> Instructional Z-scores in Institutional Metrics</h2>
<p>All z-scores (also known as standardized or normalized scores) were calculated as the difference of the actual metric and the mean of the metric for included units divided by the standard deviation of the included units’ metrics.</p>
<p>It measures the number of standard deviations a metric is from the mean. In a normal distribution, approximately two-thirds of scores fall within +/- 1 standard deviation of the mean. Approximately 95% of cases fall within +/- 1.96 standard deviations of the mean. Traditionally – but not universally – cases beyond the 1.96 standard deviation threshold are considered outliers.</p>
<div id="wrn-instruction-z-prob" class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning&nbsp;C.27: Instructional Z-score Problem
</div>
</div>
<div class="callout-body-container callout-body">
<p>While standardizing scores is common practice in some circumstances, it is problematic as used here, in part because it assumes that there is a single common distribution used for these values. For instance, disciplines that only have graduate programs cannot be assumed to have the same distribution of SCH because of much lower numbers of graduate students. It is utterly ridiculous to compare these programs to programs such as math or english who teach large numbers of nonmajor undergraduate service courses and will have SCH values on a vastly different scale. Departments <strong>do not</strong> have quantities which can be said to be “identically distributed” (in statistical parlance) even if you assume that the instructional metrics are reflective of a distribution of department performance, because not every department is competing in every pool. At minimum, it would be necessary to do some assessment of whether a course is primarily taken by majors or nonmajors, and then compare service teaching load separately from major teaching load, and undergraduate hours separately from graduate hours. Even under this system, it is probably necessary to “bin” departments based on the number of service courses taught/required on an annual basis, because e.g.&nbsp;Math will teach Calc 1, 2, 3, but Chemistry might teach an elective introductory course that counts for a science prerequisite, and the structural differences between these two departments and their relationship to other majors offered on campus matter significantly. While these factors are related to department productivity, no amount of work by the EDAD department is going to ensure that they teach every undergraduate STEM major an introductory service course, and as such it is ridiculous to compare SCH between EDAD and MATH or PHYS or STAT.</p>
<p>Moreover, the description of interpretation implies that these are normally distributed variables, but e.g.&nbsp;share of growth is necessarily confined to a value between 0 and 1, which is decidedly not normal because the normal distribution has support over the entire real line (that is, every value between <span class="math inline">\(-\infty\)</span> and <span class="math inline">\(\infty\)</span> has a positive, theoretically non-zero probability, though of course the values far from the mean of the distribution are expected to be infinitesimal).</p>
<p>When a metric consists of a ratio of two values, as many of these metrics do, it is even less likely that the random quantity has a normal distribution. In fact, if the numerator and denominator both have mean zero, the ratio is Cauchy distributed, and Cauchy variables do not have estimable means or variance – you can calculate a value for observed data, but it does not mean anything or converge to anything and is not an estimator of any useful quantity. While the problem is not quite as dramatic when the means of both distributions are nonzero, it is still important to be cautious because there are a number of different <a href="https://en.wikipedia.org/wiki/Ratio_distribution">ratio distributions</a> which might be relevant and not all of them are “nice”. This might be expected to be the case with a variable like <code>budget_to_sch_2024</code>, and it is almost certainly also true of <code>instructional_sch_4Y_share_growth</code></p>
<p>Ultimately, just because you <em>can</em> calculate a z-value doesn’t ensure that it has meaning in the context of the data. Even if it would <em>seem</em> to have meaning, and every point is taken from the same reference distribution, if the values are ratios, it would probably be good to check with a statistician before proceeding, because it is <em>very</em> easy to end up in a nonsensical mathematical situation.</p>
</div>
</div>
<p>2.10 <code>instructional_average</code> Mean of instructional z-scores.</p>
<p>2.11 <code>research_average</code> (Research Average z-score) Mean of research z-scores</p>
<p>2.12 <code>overall_average</code> Mean of instructional and research average z-scores.</p>
<hr>
<p>2.1 <code>zinstructional_sch_4Y_share_growth</code> Standardized <code>instructional_sch_4Y_share_growth</code></p>
<p>2.2 <code>zall_majors_share_growth</code> Standardized <code>all_majors_share_growth</code></p>
<p>2.3 <code>zinstructional_sch_2024</code> Standardized <code>instructional_sch_2024</code></p>
<p>2.4 <code>ztotal_majors_n_2024</code> Standardized <code>total_majors_n_2024</code></p>
<p>2.5 <code>zinstructional_sch_to_instructional_fte_2024</code> Standardized <code>instructional_sch_to_instructional_fte_2024</code></p>
<p>2.6 <code>zbudget_to_sch_2024</code> Standardized <code>budget_to_sch_2024</code></p>
<p>2.7 <code>znet_realizable_tuition_less_budget_2024</code> Standardized <code>net_realizable_tuition_less_budget_2024</code></p>
<p>2.8 <code>zavg_retention_rate_2024</code> Standardized <code>avg_retention_rate_2024</code></p>
<p>2.9 <code>zratio_completions_majors_2024</code> Standardized completions (all majors) to majors.</p>
<hr>
<p>2.14 <code>instruction_weight</code> <code>percent_teaching / (percent_teaching + percent_research)</code>. This is set to zero when the denominator is zero.</p>
<p>2.15 <code>research_weight</code> <code>percent_research / (percent_teaching + percent_research)</code>. This is set to zero when the denominator is zero.</p>
<p>2.13 <code>weighted_overall_average</code> Mean of <code>instructional_average</code> and research average weighted by <code>instruction_weight</code> and <code>research_weight</code> respectively.</p>
<hr>
<p>2.16 <code>mad_instructional_sch_4Y_share_growth</code> Standardized <code>instructional_sch_4Y_share_growth</code> using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<p>2.17 <code>mad_all_majors_share_growth</code> Standardized <code>all_majors_share_growth</code> using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<p>2.18 <code>mad_instructional_sch_2024</code> Standardized <code>instructional_sch_2024</code> using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<p>2.19 <code>mad_total_majors_n_2024</code> Standardized <code>total_majors_n_2024</code> using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<p>2.20 <code>mad_instructional_sch_to_instructional_fte_2024</code> Standardized <code>instructional_sch_to_instructional_fte_2024</code> using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<p>2.21 <code>mad_budget_to_sch_2024</code> Standardized <code>budget_to_sch_2024</code> using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<p>2.22 <code>mad_net_realizable_tuition_less_budget_2024</code> Standardized <code>net_realizable_tuition_less_budget_2024</code> using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<p>2.23 <code>mad_avg_retention_rate_2024</code> Standardized <code>avg_retention_rate_2024</code> using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<p>2.24 <code>mad_ratio_completions_majors_2024</code> Standardized completions (all majors) to majors using median and median absolute deviation (MAD). MAD was scaled using <code>sd(x) / mad(x, const = 1)</code> method.</p>
<hr>
<p>2.25 <code>pool_znstructional_sch_4Y_share_growth</code> Standardized <code>instructional_sch_4Y_share_growth</code> within discipline pool.</p>
<p>2.26 <code>pool_zall_majors_share_growth</code> Standardized <code>all_majors_share_growth</code> within discipline pool.</p>
<p>2.27 <code>pool_zinstructional_sch_2024</code> Standardized <code>instructional_sch_2024</code> within discipline pool.</p>
<p>2.28 <code>pool_ztotal_majors_n_2024</code> Standardized <code>total_majors_n_2024</code> within discipline pool.</p>
<p>2.29 <code>pool_zinstructional_sch_to_instructional_fte_2024</code> Standardized <code>instructional_sch_to_instructional_fte_2024</code> within discipline pool.</p>
<p>2.30 <code>pool_zbudget_to_sch_2024</code> Standardized <code>budget_to_sch_2024</code> within discipline pool.</p>
<p>2.31 <code>pool_znet_realizable_tuition_less_budget_2024</code> Standardized <code>net_realizable_tuition_less_budget_2024</code> within discipline pool.</p>
<p>2.32 <code>pool_zavg_retention_rate_2024</code> Standardized <code>avg_retention_rate_2024</code> within discipline pool.</p>
<p>2.9 <code>pool_zratio_completions_majors_2024</code> Standardized completions (all majors) to majors within discipline pool.</p>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>Academic Analytics analysts are very aware of the flaws in their data. If UNL wants to improve as an institution, one way to facilitate that would be to have PIs to ask e.g.&nbsp;federal grant agencies other than NIH and NSF to report data to Academic Analytics, as this would likely help us. Another option is for UNL to actually talk to analysts at Academic Analytics and to ensure that UNL follows statistical validation procedures that are as well thought out as AcA’s procedures.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>The Fulbright program might be one common exception, as it allows applications from many different disciplines. However, this would likely fall under “Awards” more generally instead of research awards/grants.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./app-analysis-issues.html" class="pagination-link" aria-label="Problems with the Analysis of Research and Teaching Data">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Problems with the Analysis of Research and Teaching Data</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./app-engagement-ori.html" class="pagination-link" aria-label="Attempts to Document Metrics and Data Issues">
        <span class="nav-page-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Attempts to Document Metrics and Data Issues</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>