<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>6&nbsp; Program Analysis – Statistics: An Essential Department for a Modern R1 University</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./centralized.html" rel="next">
<link href="./peer-analysis.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-e1615be2c113e74b0a69323fdd91d2e9.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="site_libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="site_libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="site_libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="site_libs/kePrint-0.0.1/kePrint.js"></script>
<link href="site_libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./program-analysis.html"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Program Analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Statistics: An Essential Department for a Modern R1 University</a> 
        <div class="sidebar-tools-main">
    <a href="./Statistics--An-Essential-Department-for-a-Modern-R1-University.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Executive Summary</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./unl-stats-dept.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">The UNL Statistics Department</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./metrics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Metrics</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./peer-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Peer Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./program-analysis.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Program Analysis</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./centralized.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Centralized vs.&nbsp;Distributed Statistics Model</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./evaluating-budget.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Evaluating the Budget Proposal Realistically</span></span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./future.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Planning for the Future</span></span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-faculty-system.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">A</span>&nbsp; <span class="chapter-title">Statistics Faculty in the UN System</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-analysis-issues.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">B</span>&nbsp; <span class="chapter-title">Problems with the Analysis of Research and Teaching Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-metrics-analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">C</span>&nbsp; <span class="chapter-title">A Statistical Commentary on the Metric Inputs and Calculations</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./app-engagement-ori.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">D</span>&nbsp; <span class="chapter-title">Attempts to Document Metrics and Data Issues</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2025-Stat-APC-report.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Report to APC</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#apc-criteria" id="toc-apc-criteria" class="nav-link active" data-scroll-target="#apc-criteria"><span class="header-section-number">6.1</span> APC Criteria</a>
  <ul class="collapse">
  <li><a href="#addressing-the-criteria-in-support-of-reduction" id="toc-addressing-the-criteria-in-support-of-reduction" class="nav-link" data-scroll-target="#addressing-the-criteria-in-support-of-reduction"><span class="header-section-number">6.1.1</span> Addressing the Criteria in Support of Reduction</a></li>
  <li><a href="#addressing-the-criteria-indicating-that-elimination-is-inadvisable" id="toc-addressing-the-criteria-indicating-that-elimination-is-inadvisable" class="nav-link" data-scroll-target="#addressing-the-criteria-indicating-that-elimination-is-inadvisable"><span class="header-section-number">6.1.2</span> Addressing the Criteria Indicating that Elimination is Inadvisable</a></li>
  <li><a href="#addressing-criteria-indicating-that-reduction-is-inadvisable" id="toc-addressing-criteria-indicating-that-reduction-is-inadvisable" class="nav-link" data-scroll-target="#addressing-criteria-indicating-that-reduction-is-inadvisable"><span class="header-section-number">6.1.3</span> Addressing Criteria Indicating that Reduction is Inadvisable</a></li>
  </ul></li>
  <li><a href="#effects-of-proposed-cuts-on-outside-programs" id="toc-effects-of-proposed-cuts-on-outside-programs" class="nav-link" data-scroll-target="#effects-of-proposed-cuts-on-outside-programs"><span class="header-section-number">6.2</span> Effects of Proposed Cuts on Outside Programs</a>
  <ul class="collapse">
  <li><a href="#mathematics" id="toc-mathematics" class="nav-link" data-scroll-target="#mathematics"><span class="header-section-number">6.2.1</span> Mathematics</a></li>
  <li><a href="#university-wide-impact" id="toc-university-wide-impact" class="nav-link" data-scroll-target="#university-wide-impact"><span class="header-section-number">6.2.2</span> University-Wide Impact</a></li>
  </ul></li>
  <li><a href="#undergraduate-program" id="toc-undergraduate-program" class="nav-link" data-scroll-target="#undergraduate-program"><span class="header-section-number">6.3</span> Undergraduate Program</a></li>
  <li><a href="#sec-ms-prog-analysis" id="toc-sec-ms-prog-analysis" class="nav-link" data-scroll-target="#sec-ms-prog-analysis"><span class="header-section-number">6.4</span> Graduate Programs</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span id="sec-program-analysis" class="quarto-section-identifier"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Program Analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<blockquote class="blockquote">
<p>UNL has the vision to invest in statistics for decades, having started with its roots in Biometry and mathematics, and creating a Department of Statistics. The department is an invisible backbone on your campus with an impeccable impact. It not only does its own fundamental research in statistics and data science, but also has a significant impact on the research and discoveries across the campus and across Nebraska. It is the only department in all of Nebraska that offers doctoral degrees in Statistics (UNMC offers a PhD in Biostatistics). My sincere concern is the irreversible damage a decision to abolish your statistics department will have not only on your campus, but also in the state of Nebraska. I just wonder as a Dean (not just as a statistician) whether the university is, unfortunately, killing the goose that lays a golden egg. – <a href="letters/Sastry Pantula UNL_Letter-1.pdf">Sastry Pantula, Dean, College of Natural Sciences, California State University</a></p>
</blockquote>
<section id="apc-criteria" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="apc-criteria"><span class="header-section-number">6.1</span> APC Criteria</h2>
<p>The APC procedures specify criteria for the reduction or elimination of academic programs. We will address each set of criteria separately to both show that the criteria in support of reduction or elimination are not met and to show that the criteria indicating that elimination is inadvisable are satisfied. These are taken from APC <a href="https://apc.unl.edu/procedures-be-invoked-significant-budget-reallocations-and-reductions/criteria/">Criteria for program evaluation</a>.</p>
<section id="addressing-the-criteria-in-support-of-reduction" class="level3" data-number="6.1.1">
<h3 data-number="6.1.1" class="anchored" data-anchor-id="addressing-the-criteria-in-support-of-reduction"><span class="header-section-number">6.1.1</span> Addressing the Criteria in Support of Reduction</h3>
<blockquote class="blockquote">
<ol type="1">
<li><p>The program’s present and probable future demand is insufficient to justify its maintenance at existing levels of support. Insufficient demand may be indicated by significant decline in one or more of these areas over a protracted period:</p></li>
<li><p>the number of completed applications for admission to the program;</p></li>
<li><p>the student credit hours generated in lower division, upper division, professional, and/or graduate level courses in the program;</p></li>
<li><p>the number of students who complete majors or degrees in the program;</p></li>
<li><p>in the case of instructional programs designed to prepare graduates for specific employment, the market demand for graduates of the program;</p></li>
<li><p>in the case of service programs, the level of demand for the service provided;</p></li>
<li><p>in the case of research programs, the quality and quantity of research being conducted;</p></li>
<li><p>in the case of research programs, the level of external funding, given the relative availability of funds.</p></li>
</ol>
</blockquote>
<p>Of the fastest growing occupations identified by the Bureau of Labor Statistics, Data Scientists, Actuaries, and Operations research analysts are 4th, 8th, and 9th, respectively. All involve statistical training, and many data science jobs would have been advertised as requiring a statistics degree even 5 years ago. However, even if we confine ourselves to positions explicitly labeled as statistician, the BLS expects 9% growth in these positions over the next decade, which is considerably faster growth than most other professions. Thus, we can see that the market demand for graduates of our programs at all levels is there. In addition, while statistics does not pull in grants which are comparable in size to those in lab-based sciences that require laboratory equipment, AI is one of the stated research priorities of the current administration. Most deep learning and large language models are built on a fundamental foundation of statistics.</p>
<div id="fig-stat-growth" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stat-growth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/Statdegreefig2.png" class="lightbox" data-gallery="quarto-lightbox-gallery-1" title="Figure&nbsp;6.1: Statistics degrees by degree level and data science bachelor’s degrees awarded in the United States, from Amstat News, 2024-11-05"><img src="images/Statdegreefig2.png" class="img-fluid figure-img" style="width:50.0%"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stat-growth-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.1: Statistics degrees by degree level and data science bachelor’s degrees awarded in the United States, from <a href="https://magazine.amstat.org/blog/2024/11/05/data-science-analytics-degrees-see-explosive-growth/">Amstat News, 2024-11-05</a>
</figcaption>
</figure>
</div>
<blockquote class="blockquote">
<p>The number of U.S. undergraduates earning degrees in statistics has increased more than six-fold since 2010, with over 5,500 bachelors degrees awarded in 2023, with the number of institutions offering such programs nearly doubling over the same period (from 95 to 184). At the Master’s level, statistics degrees have increased 150% since 2010 to 5,150 in 2023, while data science and analytics-related degrees increased an astonishing 15-fold to more than 12,000 in that period. The number of universities granting statistics and data-intensive degrees also grew from 70 to 300. These trends reflect the central role of statistics and data science in today’s workforce; the financial benefit to UNL, Nebraska, and the overall U.S. economy cannot be overstated. – <a href="letters/CarlinBrad_10_2_25_Regents.pdf">Brad Carlin, UNL Math &amp; Statistics alumni, former faculty at CMU and University of Minnesota Statistics, President of Biostatistical Consulting</a></p>
</blockquote>
<p>While we are early in our undergraduate program, and have not yet existed long enough to graduate our first class, we expect that the increased demand for data scientists and statisticians should result in increased enrollment in the program over the near term, so long as we have sufficient support from the university for advertising and recruiting. Of course, it is easier to recruit students when it is possible to make statements about graduates having found jobs, or continued on to graduate school. For instance, we can advertise our Ph.D.&nbsp;program by saying that all graduates have found employment in their field, whether in academia, government, or industry. It is somewhat harder to recruit new students before the program has graduated its first class. This is one reason why the <a href="https://ccpe.nebraska.gov/sites/default/files/AP_Guidelines_Review%20of%20Existing%20Instructional%20Programs.pdf">NE Coordinating Commission for Postsecondary Education</a> rules require a five-year period to evaluate program enrollment and graduation rates.</p>
<p>Given the demand for statistics and data science education, Criteria 1.1.1.1-7 cannot be used to support elimination of the department<a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>.</p>
<blockquote class="blockquote">
<ol start="2" type="1">
<li>The program would normally be expected to be accredited but is not; or it is exposed to a substantial risk of loss of accreditation. If the program is not appropriate for accreditation, the program has been deemed to be of a quality or size that raises questions concerning its viability or continuation.</li>
</ol>
</blockquote>
<p>The graduate statistics program at UNL has been increasing in ranking over the past 5-10 years. It is seen as a small-but-quality program within our discipline, and our graduates all get jobs working within their field of study, whether in industry, government, or academia.</p>
<p>Our undergraduate statistics program is known for having a high proportion of statistics coursework, which is why many of our current students selected this program over Data Science and over programs at other institutions. While our undergraduate curriculum is still young, it was favorably evaluated at our last APR, which occurred before the first cohort started.</p>
<blockquote class="blockquote">
<p>“The undergraduate program plan is an outstanding one – we are impressed by the vision and effort that has gone into this already. We think this is very important for UNL and the State of Nebraska, given the enormous demand for people who are highly trained in statistics. Based on what has been observed nationwide, we expect this program to grow very quickly – potentially to hundreds of majors in the near future. Hence, developing and teaching thee courses, as well as addressing student advising needs will require considerable resources in terms of faculty and staff. It is important to be cognizant of the amount of time and effort to build this program. We note that three members of the external review team are in large statistics departments that have many more tenure-track faculty and teaching faculty than Statistics at Nebraska. Even with our resources, we have found it to be a challenging undertaking to find the people hours necessary to build new majors.” - <a href="documentation/2021-STAT-APR-Report.pdf">2021 APR Report</a></p>
</blockquote>
<p>Thus, we do not believe criteria 1.1.2 applies to the statistics department; it should not be used to support our elimination.</p>
<blockquote class="blockquote">
<ol start="3" type="1">
<li><p>The program’s productivity relative to the university’s investment in faculty, staff, and equipment, facilities, or other resources has declined significantly.</p>
<ol type="1">
<li>In the case of instructional programs, a significant decline in productivity might be indicated by a decrease in the generation of student credit hours of all courses per full-time equivalent (FTE) faculty over the past five years relative to UNL enrollment trends and by a low level of student credit hours per full-time equivalent (FTE) faculty in comparison to that of UNL’s peer institutions and/or similar programs at UNL.</li>
<li>In the case of non-instructional programs, productivity shall, where possible, be measured in terms of units of output appropriate to the program’s mission.</li>
</ol></li>
</ol>
</blockquote>
<div class="cell">
<div class="cell-output-display">
<div id="fig-instructional-sch-fte" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-instructional-sch-fte-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="program-analysis_files/figure-html/fig-instructional-sch-fte-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-2" title="Figure&nbsp;6.2: The department’s instructional SCH generated between 2020 and 2024 has not significantly decreased (a horizontal line can easily be drawn across the standard error band, indicating that the slope of the line is not significantly different from zero). The SCH per teaching FTE has stayed almost constant over the 5-year period evaluated in the budget process. Meanwhile, teaching FTE has declined, but the decline is also not statistically significant. What seems clear is that any decrease in instructional SCH generated directly correlates to the decrease in teaching FTE. Thus, the department’s instructional productivity has remained consistent despite introducing the Statistics and Data Analytics BS program in 2022 and the Data Science BS program(s) across colleges in 2023."><img src="program-analysis_files/figure-html/fig-instructional-sch-fte-1.png" class="img-fluid figure-img" width="768"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-instructional-sch-fte-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.2: The department’s instructional SCH generated between 2020 and 2024 has not significantly decreased (a horizontal line can easily be drawn across the standard error band, indicating that the slope of the line is not significantly different from zero). The SCH per teaching FTE has stayed almost constant over the 5-year period evaluated in the budget process. Meanwhile, teaching FTE has declined, but the decline is also not statistically significant. What seems clear is that any decrease in instructional SCH generated directly correlates to the decrease in teaching FTE. Thus, the department’s instructional productivity has remained consistent despite introducing the Statistics and Data Analytics BS program in 2022 and the Data Science BS program(s) across colleges in 2023.
</figcaption>
</figure>
</div>
</div>
</div>
<p>Figure <a href="#fig-instructional-sch-fte" class="quarto-xref">Figure&nbsp;<span>6.2</span></a> shows that the instructional productivity of the statistics department has not effectively changed (panel 2) over the 2020-2024 period. We suspect that this quantity is likely to actually increase if numbers from 2024-25 and 2025-26 were included, as our programs are maturing and we have taken steps to increase class size and instructional efficiency since our new chair was hired in Summer 2024. None of these changes are reflected in the assembled metrics.</p>
<p>However, we are not just an instructional program - we also have research, extension, and collaboration/service missions. Our productivity in these areas has also not decreased relative to the number of people in the department and their time in rank – it is normal for younger faculty to have fewer collaborative relationships, as these develop over the course of a career and can require a significant years-long investment before meaningful products such as co-authored papers are produced.</p>
<p>On any of these criteria, however, the department’s productivity has remained high relative to the standards of our field. Thus, we do not believe criteria 1.1.3 apply to our department.</p>
<blockquote class="blockquote">
<ol start="4" type="1">
<li>The instructional productivity of a program is substantially less than the average for UNL as a whole. The level of instruction and the mode of instruction appropriate to the program shall be considered, including particularly the average number of contact hours carried by the faculty.</li>
</ol>
</blockquote>
<p>The instructional productivity of the department has increased significantly in the past year as the department increased section sizes for Stat 218, reducing the number of Statistics students funded through teaching. However, these changes are not included in the instructional metrics, because that data is more than a year old. In addition, there are expected inefficiencies that occur at the beginning of a new program - initial classes are small and are expected to grow (if the program is given adequate support). Our instructional efficiency is comparable to other departments with similar profiles, such as Mathematics: we have graduate students who assist with teaching general education courses, but major courses are primarily taught by faculty.</p>
<blockquote class="blockquote">
<ol start="5" type="1">
<li>The program’s reduction or elimination will not substantially impair the viability or quality of other UNL programs.</li>
</ol>
</blockquote>
<p>The elimination of the statistics department <strong>will damage</strong> the viability of programs in Actuarial Science, Data Science, Agronomy, Agricultural Economics, and others, as shown in <a href="#tbl-stat-courses-reqd" class="quarto-xref">Table&nbsp;<span>6.2</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-stat-courses-majors" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-stat-courses-majors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="program-analysis_files/figure-html/fig-stat-courses-majors-1.png" class="lightbox" data-gallery="quarto-lightbox-gallery-3" title="Figure&nbsp;6.3: Statistics course average enrollment by major/nonmajor. Agronomy students . Stat 218 and 380 have been omitted to make comparisons easier. Many statistics courses serve students across a variety of outside programs."><img src="program-analysis_files/figure-html/fig-stat-courses-majors-1.png" class="img-fluid figure-img" width="768"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-stat-courses-majors-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6.3: Statistics course average enrollment by major/nonmajor. Agronomy students . Stat 218 and 380 have been omitted to make comparisons easier. Many statistics courses serve students across a variety of outside programs.
</figcaption>
</figure>
</div>
</div>
</div>
<p>In addition, specific graduate statistics courses other than Stat 801/802/870 are often required by committees in Agronomy, Engineering, and other disciplines.</p>
<blockquote class="blockquote">
<p>My background is in quantitative genetics and plant improvement—I owned my own company for 30 years, worked for a multi-national corporation, and spent nearly 7 years as a faculty member in the Department of Agronomy and Horticulture… The proposal to eliminate the Department of Statistics at UN-L will deliver a severe blow to all the biological sciences at UN-L, but especially the Plant and Animal Sciences graduate programs (who already collaborate extensively to offer many courses together in these statistically related disciplines). It will effectively eliminate our ability to offer most graduate degrees in these disciplines, or relegate our graduate programs to the “minor leagues.” – <a href="letters/ThomasHoegemeyer.pdf">Thomas C. Hoegemeyer, Ph.D.</a></p>
</blockquote>
<p>It is clear that the current proposal to eliminate all statistics courses on campus other than 218, 380, 801, 802, and 870 will dramatically hurt programs across campus. Thus, under criteria 1.1.5, the program elimination cannot be justified.</p>
<blockquote class="blockquote">
<ol start="6" type="1">
<li>The program’s contribution to the UNL missions of instruction, research, and service is sufficiently marginal not to justify maintenance of its present size.</li>
</ol>
</blockquote>
<p>The Statistics department at UNL has around 13 FTE, and yet manages to offer a BS, MS, and Ph.D.&nbsp;program, undergraduate and graduate minors, and a large number of courses which are required or necessary for other degree programs. This contribution to the teaching mission of the university is significant.</p>
<p>However, the contributions of the statistics department extend to the research mission as well, though in statistics these contributions are considered service rather than research. While we train graduate students from other disciplines, we also have collaborations across campus, assisting other faculty and graduate students with their research. Many of these collaborations are not documented in coauthored papers or grants, because statisticians view collaboration and consulting as part of the job, and as long as it isn’t a commitment involving large amounts of time (say, more than 1 day/week), we do not usually require compensation and simply hope that the collaboration will eventually lead to coauthored papers.</p>
<p>Up until this budget reduction proposal, this “unseen” component of faculty labor seemed to be well understood in IANR, and was also reflected in P&amp;T evaluations of statistics faculty. Faculty in Statistics have helped to design extension web applications to share research findings from Bio-systems Engineering with farmers, assisted with the visualization of observational data in Animal Science, discussed visualization methods with qualitative researchers in CEHS, and more.</p>
<p>In addition to those contributions to other disciplines research, research in statistics has the potential to impact both our field and other fields in interesting ways. Statistics faculty regularly publish software packages to make our methodological research available to others. Some of the packages available on CRAN (a software repository for R statistical software) authored or coauthored by UNL faculty include: <code>GGally</code> (103,575), <code>bulletr</code> (294), <code>cmcR</code> (483), <code>cmpsR</code> (317), <code>ggmosaic</code> (16,697), <code>ggparallel</code> (1,245), <code>ggpcp</code> (6,376), <code>lvplot</code> (3,511), <code>nullabor</code> (8,086), <code>productplots</code> (16,266), <code>qqplotr</code> (24,677), <code>rotations</code> (748), <code>toolmaRk</code> (213), <code>x3ptools</code> (1,379), <code>ggenealogy</code> (332), <code>highlightr</code> (176), <code>dmtl</code> (271), <code>tidychangepoint</code> (231). Numbers shown in parentheses are the 30-day download counts as of October 4, 2025 from CRAN repositories (additional downloads may have occurred via GitHub).</p>
<p>Section <a href="metrics.html#sec-metrics-research" class="quarto-xref"><span>Section 4.1</span></a> details our research ranking compared to other statistics departments among AAU universities. It is clear that our department is punching well above our weight per FTE across many different dimensions of the teaching, research, service, and extension missions at UNL. We have been, for several years, the “little department that could”. As a result, we do not believe criteria 1.1.6 applies to our department either.</p>
</section>
<section id="addressing-the-criteria-indicating-that-elimination-is-inadvisable" class="level3" data-number="6.1.2">
<h3 data-number="6.1.2" class="anchored" data-anchor-id="addressing-the-criteria-indicating-that-elimination-is-inadvisable"><span class="header-section-number">6.1.2</span> Addressing the Criteria Indicating that Elimination is Inadvisable</h3>
<blockquote class="blockquote">
<ol type="1">
<li>The program has achieved a national or international reputation for quality as indicated by objective evaluations.</li>
</ol>
</blockquote>
<p>The UNL statistics department is recognized by many leading statisticians as a small, but powerful program:</p>
<ul>
<li><p>“The department is highly visible, and internationally recognized for its contributions to education and both collaborative and methodological research. At a time when the amount of data is exploding and misinformation is spreading across the internet (and increasingly, even being promoted by some of our own elected leaders), the need for UNL to be a leader in the promotion of statistical literacy is more acute than ever.” – <a href="letters/CarlinBrad_10_2_25_Regents.pdf">Brad Carlin, UNL Math &amp; Statistics alumni, former faculty at CMU and University of Minnesota Statistics, President of Biostatistical Consulting</a></p></li>
<li><p>“The University of Nebraska has a distinguished record, which I believe must not have been adequately captured in whatever statistics you may have been given; and their work has been valuable to me personally. In fact, during the pandemic, I spent a great deal of time studying publications from the University of Nebraska’s Statistics Department. I later invited faculty members from University of Nebraska to speak at the Stanford statistics seminar and also arranged meetings with people in the health sciences industry who were interested in using group testing ideas from which the Statistics Department of the University of Nebraska is a pioneer to solve an urgent problem — scaling Covid tests to larger user populations when few PCR machines are available. This type of work will be essential the next time we have new public health emergencies.” – <a href="letters/David Donoho-Stanford.pdf">David Donoho, Professor of Statistics, Stanford University</a></p></li>
<li><p>“This is a small but globally impactful unit that significantly enhances the university’s reputation.” – <a href="letters/DiCook.pdf">Dianne Cook, Professor of Statistics, Monash Business School. ASA Fellow, R Foundation Board Member, International Statistical Institute Member</a></p></li>
<li><p>“UNL Statistics has made significant contributions to the field, and includes several highly-influential researchers whose work has had a profound impact. I have personally worked with two of your faculty — Professor Heike Hofmann and Professor Susan VanderPlas — of whom I have the highest respect. Professor Hofmann is a leading figure in data visualization, whose work has shaped how data is presented and understood globally. Professor VanderPlas is a rising star in statistical computing and statistical graphics, who recently won a prestigious NSF career award.” – <a href="letters/Rob_Hyndman.pdf">Rob Hyndman, Professor of Statistics and former Chair, Department of Econometrics &amp; Business Statistics, Monash University</a></p></li>
<li><p>“I visited UNL this summer as Program Chair of the IISA 2025 conference, a major international meeting that brought leading statisticians and probabilists to campus. I was struck by how lovely and modern the IISA 2025 venue was—the infrastructure was first-rate; I genuinely found myself wishing we had something like that at Columbia. Sourav Chatterjee (Stanford)— arguably the most influential probabilist/statistician of his generation—delivered a keynote, underscoring the scholarly profile UNL can attract. I met many members of your department; they were collegial, ambitious, and committed to elevating UNL’s stature. In particular, Prof.&nbsp;Bertrand Clarke is a distinguished scholar whom I hold in the highest regard—an asset to UNL. The department is trying to grow; in a moment when Statistics, Data Science, and AI are central to society and the economy, abolishing a statistics department makes no sense.” – <a href="letters/Bodhisattva Sen.pdf">Bodhi Sen, Professor and Chair, Department of Statistics, Columbia University</a></p></li>
<li><p>“Statistics is a small department with outsized impact on IANR – it is remarkable how much the department is accomplishing with the relatively small number of faculty.” – <a href="documentation/2021-STAT-APR-Report.pdf">2021 APR Team Report</a></p></li>
<li><p>“The undergraduate program plan is an outstanding one – we are impressed by the vision and effort that has gone into this already. We think this is very important for UNL and the State of Nebraska, given the enormous demand for people who are highly trained in statistics.” – <a href="documentation/2021-STAT-APR-Report.pdf">2021 APR Team Report</a></p></li>
</ul>
<p>While the APR reports are the closest we can come to objective evaluations, the time period over which evaluations can be obtained is limited, given that we have not had an undergraduate program for very long. The department’s rating in US News and World Report is #66. While USNWR uses methodology that has <a href="https://www.insidehighered.com/opinion/views/2023/10/09/why-new-us-news-rankings-are-flawed-opinion">frequently been criticized</a>, we provide information here because it demonstrates both the growth of the field and the increased perception of the statistics department. In 2010, when rankings began for statistics programs, UNL was not listed (only 22 Statistics departments and 8 Biostat departments were included)<a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a>. In 2014, <a href="https://web.archive.org/web/20170524203540/https://www.usnews.com/best-graduate-schools/top-science-schools/statistics-rankings/page+4">UNL was listed as RNP (essentially, unranked)</a>. In 2018, <a href="https://web.archive.org/web/20180525103026/https://www.usnews.com/best-graduate-schools/top-science-schools/statistics-rankings/page+4">UNL was not listed at all</a> but the number of universities in the list had increased to 98 ranked statistics and/or biostatistics departments. In 2022, <a href="https://www.usnews.com/best-graduate-schools/top-science-schools/statistics-rankings">UNL was ranked 66th among 101 universities</a>, indicating a steep increase in the perception of the department.</p>
<p>The rankings are updated every 4 years. If UNL closes the statistics department, will it discover in May 2026 that we should have been a point of pride for the university? We strongly believe that under criteria 1.2.1, the department’s reputation is sufficiently good to recommend against its elimination.</p>
<blockquote class="blockquote">
<ol start="2" type="1">
<li>The program supplies significant instruction, research, or service that UNL is better equipped to supply than other colleges or universities.</li>
</ol>
</blockquote>
<p>The UNL statistics program supplies instruction, research, and service to UNL which cannot be easily supplied by other universities. As the next point demonstrates, we are alone within the state of Nebraska in providing both graduate and undergraduate degrees in Statistics. That is, the only other collection of a significant number of statisticians in the state is UNMC Biostatistics, but they fill a very different niche in the research ecosystem of the state and are ill-equipped to serve both the medical school and UNL researchers.</p>
<p><a href="#tbl-stat-courses-reqd" class="quarto-xref">Table&nbsp;<span>6.2</span></a> provides a list of degree programs which require statistics courses which will not be taught under the current budget plan. <a href="#fig-stat-courses-majors" class="quarto-xref">Figure&nbsp;<span>6.3</span></a> shows the proportion of majors and non majors in statistics courses: the proportion of non majors is sufficiently high to demonstrate that we provide critical instruction for programs across UNL.</p>
<blockquote class="blockquote">
<p>[T]he decision to close the statistics department does not reflect that philosophy [“vertical cuts”], as the work of Statistics supports that of every other unit within IANR, and many across the university. The training and teaching provided by Statistics faculty is critical to the training of the vast majority of graduate students throughout IANR who work on projects relevant to agronomy, plant breeding, animal science, and value-added agriculture. – <a href="letters/James Schnable.pdf">Professor James Schnable, Nebraska Corn Checkoff Presidential Chair, Department of Agronomy &amp; Horticulture</a></p>
</blockquote>
<blockquote class="blockquote">
<p>The Statistics Department is irreplaceable. Its contributions span education, research, and economic development, touching every student, every faculty member, and every industry in Nebraska. Eliminating this department would harm education, cripple interdisciplinary research, weaken the state’s workforce, and undermine Nebraska’s ability to compete in the AI- and IT-driven economy of the future. – <a href="letters/Zhenghong Tang-CRPchairUNL.pdf">Zhenghong Tang, Professor &amp; Associate Dean for Research &amp; Innovation, College of Architecture</a></p>
</blockquote>
<p>We feel that both objective quantitative and subjective qualitative evidence supports the fact that the statistics department and its programs are essential to the university and the state of Nebraska. Thus, under criteria 1.2.2, the APC should recommend the department and its programs be retained.</p>
<blockquote class="blockquote">
<ol start="3" type="1">
<li>The program is the only one of its kind within the State of Nebraska.</li>
</ol>
</blockquote>
<p>The colleges and universities in the state of Nebraska:</p>
<div id="tbl-stat-programs" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stat-programs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.1: Colleges and Universities offering undergraduate and graduate degrees in Nebraska. While some institutions offer programs in Data Science, UNL is the only university offering a BS, MS, or Ph.D.&nbsp;in Statistics. Institutions only offering theological degrees, medical degrees, or associates degrees have been excluded from this table to save space.
</figcaption>
<div aria-describedby="tbl-stat-programs-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="caption-top table">
<thead>
<tr class="header">
<th>School</th>
<th>Undergraduate</th>
<th>Graduate</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Chadron State</td>
<td><a href="https://www.csc.edu/academics/mathematics/degree-programs--information/">Minor</a></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Peru State</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>UNK</td>
<td><a href="https://catalog.unk.edu/undergraduate/departments-programs/mathematics-statistics/statistics-minor/">Minor</a></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>UNL</td>
<td><a href="https://catalog.unl.edu/undergraduate/agricultural-sciences-natural-resources/statistics-data-analytics/#fouryearplanstext">BS</a>, <a href="https://catalog.unl.edu/undergraduate/agricultural-sciences-natural-resources/data-science/#majortext">BS Data Science</a></td>
<td><a href="https://graduate.unl.edu/academics/programs/STAT-MS/">MS</a>, <a href="https://graduate.unl.edu/academics/programs/STAT-PHD/">Ph.D.</a> Statistics</td>
<td></td>
</tr>
<tr class="odd">
<td>UNO</td>
<td><a href="https://catalog.unomaha.edu/undergraduate/college-arts-sciences/mathematics/mathematics-bs/statistics-conc/">Stat Conc,</a> in Math degree</td>
<td><a href="https://catalog.unomaha.edu/graduate/degree-programs-certificates-minors/data-science/#requirementstext">MS</a> Data Science</td>
<td>only 6 hours of STAT required for either program</td>
</tr>
<tr class="even">
<td>UNMC</td>
<td></td>
<td><a href="https://catalog.unmc.edu/graduate-studies/programs-requirements/msdegrees/mbios/">MS</a>, <a href="https://catalog.unmc.edu/graduate-studies/programs-requirements/phd/biostats/">Ph.D.</a> in Biostatistics</td>
<td></td>
</tr>
<tr class="odd">
<td>Wayne State</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Creighton</td>
<td><a href="https://catalog.creighton.edu/undergraduate/arts-sciences/data-science/data-science-major/index.html">BS Data Science</a></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Doane</td>
<td><a href="https://www.doane.edu/programs/mathematics-data-analytics">BS Math and Data Analytics</a></td>
<td></td>
<td></td>
</tr>
<tr class="even">
<td>Hastings College</td>
<td><a href="https://www.hastings.edu/academics/undergraduate-majors/mathematics/">BS Actuarial Science</a></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Nebraska Weslyan</td>
<td><a href="https://www.nebrwesleyan.edu/academics/majors-and-minors/mathematics-and-computer-science/degrees/data-analytics-ba-bs-0">BS Data Analytics</a></td>
<td></td>
<td>In-major courses offered fully remote through other institutions.</td>
</tr>
<tr class="even">
<td>Bellevue University</td>
<td><a href="https://www.bellevue.edu/degrees/bachelor/data-science-bs/">BS Data Science</a></td>
<td><a href="https://www.bellevue.edu/degrees/master/data-science-ms/">MS Data Science</a></td>
<td>Fully online, 36 hrs in-major</td>
</tr>
<tr class="odd">
<td>College of Saint Mary</td>
<td></td>
<td></td>
<td><a href="https://www.csm.edu/academics/arts-science/mathematics">Only Math BS</a></td>
</tr>
<tr class="even">
<td>Concordia University</td>
<td></td>
<td></td>
<td><a href="https://www.cune.edu/academics/undergraduate/mathematics/courses">Only Math BA/BS</a></td>
</tr>
<tr class="odd">
<td>Midland University</td>
<td></td>
<td></td>
<td><a href="https://www.midlandu.edu/academics/luther-college-of-arts-sciences/mathematics/">Only Math BS</a></td>
</tr>
<tr class="even">
<td>Nebraska Methodist College</td>
<td></td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Union Adventist University</td>
<td></td>
<td></td>
<td><a href="https://uau.edu/math">Only Applied Math BS</a></td>
</tr>
<tr class="even">
<td>York University</td>
<td></td>
<td></td>
<td><a href="https://www.york.edu/registrar/catalog/2023-2024-catalog.pdf#page=145">Only Math BA</a></td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><a href="#tbl-stat-programs" class="quarto-xref">Table&nbsp;<span>6.1</span></a> demonstrates that UNL’s statistics programs are unique within the state. Other universities may offer programs in Data Science or Analytics, but these typically involve much less coursework in Statistics and will equip students for different jobs which focus on visualization or management of data rather than the analysis of data to produce useful insights. <a href="#sec-ms-prog-analysis" class="quarto-xref"><span>Section 6.4</span></a> includes a discussion of how these undergraduate Data Science and Data Analytics programs actually drive demand for UNL’s MS program, rather than competing with UNL’s BS in Statistics and Data Analytics degree. Clearly, under criteria 1.2.3, elimination of our department and its programs is inadvisable.</p>
<blockquote class="blockquote">
<ol start="4" type="1">
<li>The program is an essential program for every university.</li>
</ol>
</blockquote>
<p>Statistics programs and coursework are essential for every university with programs in science, technology, mathematics, and engineering; statistics coursework is also essential for developing quantitative reasoning skills in all undergraduate and graduate students.</p>
<blockquote class="blockquote">
<ol start="5" type="1">
<li>The program’s elimination would have a substantially negative impact on education and societal concerns in Nebraska.</li>
</ol>
</blockquote>
<p>In an era of misinformation and “alternative facts”, the quantitative reasoning skills students gain from statistics courses are of primary importance, helping students evaluate claims and evidence using the scientific method. In addition, however, Nebraska’s economy is at least significantly based on agriculture. The digital agriculture revolution has begun, and requires many more individuals to have some familiarity with data analysis and statistical computing skills. The digital agriculture minor at UNL requires three Statistics courses, two of which are primarily statistical computing. If the statistics program were eliminated, the minor’s curriculum would have to change, and would likely require at least 6 hours of coursework in computer science or the development of corresponding courses within CASNR, but without the expertise of the statistics faculty (several of us specialize in various aspects of statistical computing).</p>
<blockquote class="blockquote">
<p>Although I have no discipline expertise in those other departments, I do know that Statistics has an advantage that none of the others possess. Because I wrote in support of the Department’s planned undergraduate program in February, 2021, I know that the first cohort of students is not expected to graduate until later this year or next. Evidence from our experience here at NC State University as well as from other math/stat/cs/quantitative departments across the United States, suggests very strongly that the nascent undergraduate program will grow by leaps and bounds. Simply stated, Statistics education and training is a growth industry and will be for some time (at least until AI replaces all of us). It strikes me as shortsighted to pull the rug out from under a program that in a few years time has very strong potential to be a dean’s and provost’s bragging point. In the four years since the decision was made to start the new undergraduate program, the reasons for doing so, the wisdom of doing so, and the ROI of doing so, have all strengthened considerably. – <a href="letters/Len Stefanski-NCSU.pdf">Leonard A. Stefanski, Alumni Distinguished Professor, Statistics, NCSU</a></p>
</blockquote>
<p>“Data Science” has likewise been a buzzword over the past decade, and the data science BS programs take approximately 1/3 of their coursework from Statistics. Data science without statistics has no Science – statistics is the glue that holds the discipline together. The loss of the statistics department at UNL would seriously damage both the reputation of the program and the course offerings in Data Science, leading to difficulties across the College of Arts and Sciences and the School of Computing. These programs are essential for Nebraska students to be able to obtain training in a growing field that is only more in demand as “AI” becomes the new buzzword. Thus, under criteria 1.2.5, it is unwise to eliminate the statistics department.</p>
<blockquote class="blockquote">
<ol start="6" type="1">
<li>The program’s elimination would result in substantial loss of revenue currently derived from grants, contracts, endowments or gifts.</li>
</ol>
</blockquote>
<p>The letters received during the APC feedback process make this argument better than we could:</p>
<blockquote class="blockquote">
<p>Disbanding the department incurs immediate costs such as teach-outs, redistribution of general education and graduate methods courses, and the loss of central consulting capacity. It also leads to longer-term reductions in tuition revenue and partnerships. Equally important, grant competitiveness impressively declines: NIH, NSF, and other agencies increasingly require statisticians as co-investigators and insist on prespecified analyses, rigorous design, and reproducible workflows. Proposals lacking these elements tend to perform worse, resulting in fewer awards and a smaller overhead base for the university in the future. In my experience, the lack of a statistician among the core investigators on a research grant has almost always been a notable weakness in every panel I have been involved with, even with the new grant format. – <a href="letters/Guindani_UCLAbiostat.pdf">Michele Guindani, Professor, UCLA Biostatistics, ASA Fellow, ISI elected member, ISBA Fellow, past Editor in Chief of Bayesian Analysis, Statistics Membership Engagement Chair, AAAS</a></p>
</blockquote>
<blockquote class="blockquote">
<p>In addition, the Department of Statistics, both via teaching and consulting has been and continues to be an integral part of the research performed by IANR and the Beadle Center. These groups continue to garner a large share of the total research grants awarded to the University. Statistics faculty are consistently integral to the design, analysis, and interpretation of nationally important studies. If we are serious about remaining an “R1” university, much less regaining AAU status, we absolutely need these people, the courses they teach, and the help they provide. In my professional judgment this is best done by retaining a stand-alone Department of Statistics. The alternative is to hire MOST of these professors as faculty in other departments—they are integral to our success.</p>
<p>My wife and I have donated nearly a million dollars to UN-L, and have helped raise millions more through the University of Nebraska Foundation—you are welcome to check with them. I see no reason to continue if UN-L can no longer have strong programs in these fields. – <a href="letters/ThomasHoegemeyer.pdf">Thomas C. Hoegemeyer, Ph.D.</a></p>
</blockquote>
<p>It is clear that the reputation damage to UNL from eliminating the department will increase the scrutiny of grants written by UNL PIs at NSF, NIH, and other federal agencies. In addition, UNL alumni recognize that eliminating statistics has a profound effect on the competitiveness of UNL programs, and this will have an effect on donations through the NU foundation as well as direct donations to the university. As such, criteria 1.2.6 supports APC recommending that UNL keep the Statistics department and programs intact.</p>
<blockquote class="blockquote">
<ol start="7" type="1">
<li>The program represents a substantial capital investment in specialized physical plant or equipment that could not be effectively redirected to alternative uses.</li>
</ol>
</blockquote>
<p>The Statistics program has invested significant sweat equity in developing our SDAN major, but we expect that this is not what the criteria refers to. In reality, Statistics is relatively inexpensive for the value it provides to the university - we require only chalkboards, paper, computers, and coffee to function (and the university isn’t expected to provide the coffee).</p>
<blockquote class="blockquote">
<ol start="8" type="1">
<li>The program is central to maintaining the university’s affirmative action goals.</li>
</ol>
</blockquote>
<p>Statistics is an incredibly diverse field - unlike Mathematics and most other STEM fields, Statistics has an approximately even distribution of men and women. We also have considerable racial diversity in the field, which helps us to recruit graduate students who self-pay from other countries.</p>
<blockquote class="blockquote">
<ol start="9" type="1">
<li>The program gives the University of Nebraska-Lincoln its distinctive character.</li>
</ol>
</blockquote>
<p>UNL is well known for agronomy, engineering, and business programs, including prestigious programs such as the Raikes school. All of these fields heavily depend on statistics, and require coursework in statistics as well as input from statisticians to successfully compete for research grants. While the department may not give UNL its distinctive character, it functions as very necessary but often invisible structural support for a number of UNL’s most distinctive programs. As a result, under criteria 1.2.9, the department should not be eliminated.</p>
</section>
<section id="addressing-criteria-indicating-that-reduction-is-inadvisable" class="level3" data-number="6.1.3">
<h3 data-number="6.1.3" class="anchored" data-anchor-id="addressing-criteria-indicating-that-reduction-is-inadvisable"><span class="header-section-number">6.1.3</span> Addressing Criteria Indicating that Reduction is Inadvisable</h3>
<blockquote class="blockquote">
<ol type="1">
<li>The program’s nature is such that reduction would impair the critical mass necessary to have adequate quality.</li>
</ol>
</blockquote>
<p>The statistics department is operating on the minimum FTE which could reasonably offer programs at the undergraduate, MS, and Ph.D.&nbsp;levels. Any reduction in headcount would force the department to choose between the undergraduate programs that are predicted to increase the profitability of the department in the future, and the graduate programs that facilitate the consulting, service, and research missions of the department.</p>
<blockquote class="blockquote">
<ol start="2" type="1">
<li>The program cannot be reduced without a substantial risk to accreditation.</li>
</ol>
</blockquote>
<p>Statistics programs are not externally accredited, but criteria 1.3.1 addresses the risks of reduction to our programs.</p>
<blockquote class="blockquote">
<ol start="3" type="1">
<li>Current projections indicate that demand for the program or its graduates will increase substantially within the next five years.</li>
</ol>
</blockquote>
<p>Every external opinion suggests that BS programs in Statistics and Data science are experiencing increasing enrollment and that economic demand for graduates of these programs is also increasing. We strongly believe that enrollment in the statistics and data science programs will increase once we begin graduating students and can advertise based on their job or graduate school placement. However, we will acknowledge that there is some friction in offering our undergraduate program within the College of Ag Science and Natural Resources. Current students suggest that CASNR prerequisites and general education requirements are unappealing relative to the freedom of CAS and COE requirements, which may account for the low enrollment in CASNR’s data science program.</p>
<blockquote class="blockquote">
<p>Indeed, workforce realities cut the same way. Student demand for statistics and data science is sustained and high, and employers across tech, biotech, finance, climate, and government hire at every degree level. Closing a department in the face of that demand misaligns the university with student interest and employers’ need, ceding enrollments, tuition, and partnerships to peer institutions that are expanding, often by re-forming as “Statistics &amp; Data Science” and integrating computation with inference. – <a href="letters/Guindani_UCLAbiostat.pdf">Michele Guindani, Professor, UCLA Biostatistics</a></p>
</blockquote>
<p>We think it likely that enrollment would be higher if our undergraduate program were located within the School of Computing (thinking back to the 1968 plan to create a School of Computing with Statistics and Computer Science departments) or within the College of Arts and Sciences<a href="#fn3" class="footnote-ref" id="fnref3" role="doc-noteref"><sup>3</sup></a>. Regardless, every expectation is that enrollment in our undergraduate programs will continue to increase for some time. Our graduate programs may increase in demand, but capacity will continue to be primarily determined by the number of faculty, as graduate students require a substantial investment of faculty time. Thus, under criteria 1.3.3, reduction in the size of the department is inadvisable.</p>
<blockquote class="blockquote">
<ol start="4" type="1">
<li>Scholarly research or creative activity of the faculty within this program, as shown by publications, creative productions, honors and awards, external funding, or other objective measure, is higher than others in the same or related peer disciplines.</li>
</ol>
</blockquote>
<p><a href="metrics.html#fig-sri-by-class" class="quarto-xref">Figure&nbsp;<span>4.2</span></a> shows that UNL’s statistics department has a scholarly research index (as computed by Academic Analytics) comparable to AAU universities and at the top of non-AAU R1 institutions. This suggests that reduction is inadvisable under criteria 1.3.4.</p>
</section>
</section>
<section id="effects-of-proposed-cuts-on-outside-programs" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="effects-of-proposed-cuts-on-outside-programs"><span class="header-section-number">6.2</span> Effects of Proposed Cuts on Outside Programs</h2>
<blockquote class="blockquote">
<p>Statistics departments have been flourishing across the country. They are vital in terms of being at the foundation of Data Science. They bring in more external funding per capita than almost every department on a Liberal Arts campus. They provide support and an invaluable resource for research investigation across the entire institution. should be viewed as one of the most valued groups on the campus. I can assure you, speaking as a former Department chair and long time faculty member, that this is certainly the perspective of Duke University. …<br>
This elimination decision, if enacted, would dismantle a vibrant department that has long served as a cornerstone of fundamental research in Statistics, interdisciplinary research, graduate education, and statistical consulting across the university and beyond. I strongly urge you to reconsider this drastic action. – <a href="letters/Allan Gelfand.pdf">Alan E. Gelfand, James B. Duke Professor of Statistical Science and Professor of Environmental Science and Policy, Duke University.</a></p>
</blockquote>
<section id="mathematics" class="level3" data-number="6.2.1">
<h3 data-number="6.2.1" class="anchored" data-anchor-id="mathematics"><span class="header-section-number">6.2.1</span> Mathematics</h3>
<p><a href="documentation/Effects of Proposed Cuts to Undergraduate Program-Math.docx"><em>This section was contributed by Alex Zupan, Undergraduate Chair, Mathematics, and Doug Pellatz, Senior Academic Advisor, College of Arts and Sciences</em></a></p>
<p>Cutting the Department of Statistics will have significant and lasting effects on the undergraduate program in the Department of Mathematics. Elimination of courses will be most deeply felt by students majoring in CAS Data Science and by students pursuing the Statistics and Data Science Option and Mathematical Finance Option within the Mathematics major. We were relieved to see IANR’s plan to continue to offer STAT 218, 318, 380, 462, and 463, which means there would be sufficient Statistics courses offered to complete the Data Science major and the Math major on the Mathematical Finance and the Statistics and Data Science options<a href="#fn4" class="footnote-ref" id="fnref4" role="doc-noteref"><sup>4</sup></a>. However, the Statistical Modeling focus area of the Data Science major would likely need to be eliminated or greatly revised considering the proposed cuts. There would also be far fewer Statistics course options available with the Statistics and Data Science option of the Math major.</p>
<p>As of the beginning of the fall 2025 semester, a total of 26 students had declared a Math major within the Statistics and Data Science option, and 21 students had declared within the Mathematical Finance option. The number of students graduating in the former option has been continuously increasing since the introduction of this option in 2020. The CAS Data Science major has seen even more dramatic increases, with 17 declared majors in the fall of 2023, 59 declared majors in the fall of 2024, and 83 declared majors in the fall of 2025. The curriculum for these majors is well-balanced between Math, Computer Science, and Statistics courses, with input and shared leadership among all three departments, and we view this major as one of the most interdisciplinary majors in the university. Losing the statistics department would be a significant blow to this valued interdisciplinarity.</p>
<p>One motivating factor for the steep growth curve of the Data Science program is a strong positive jobs outlook. This field is highly regarded across disciplines. In a 2023 conversation with Stephen Cooper, the former Director of the Raikes program, he declared that within five years, he expected most Raikes students would have Data Science as one of their majors. Cutting one of the three pillars of the Data Science major would almost certainly hamper this growth. Students graduating within the Statistics and Data Science option of the Math major have thus far had excellent internship and career prospects. When they graduate, we ask students to fill out a voluntary exit survey, and in 2024 and 2025, students in this option have reported completing internships at companies such as Kiewit, 84.51°, the Federal Reserve Bank of Kansas City, and they report having jobs as data scientists, software engineers, and a number of other positions.<br>
This field and its employment prospects are enjoying a wave of growth and popularity, and we can choose to grow with it, or we can hamstring our efforts with cuts that may ultimately prove to be shortsighted.</p>
<p>Finally, we understand that statistics courses will continue to be taught at UNL, but we have grave concerns about the long-term ability of the university to attract high-achieving statistics faculty with modern knowledge about a quickly evolving field, the type of faculty members who can provide high-quality instruction to our majors and who have the expertise to lead undergraduate research projects in data science.<br>
The department has been in conversations about our curriculum with Bill Anderson, a retired data science expert who held leadership positions at Microsoft, United Healthcare, and Ford, and who has consulted for senior design groups within the Raikes School. In a recent meeting, Bill reported that the use of statistics in the real world is dramatically changing.<br>
The meteoric rise of AI tools has enabled data scientists to implement new solutions with unprecedented speed, but according to Bill, these solutions require statistics for measurement – to determine to what extent new techniques are working and whether they are reliable, ethical, and fair – and the industry has not yet fully realized this need. Our Data Science majors, with their unique synthesis of mathematical, computing, and statistical knowledge are well-positioned to be leaders in their fields upon graduating from UNL, and without a thriving Department of Statistics, we may not be able to continue making this assertion with confidence.</p>
</section>
<section id="university-wide-impact" class="level3" data-number="6.2.2">
<h3 data-number="6.2.2" class="anchored" data-anchor-id="university-wide-impact"><span class="header-section-number">6.2.2</span> University-Wide Impact</h3>
<p>The statistics department teaches courses which are required for degree programs across the university.</p>
<blockquote class="blockquote">
<p>The plan proposes to strategically deploy a portion of state-appropriated funds to continue to offer:</p>
<ul>
<li>Critical student competencies. Undergraduate and graduate students would continue to gain essential skills in statistics and data analytics for their future careers. We anticipate course offerings would include STAT 218, STAT 380, STAT 801, STAT 802, STAT 870, complemented by additional coursework in R programming, bioinformatics, computational biology, quantitative genetics/genomics, and data analysis interpretation and visualization offered through other units.</li>
</ul>
</blockquote>
<p>Unfortunately, the budget proposal has massively under-estimated the importance of statistics in curricula across campus, as shown in <a href="#tbl-stat-courses-reqd" class="quarto-xref">Table&nbsp;<span>6.2</span></a>.</p>
<div class="cell">
<div id="tbl-stat-courses-reqd" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-stat-courses-reqd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6.2: Statistics courses required by other programs across campus. The budget proposal calls for maintaining some statistics courses; programs which require courses that will not be offered are highlighted.
</figcaption>
<div aria-describedby="tbl-stat-courses-reqd-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="table do-not-create-environment cell caption-top table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Program</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Level</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">College</th>
<th style="text-align: left;" data-quarto-table-cell-role="th">Classes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left; width: 15em;">Fisheries and Wildlife</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218 or STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Forensic Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Environmental Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Animal Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Regional and Community Forestry</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218 or STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Agricultural Leadership, Education and Communication, Agricultural and Environmental Sciences Communication Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Grassland Systems</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Plant Biology</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Insect Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Agricultural Economics, Quantitative Analysis Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Agricultural Systems Technology</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Biochemistry (CASNR), Computational and Systems Biochemistry Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CASNR</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Digital Agriculture Minor</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CASNR</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 151, 251, 218</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Actuarial Science (CAS)</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CAS</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 462, 463</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Biochemistry (CAS), Computational Biochemistry Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 218</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Meterology-Climatology</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Actuarial Science (Business)</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">Business</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 462, 463</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Secondary Education: Mathematics</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CEHS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Software Engineering</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Computer Science</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Mathematics, Education Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Mathematics, Mathematical Biology Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Mathematics, Mathematical Finance Option</td>
<td style="text-align: left;">UG</td>
<td style="text-align: left;">CAS</td>
<td style="text-align: left; width: 15em;">STAT 380</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Mathematics, Statistics and Data Science Option</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CAS</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 380, 2 additional 300/400 level STAT courses</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Data Science, CAS</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">CAS</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 218 or 380 + STAT 318 -or- STAT 101 + STAT 102; Included in focus areas: STAT 251, 351, 212, 301, 302, 325, 412, 414, 432, 443, 450, 462, 463, 464, 474, 475, 478, 468</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Data Science, Engineering</td>
<td style="text-align: left; background-color: yellow !important;">UG</td>
<td style="text-align: left; background-color: yellow !important;">Engineering</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 218 or 380 + STAT 318 -or- STAT 101 + STAT 102; Included in focus areas: STAT 251, 351, 212, 301, 302, 325, 412, 414, 432, 443, 450, 462, 463, 464, 474, 475, 478, 468</td>
</tr>
<tr class="odd">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Agricultural Economics, PhD</td>
<td style="text-align: left; background-color: yellow !important;">G</td>
<td style="text-align: left; background-color: yellow !important;">CASNR</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">STAT 882</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Complex Biosystems, PhD</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;"></td>
<td style="text-align: left; width: 15em;">STAT 801</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Biomedical Engineering, PhD</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">3 credits of graduate level statistics</td>
</tr>
<tr class="even">
<td style="text-align: left; width: 15em;">Biological Engineering, PhD</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">3 credits of graduate level statistics</td>
</tr>
<tr class="odd">
<td style="text-align: left; width: 15em;">Civil Engineering, PhD; specialization in Transportation</td>
<td style="text-align: left;">G</td>
<td style="text-align: left;">Engineering</td>
<td style="text-align: left; width: 15em;">STAT 801</td>
</tr>
<tr class="even">
<td style="text-align: left; background-color: yellow !important; width: 15em;">Finance, PhD</td>
<td style="text-align: left; background-color: yellow !important;">G</td>
<td style="text-align: left; background-color: yellow !important;">Business</td>
<td style="text-align: left; background-color: yellow !important; width: 15em;">9 credits in graduate level statistics</td>
</tr>
</tbody>
</table>


</div>
</div>
</figure>
</div>
</div>
<p>In addition to the listed courses, many graduate statistics courses are taken as electives (or graduate committee-level requirements) to ensure that students have appropriate quantitative training for their research topics and fields. Courses like Stat 850 – Computing Tools for Statistics – teach R and python “data wrangling” skills, data visualization, reproducible research, and statistical simulation. The undergraduate computing sequence, Stat 151, 251, and 351, are similarly useful across multiple disciplines, though these courses were developed for the statistics undergraduate program. Relatively quickly after the courses were created, the Digital Agriculture minor was created with the requirement that students take Stat 151 and 251. Similarly, we believe that Stat 349, Technical Skills for Statisticians, might be useful to students in Computer Science who need a technical writing course, though this potential was only identified recently, and we would need to get ACE 2 certification for the course.</p>
<p>Statistics is one of three departments participating in the cross-college Data Science majors program; even though CASNR has indicated a desire to eliminate their Data Science option, there are still students in two other colleges who are required to take multiple statistics undergraduate courses for the major. Many focus areas require statistics courses, and the Statistical Modeling option would be impossible to complete without our courses. The credibility of a Data Science degree without the participation of statisticians is questionable - statistics is the foundation of data science, and many variations of “data science is a sexy word for statistician<a href="#fn5" class="footnote-ref" id="fnref5" role="doc-noteref"><sup>5</sup></a>” have been uttered at different points as the phrase “data science” caught on.</p>
<p>The proposed budget reduction plan does not account for the costs of teaching Stat 218, 380, 801, 802, and 870. Currently, some of these courses are taught by graduate TAs, who will no longer exist if the graduate program is closed. The remainder of the courses are taught by Statistics faculty, who are slated to be eliminated as well. The one remaining head of consulting cannot physically teach all of the sections of Stat 218 which are currently taught, let alone teaching 380, 801, 802, and 870 on top of the Stat 218 courses. Stat 218 is taken by approximately 20% of undergraduates at UNL and is an extremely important course for building quantitative literacy among undergraduate students. Without a plan to ensure that Stat 218 is taught by people who understand statistical pedagogy, this proposal will majorly weaken quantitative education at UNL and diminish the value of a UNL degree.</p>
</section>
</section>
<section id="undergraduate-program" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="undergraduate-program"><span class="header-section-number">6.3</span> Undergraduate Program</h2>
<p>At the request of the CASNR Dean, our department has implemented an undergraduate program in Statistics and Data Analytics (approved 2021, first cohort 2022) and is an important component of the undergraduate Data Science programs in CASNR, School of Computing, and the College of Arts and Science (approved 2022). The undergraduate program requires 51 hours of statistics coursework, making it unique within the ecosystem of undergraduate statistics programs; this was a deciding factor for several of our current students who chose UNL over other universities offering statistics degrees.</p>
<p>The department has developed the new courses for this program<a href="#fn6" class="footnote-ref" id="fnref6" role="doc-noteref"><sup>6</sup></a>, and has implemented this program without any additional TT faculty or professors of practice positions intended to assist with the additional course load. These additional courses may be reflected in the metrics in some ways – it is possible that research output might have decreased slightly given the large increase in teaching and course design load, as was predicted by the review team in the 2021 APR if we did not continue to increase the department size to manage the increased course load.</p>
<blockquote class="blockquote">
<p>The main resources needed to implement the undergraduate Statistics and Data Analytics major and the forthcoming Statistical Data Science major are people and energy. The major requires the development of a considerable number of new courses. To develop these courses with only the existing faculty would require major sacrificees to faculty research programs and to their ability to collaborate with IANR and other faculty at UNL. New faculty will need to be hired to develop coursework for the majors. - <a href="documentation/2021-STAT-APR-Report.pdf">2021 APR Report</a></p>
</blockquote>
<p>However, we do not think that this is the case: research output in the department has been relatively steady over the last 5 years, and some of the faculty most burdened by course development have also had record numbers of publications accepted.</p>
<p>What is clear is that the additional resources promised by IANR to allow the department to successfully develop, deliver, and grow the undergraduate SDAN and Data Science programs never arrived. Faculty have been so busy developing the courses to ensure that students can graduate on time that we have not had additional time or energy to devote to recruitment and outreach across campus. The proposed elimination of our department sends signals across campus that:</p>
<ul>
<li>new program development will put your department at risk during the inevitable next round of budget cuts, as the metrics won’t account for the development of the program, and</li>
<li>extending the department beyond current FTE on the promise of future resources is not a risk worth taking.</li>
</ul>
<p>New program development is an <strong>investment</strong> in the future of the university and an investment in the people of this state, which should pay dividends to the people of the state through increased economic activity, better educational opportunities, and increased quality of life. Eliminating the statistics department before we can graduate our first cohorts of Statistics undergraduates is like buying a new stock offering high and selling during a dip, losing money and also the opportunity to capitalize on the gains as the stock matures.</p>
<blockquote class="blockquote">
<p>The development of new undergraduate majors is very important not only to UNL but more broadly to the state of Nebraska given the urgent need for highly trained statisticians and data scientists. Furthermore, this program will generate substantial resources for IANR; the department needs resources to develop, deliver, and grow these programs. - <a href="documentation/2021-STAT-APR-Report.pdf">2021 APR Report</a></p>
</blockquote>
<p>CCPE guidelines require that programs have been operating for at least 5 years (and more practically, 9 years) before evaluation, because 5-year graduation rates and cohort sizes are part of the evaluation criteria. The Statistics BS program has only been operating for 3 years, making an evaluation of the program based on cohort sizes very premature.</p>
<blockquote class="blockquote">
<p>As you will be aware, the department has recently established an innovative undergraduate programme designed to train the computationally skilled applied statisticians and data scientists that the private and public sectors everywhere (in my experience) are trying to find. The first cohort will graduate soon. The department has significant expertise in this area, and your institution is about to see the benefits. – <a href="letters/Thomas Lumley.pdf">Thomas Lumley, Chair of Biostatistics, Professor of Statistics, University of Auckland</a></p>
</blockquote>
<p>Many of the internal and external letters urged the university to reinvest in the statistics department.</p>
<blockquote class="blockquote">
<p>This is not the moment to dismantle capacity—it is the moment to strengthen it. UNL should not only preserve but actively invest in the Statistics Department, building on its proven strengths in data science, analytics, and applied research. Doing so will ensure that UNL fulfills its mission as a land- grant institution, supports Nebraska’s industries, and positions the university for long-term success in an increasingly data-driven world. – <a href="letters/Zhenghong Tang-CRPchairUNL.pdf">Zhenghong Tang, Professor and Associate Dean for Research and Innovation, College of Architecture</a></p>
</blockquote>
</section>
<section id="sec-ms-prog-analysis" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="sec-ms-prog-analysis"><span class="header-section-number">6.4</span> Graduate Programs</h2>
<p>UNL’s MS program serves as an integral part of the ecosystem of statistics and data science in Nebraska.</p>
<blockquote class="blockquote">
<p>Doane has maintained a productive relationship with UNL’s Statistics graduate programs. We utilize Dr.&nbsp;Chris Bilder’s excellent textbook in our MTH316 Categorical Analysis course, and several of our alumni have successfully matriculated to your program. Two of our alumni will complete their master’s degrees this spring, fortunately before any potential program closure. Three of our current seniors are planning to apply this spring, assuming the program remains available. Our successful alumni who completed UNL’s Statistics program include these leaders, who have risen to the top of their organizations:</p>
<ol type="1">
<li>Billy Garver, UNL Statistics M.S., 2013, Chief Compliance Officer &amp; Co-owner, Leibman Financial Services, Louisville, NE <em>Donated over $100,000 to Doane last year</em></li>
<li>Julie Couton, UNL Statistics Ph.D., 2017, Senior Data Scientist, Incredible Health</li>
<li>Katie Kallenbach, UNL Statistics M.S., 2012, Statistician, USDA</li>
<li>Zack Gabelhouse, UNL Statistics M.S., 2005, Director of Client Strategy, Deluxe Corporation</li>
</ol>
<p>– <a href="letters/PeggyHart-UNLmathStatAlum_DoaneProf.pdf">Peggy Hart, Ph.D.&nbsp;Statistics, UNL. Associate Professor of Mathematics &amp; Data Analytics, Doane University</a></p>
</blockquote>
<p>UNL tried to establish a Ph.D.&nbsp;program for at least 50 years before it was actually established in 2003 with the formation of the Department of Statistics. It is worth examining the motivating factors behind the creation of the Ph.D.&nbsp;program before examining the program itself.</p>
<p>In the 1993 Biometry APR Self-Study, the following reasons were provided; they have been summarized here for brevity, but can be found on pages 28-30 of the <a href="documentation/1993-Biometry-APR-SelfStudy.pdf">self-study report</a></p>
<ul>
<li>Graduate student recruiting: good students will want a program that offers a Ph.D.&nbsp;in addition to a M.S.</li>
<li>Research efficiency: accumulated consulting-inspired research problems can be addressed by graduate students.</li>
<li>Consulting efficiency: consulting-inspired research and methodology development fuels Ph.D.&nbsp;dissertations. In addition, graduate students can do statistical consulting, providing additional capacity.</li>
<li>Teaching efficiency: Labs for graduate courses cannot be easily taught by MS students until they have taken the course.</li>
<li>Faculty professional development: time constraints limit faculty ability to develop new areas of expertise.</li>
<li>Enhanced value of Biometry to IANR, UNL, and Nebraska. Statistical quality control improves economic efficiency. A Ph.D.&nbsp;program could make meaningful contributions to the state economy.</li>
</ul>
<p>The graduate programs at UNL were motivated primarily by the consulting and service missions of the Biometry department. Corresponding programs in Mathematics &amp; Statistics on City campus provided the ability to get Math degrees with concentrations, focus areas, or minors in Statistics, and seem to have developed from demand rather than necessity.</p>
<p>If the department of Statistics is eliminated along with its programs, leaving only 1 FTE to do statistical consulting, that one person will very quickly find themselves inundated with more work than one person could do in a decade. The consulting desk currently requires the support of 5 graduate statistics students who work at least 100 hours a week on consulting problems (the true total is likely higher).</p>
<p>In addition, development of new methodology in statistics and in applied domains including agronomy and animal science, the natural product of statistical consulting, will effectively cease. The current proposal indicates that Stat 801 and 802 will continue to be offered; these are the graduate courses which required graduate TA support in 1993 and still require that support today<a href="#fn7" class="footnote-ref" id="fnref7" role="doc-noteref"><sup>7</sup></a>.</p>
<p>Our graduate students are extremely in-demand: to our knowledge, every MS and Ph.D.&nbsp;graduate in statistics has found work in their field, whether in industry, government, or academia. While our undergraduate students have not yet graduated (May 2026 will be the first cohort’s graduation date), Many of these students mentions feeling uniquely empowered to work in <em>many</em> fields using their Statistics degree. This sentiment goes back to John W. Tukey: <a href="https://www.stat.berkeley.edu/~brill/Papers/copssbrill.pdf">“The best thing about being a statistician,” he once told a colleague, “is that you get to play in everyone’s backyard.”</a>.</p>
<p>We feel that it is more effective to allow our graduate students and graduates to speak about the UNL Statistics program - it is well designed, though like any other program could use some updates, but it is far more important to show how effective it is at equipping students for careers in Statistics.</p>
<blockquote class="blockquote">
<p>When I graduated, I felt like a kid in a candy shop – I could take my newly acquired skills into literally any industry. I eventually landed in retail marketing. In my first job, even though my co-workers were all data analysts and modelers, none of them had a background in Statistics, so it was rewarding to help improve our processes with more statistically sound methods, improving turnaround timing, accuracy, and insights. – <a href="letters/DanaCraker-MSgrad.pdf">Dana Cracker, MS Statistics (2008) from UNL</a></p>
</blockquote>
<p>While the department has produced excellent researchers who are very well known in the field, these same graduates remember the department not only as laying the foundation for their academic and economic success, but for its supportive environment and mentoring. While this quote is long, it is still only a fraction of the original letter (and we’ve trimmed sections for brevity), and the story is important for motivating the importance of statistics to this state as well as highlighting unique characteristics of this department’s programs.</p>
<blockquote class="blockquote">
<p>I would like to explain how the Department of Statistics transformed me—a first-generation college graduate and son of a living Nebraska veteran who has spent 49 years paralyzed—from a mediocre high school graduate to a full professor at an R1 university by age 38.<br>
…<br>
As a Lincoln native, I was a first-generation college applicant with close to the bare minimum requirements to be admitted as an undergraduate student at UNL. I was fortunate to have Chapter 35 GI Bill benefits and a tuition waiver from the Nebraska Department of Veterans Affairs. This enabled me to fully dedicate myself to the fisheries and wildlife program within the School of Natural Resources. Very early in my undergraduate career, I realized two things. First, while I found the fisheries and wildlife undergraduate program fun, engaging, and beneficial, a career directly in that field was better suited for students with tremendous family support, both financially and in caregiving. Second, I could still do what I love —working on important environmental problems —and get paid well as a statistician. And so, I forged a path forward and created a program that should have but didn’t exist at UNL. I took about a dozen statistics and related classes. I engaged with several current faculty members in the Department of Statistics, who were instrumental in ensuring I succeeded in upper-level and even graduate-level statistics classes during my undergraduate studies and helped with my UCARE project. I graduated in 2010 with Highest Distinction and 169 credit hours (enough for a triple major at most universities). But it was 2010, there was a financial crisis, no jobs and all I had was a nearly worthless degree in fisheries and wildlife. With little or no job prospects, I remember thinking that it sure would have been nice to have an undergraduate degree in statistics at UNL—something most other R1 universities have. Sure, I had an undergraduate experience that resulted in four published scientific papers, but having that statistics degree would have made me employable. I would also like to add that I did all this while being the sole caretaker for my father, the Nebraskan veteran who has spent 49 years paralyzed and still lives in Lincoln.<br>
…<br>
In what I can only describe as pure luck, UNL landed an NSF IGERT award in 2009, and I was fortunate to be selected to be part of that program. This was by far the best-paying “job” I could find at the time. This enabled me to obtain a graduate fellowship and pursue the first joint PhD in Statistics and Natural Resources Sciences, which I finished in three years and nine months. And again, I did all of this as the sole caretaker for my father, which included a gruesome injury that resulted in a leg amputation during my first year as a PhD student. I am truly grateful for the faculty of the Department of Statistics at UNL, who created an environment where I could thrive despite what was going on in my personal life.<br>
…<br>
The rest of the story is short and academic. I would write my first 500+ page graduate-level textbook on Bayesian statistics by age 32, tenured at age 34, co-director of an institute at age 36, and full professor with 80+ published papers by age 38. While all of these personal boasts are research-heavy, I am most proud of my teaching evaluations and students. Statistics, unlike many of the undergraduate degrees offered at UNL, enables students from lower-and middle-class Nebraska families a path to an engaging, fun and well-paying career. – <a href="letters/Hefley_PhDgrad.pdf">Trevor Hefley, Ph.D.&nbsp;Statistics, UNL. Professor &amp; Co-director, Institute for Digital Agriculture and Advanced Analytics, Kansas State University</a></p>
</blockquote>
<p>More recent graduates also highlight the local, national, and international demand for Statistics degrees and the economic success that comes along with a graduate degree from our department.</p>
<blockquote class="blockquote">
<p>I am a 2023 PhD graduate from the Department of Statistics at UNL. I earned my BS in Statistics in 2011, my MS in 2018, and finally my PhD in 2023. My connection to statistics goes back even further since my father worked as a Statistician for the Government of India for more than 35 years. This field has been an inseparable part of my life, and I owe much of my career success to the excellent training and mentorship I received at UNL. I currently work in the technology industry as an Artificial Intelligence engineer, building large-scale solutions that are used globally.<br>
… Graduates of the department have consistently shown their value in the job market. Many of my peers went on to work for the US government, leading universities, major insurance companies, and global technology firms. Personally, I was able to intern at LinkedIn and IBM and later received offers from Meta, Adobe, Travelers Insurance, Liberty Mutual, Mutual of Omaha, and Hudl. These opportunities would not have been possible without the rigorous training I received at UNL. The department’s track record in placing graduates in top positions is also a powerful tool for recruiting future students. – <a href="letters/VedPiyushPhD.pdf">Ved Piyush, Ph.D.&nbsp;Statistics (2023), UNL</a></p>
</blockquote>
<p>Our students are equipped to work as consultants, professors, and researchers across university systems.</p>
<blockquote class="blockquote">
<p>The Statistics Department played a defining role in my academic and professional journey. Through my time as a graduate student, I gained extensive teaching experience in undergraduate statistics courses, worked on consulting projects as part of my coursework, and received continuous support and mentorship from faculty. These experiences equipped me with the skills and confidence I now rely on in my career as an Assistant Professor of Statistics. Without the training and guidance of this department, I would not be where I am today. – <a href="letters/AleenaChanda-PhDgrad.pdf">Aleena Chanda, Ph.D.&nbsp;Statistics (2025), Assistant Professor, Juniata College.</a></p>
</blockquote>
<p>Our graduate students sometimes fall in love with the state and don’t want to leave, finding jobs that enrich Nebraska’s economy. UNL’s statistics programs directly counter “brain drain”, providing local employers with an important source of trained professionals in in-demand fields.</p>
<blockquote class="blockquote">
<p>I am not from Nebraska originally and did not consider moving here prior to receiving an offer from the statistics department. However, once I got to Lincoln I not only learned a lot but fell in love with the area. I was thrilled when I got a job as a data analyst in Omaha. My employers told me that I was hired specifically because of my experience in the statistics department.<br>
…<br>
I have never been surrounded by as many smart, caring, and hard-working people as I was in the Department of Statistics. Nearly all of these people, similar to myself, come from out of state, with many coming from out of the country. All of these people gave up their old lives to come be a part of UNL, the city of Lincoln, and the state of Nebraska. Without another program like ours in the state, they and future potential students will take their great talents elsewhere and contribute to the “brain drain” happening in Nebraska. I previously mentioned how much I love the area, but if this decision is finalized, I am concerned about the long-term outlook of the state and my future here. – <a href="letters/Ryan Lalicker-MSalum.pdf">Ryan Lalicker, MS Statistics, 2025</a></p>
</blockquote>
<p>Our department provides opportunities for students to get an education that will improve their economic prospects and the state’s economy as well. Statistics Ph.D.s working in industry have a median salary of $195,000 (<a href="documentation/YCR-2020WorkandSalarySurvey.pdf">ASA 2020 compensation survey</a>, pg 13), while those with a M.S. working in industry have a median salary of $150,000. Getting a graduate degree in statistics can <strong>meaningfully change a student’s economic outlook</strong>.</p>
<blockquote class="blockquote">
<p>Impact on graduate students<br>
I am a Nebraska native, who was able to attend UNL thanks to a Regents Scholarship. Without the grants and graduate assistantships I received through the Department of Statistics, I would not have been able to afford graduate school, and most likely would have left Nebraska. Instead, I discovered a passion for statistics and data science education because I was encouraged to experiment and take risks as an instructor. I built a career in academia and industry as a data science educator because of the opportunities I had at the department. – <a href="letters/Aimee Schwab-McCoy-Senior Manager-Wiley-UNL_grad.pdf">Aimee Schwab-McCoy, Senior Manager for Content Authoring – Data Science, Mathematics, and Statistics, Wiley</a></p>
</blockquote>
<p>While not all of our statistics graduates stay in Nebraska, many go on to make important contributions in a variety of fields, including pharmaceuticals and drug regulation, that are incredibly important to ensuring quality of life for Nebraskans.</p>
<blockquote class="blockquote">
<p>As a graduate student (2005-2010), I was approached by my PhD advisor Walt Stroup, professor and Chair of the Department of Statistics at the time, with the opportunity to become a member along with him of the Product Quality Research Institute (PQRI) Stability Shelf Life Working Group (SSL WG) to expand their initial research on shelf life estimation. I accepted this opportunity and was able to work along with members of industry, academia, and FDA to assess the current methodologies for shelf life estimation of pharmaceutical products. This research led to my dissertation topic and completion of my PhD requirements.<br>
The UNL faculty’s extensive knowledge and expertise proved vital in helping me communicate statistical aspects to the SSL WG, allowing me to bridge the gap between academic/statistical theory and real world problems in ways non-statisticians could understand. The opportunity to become a member of the SSL WG provided valuable experiences in collaborative research and impact outside the UNL community. The Department of Statistics provided me the academic background and developed my consulting skills, allowing me to analyze data from clinical trials and successfully explain statistical concepts to drug developers and researchers at Novartis. My education provided invaluable influence on my professional development and involvement in bringing several new drugs to market at Novartis. – <a href="letters/MichelleQuinlanPhDgrad.docx.pdf">Michelle Quinlan, Ph.D.&nbsp;Statistics and Director of Biostatistics, Early Development Analytics, Novartis Corporation</a></p>
</blockquote>
<p>Many students mention the consulting projects that helped them build the skills they rely on as professional statisticians, demonstrating that not only is SC3L important to the IANR research community and to many departments across UNL, but it is also an important component of our graduate training. UNL requires consulting training at both the MS and Ph.D.&nbsp;level, and these classes support the help desk while ensuring that every UNL graduate is prepared to collaborate and consult with non-statisticians, carefully applying statistical training to domain problems.</p>
<blockquote class="blockquote">
<p>During my time in the department, I benefited from exceptional faculty mentorship, rigorous training, and a vibrant intellectual community that continues to shape my work as a Biomedical Data Scientist at the University of Kentucky (UKY). My work colleagues and faculty mentor at UKY complemented my statistical consulting and collaboration skills, as well as the knowledge I learned on the statistics fundamentals. I would never have been in the place I was leaving graduate school if not for the support of the faculty in this department. Their comprehensive curriculum over the years, including experimental design, regression, multivariate, and categorical analyses, spatial and time-series modeling, and more, prepared students to enter the workforce with highly sought-after skills. In addition to my own training, I contributed to the department’s growth by working alongside Dr.&nbsp;Kathy Hanford, Dr.&nbsp;Reka Howard, Dr.&nbsp;Walt Stroup, and Dr.&nbsp;Bert Clarke to strengthen the Statistical Consulting and Cross Collaboration Lab (SC3L). The SC3L has become a cornerstone of research support across the university, assisting countless students and faculty in producing higher-quality, more rigorous research. Graduate students and faculty in the department have served as collaborators or consultants on hundreds, if not thousands, of research projects, theses, dissertations, and peer-reviewed manuscripts. These contributions are foundational to maintaining UNL’s status as a top-tier R1 research university. Without this support, students across the university would lose access to critical expertise in applying statistical methods to their research. At the same time, aspiring statisticians would be deprived of the hands-on experience with real- world data and collaborative projects. This type of training is essential for their development as professionals and would disappear without the Department. – <a href="letters/Kelsey Karnik-PhDalum.pdf">Kelsey Karnik, Ph.D.&nbsp;and Biomedical Data Scientist, University of Kentucky</a></p>
</blockquote>
<p>Others highlight the importance of the mentoring and relationships built at UNL; these intangibles cannot be captured by metrics but are extremely important, both in demonstrating impact within a field, and in demonstrating the culture within the department.</p>
<blockquote class="blockquote">
<p>During my time at UNL, two professors in particular had a lasting impact on my career. Dr.&nbsp;Erin Blankenship, my first instructor at UNL and later my PhD advisor, sparked in me both a love of statistics and of teaching through her contagious passion and patient mentorship. She guided me through my dissertation with just the right balance of support and independence, and she remains a trusted colleague and collaborator to this day. I also had the privilege of learning from Dr.&nbsp;Chris Bilder, whose clear, detailed instruction provided a model of excellence in teaching. The courses I later developed at NKU in categorical data analysis and applied multivariate analysis were directly inspired by his classes, and I continue to draw on the foundation he built for me. Faculty like Dr.&nbsp;Blankenship and Dr.&nbsp;Bilder exemplify the kind of expertise and dedication that make UNL’s statistics program so impactful, not only to students but to the broader academic community. – <a href="letters/Jacqueline Herman.pdf">Jacqueline Herman, Ph.D., Professor and Statistics Program Coordinator, Northern Kentucky University</a></p>
</blockquote>
<p>The mentoring and relationships continue to be important long after students have graduated, as they continue to talk with professors in the department about interesting problems they have encountered.</p>
<blockquote class="blockquote">
<p>Beyond my initial education, the Statistics Department has remained an invaluable resource throughout my career. The ability to consult with my former professors when facing complex statistical challenges has been critical to my success. This ongoing support underscores the department’s role not only in educating students but also in fostering a lifelong connection with alumni who contribute to society and the economy. – <a href="letters/zhao_MS.pdf">Qingwen Zhao, MS Biometry, 1996. President AM Solutions, LLC</a></p>
</blockquote>
<p>Statistics maintains joint degree programs with other disciplines, which provide students with the opportunity to pursue interdisciplinary studies during their graduate training as well as in their later careers.</p>
<blockquote class="blockquote">
<p>Statistics has been a cornerstone of my academic and professional growth. Pursuing a joint Ph.D.&nbsp;in Economics and Statistics gave me a deeper analytical foundation and sharper research skills than economics alone could provide. Because of this combined training, I entered the job market with a distinct advantage. Employers across sectors increasingly value candidates who can apply statistical reasoning to complex economic and policy questions, and this dual expertise opened opportunities that would not have been available otherwise. Today, I serve as an external faculty member in a statistical consulting unit, even though my primary appointment is in a different college. This role allows me to collaborate across disciplines, demonstrating how statistical skills complement and enhance work in economics, business, the social sciences, and beyond. From my experience, students who strengthen their analytical abilities through statistics are better prepared for the evolving workforce. The discipline fosters critical thinking, data literacy, and problem-solving—skills that are essential in research, industry, and government. When paired with fields like economics, these abilities create graduates who are adaptable and highly sought after. – <a href="letters/Mariana SaenzAyala - UNL grad.pdf">Mariana Saenz-Ayala, Ph.D.&nbsp;Economics and Statistics &amp; Associate Professor of Economics, Georgia Southern University</a></p>
</blockquote>
<p>Our graduates often consider themselves part of the department even after they have graduated and begun professional careers, highlighting just how much of a community students have at UNL. It is hard to rebuild this type of culture, but it is critically important both for student retention and for alumni fundraising once current students have gone on to get well-paying jobs.</p>
<blockquote class="blockquote">
<p>While I am sure that every other department on the chopping block is also defending their department relentlessly and is arguing as hard as we are, I hope you consider that the Statistics Department stands out among all the other departments on your list. The statistics department is the only department that fosters tools, research, and analysis, that will address emerging challenges in a data-rich world. Not to mention, the ever-growing fields like AI and Machine Learning that require a fundamental knowledge of Statistics and Data Science. – <a href="letters/Paulus Hermanto - UNL grad.pdf">Paulus Hermanto, MS Statistics, 2023</a></p>
</blockquote>
<p>Our current students gave up careers and stable employment to come to this department because of its reputation for excellence.</p>
<blockquote class="blockquote">
<p>I moved to the U.S. nearly two months ago to begin my Master’s/Ph.D.&nbsp;in Statistics at UNL. Before coming here, I had a very stable life and a good job as a math teacher in Vietnam, where I had worked for 8 years. A lot of people asked me if it was worth it when I gave up a very stable job, good income, and familiarity to start over in a new country. But I persisted that my dream was to gain a deep knowledge and research skills in statistics. I believed that UNL was the right place to make that dream come true. I chose UNL over another school in Ohio that also offered me funding because I believed in UNL’s reputation and commitment to excellence. – <a href="letters/ThuDang.pdf">Thu Dang, current MS/Ph.D.&nbsp;student</a> (Ms.&nbsp;Dang began classes at UNL in Fall 2025)</p>
</blockquote>
<p>The community our students find in the department, and the traditions among the graduate students (such as the midwesterners taking everyone from tropical regions coat shopping in mid-October to ensure they are well equipped for winter) are very important parts of our departmental culture.</p>
<blockquote class="blockquote">
<p>As a first year, native Nebraskan PhD student in statistics I feel inclined to share my thoughts and feelings on the proposed budget cuts. I feel the proposed budget cuts would be a grave injustice not only for the faculty and students of statistics department but for the state of Nebraska as a whole. I have lived in Nebraska for the past 22 years of my life and have seen the impact which statistics and data driven solutions can provide.</p>
<p>I already have a master’s degree in mathematics from UNO and I received an internship at Smeal Fire Apparatus in Snyder, NE this past summer where I worked as a Supply Chain and Logistics intern. With my gained analytical experience I was able to create an automated vendor quality assessment system which in turn increased profitability for the company. This not only benefited me but because of what I did this helped us switch vendors and enable the shop to be able to meet quarterly goals which resulted in a plant wide bonuses. Not only did this leave a good impression with my superiors, but enabled two hundred fellow Nebraskans to have more money to spend in the economy of Nebraska. With a PhD in Statistics and a desire to stay in state after graduation more meaningful procedures would be created to continue to not only generate myself an income but help Nebraskan citizens. A PhD in Statistics would give me more skills to continue to do work like this for the industry throughout the state.</p>
<p>However, not only have I seen the impact of statistics at my place of work but in the agricultural sector. My fiancee is from a farm and getting seeds which yield the best crops is a means to an income for her family. These seeds are developed in labs and tested. These results are verified and analyzed through statistical means. Cutting the statistics department would partially eliminate the state’s ability to perform important agricultural analysis which improve the state’s primary economic sector. Since UNL is the only university in the state with a PhD in statistics, eliminating people valuable to agricultural sector seems counterproductive to statewide economic hopes.</p>
<p>If UNL cuts their statistics program I do intend to transfer to another Big Ten university. The reason I choose Nebraska is because of my personal ties to this state, my love of the genuinely caring helpful faculty, and the familial feeling on the third floor of Hardin Hall. Our department provides services to other departments including offering necessary classes to help others gain meaningful data driven insights along with analyses for others thesis’s and dissertations. We collaborate across fields to further research at the Nebraska’s only R1 institution. I believe our department is a crucial part to UNL’s standing as an R1 institution and plays a vital role in getting Nebraska back into the AAU. – <a href="letters/ThomasSpoehr_MSstudent.docx.pdf">Thomas Spoehr, MS/Ph.D.&nbsp;student in Statistics</a> (Mr.&nbsp;Spoehr started his coursework in Fall 2025)</p>
</blockquote>
<p>Ultimately, the graduate programs at UNL are increasing in visibility and in academic rankings not only because of the department’s efforts to continuously improve our programs, but because of our graduates – the relationships they built and the education they received through our programs is the foundation for a promising future, if the APC and Chancellor reconsider the proposal to eliminate the department.</p>
<blockquote class="blockquote">
<p>My experience at UNL was not only academically enriching but also personally rewarding. The friendships and professional relationships I built during my time there continue to support my career. Similarly, my fellow graduates share my view that the education we received was unparalleled, empowering us to excel as educators, researchers, and colleagues. I urge the university leadership to reconsider the elimination of the Department of Statistics. Preserving and strengthening this department is crucial for the continued success and excellence of UNL. – <a href="letters/MarinaPtukhina-StatPhDgrad-WhitmanU.pdf">Marina Ptukhina, Ph.D., Associate Professor, Department of Mathematics and Statistics, Whitman College</a></p>
</blockquote>


</section>
<section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes">
<hr>
<ol>
<li id="fn1"><p>It will take some work to undo the damage from the public proposal to eliminate the program, but we believe the economic conditions are sufficient to make this a worthwhile investment for UNL. <a href="future.html" class="quarto-xref"><span>Chapter 9</span></a> discusses several options for the future of the program which could mitigate this obstacle and could significantly improve enrollment in the program.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p>USNWR does not archive past rankings, so this information was obtained from a contemporaneous <a href="https://forum.thegradcafe.com/topic/12360-thoughts-on-new-rankings-for-stats-programs/">graduate cafe forum post</a>, which is sub optimal but necessary for obtaining historical information.<a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn3"><p>An informal survey of current students suggests the CASNR general education requirements are perceived as less useful or relevant than similar requirements in CAS and COE.<a href="#fnref3" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn4"><p>The public plan released by IANR does not include 318, 462, and 463, which have been identified as essential by CAS. As a result, there would not be sufficient Statistics courses to complete the Data Science major, or the Mathematics degree with Finance or the Statistics and Data Science options.<a href="#fnref4" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn5"><p>Nate Silver, Joint Statistical Meetings, 2013.<a href="#fnref5" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn6"><p>Course development has occurred without course releases, representing a significant increase in effective teaching workload and requiring unpaid work during the summer and winter breaks to prepare 1-2 new preps every academic year for some of the faculty in the department.<a href="#fnref6" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn7"><p>Under the current program, however, graduate statistics students no longer take Stat 801 and 802.<a href="#fnref7" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./peer-analysis.html" class="pagination-link" aria-label="Peer Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Peer Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./centralized.html" class="pagination-link" aria-label="Centralized vs. Distributed Statistics Model">
        <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Centralized vs.&nbsp;Distributed Statistics Model</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","descPosition":"bottom","loop":false,"openEffect":"zoom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>